Repository QuiltMC/quilt-mappings, pull requests merged in 2021-12, with the labels that each got.

#61 Screen constants
  mappings/net/minecraft/client/gui/screen/BackupPromptScreen.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmScreen.mapping
  mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeFlatLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/DialogScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameModeSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/LevelLoadingScreen.mapping
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/SleepingChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/SplashOverlay.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/MerchantScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/narration/ScreenNarrator.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AnimatedResultButton.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeAlternativesWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookResults.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeGroupButtonWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/EditGameRulesScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/gui/screen/world/SelectWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
Labels: new, port, release, ready to merge

#62 1.18.1-pre1 stuff
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/collection/IndexedIterable.mapping
Labels: new, snapshot, ready to merge

#57 World tick mappings
  mappings/net/minecraft/nbt/NbtList.mapping
  mappings/net/minecraft/util/profiler/Profiler.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/tick/BasicTickScheduler.mapping
  mappings/net/minecraft/world/tick/ChunkTickScheduler.mapping
  mappings/net/minecraft/world/tick/OrderedTick.mapping
  mappings/net/minecraft/world/tick/QueryableTickScheduler.mapping
  mappings/net/minecraft/world/tick/SerializableTickScheduler.mapping
  mappings/net/minecraft/world/tick/Tick.mapping
  mappings/net/minecraft/world/tick/TickScheduler.mapping
  mappings/net/minecraft/world/tick/WorldTickScheduler.mapping
Labels: new, port, snapshot

#56 Refactor Options, map 1.18 things, and more
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/Option.mapping
  mappings/net/minecraft/client/option/SmoothLightingMode.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
Labels: refactor, new, snapshot

#55 Some biome and chunk generator mappings
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/world/biome/GenerationSettings.mapping
  mappings/net/minecraft/world/biome/OverworldBiomeCreator.mapping
  mappings/net/minecraft/world/biome/TheEndBiomeCreator.mapping
  mappings/net/minecraft/world/biome/TheNetherBiomeCreator.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/biome/source/BiomeSupplier.mapping
  mappings/net/minecraft/world/biome/source/CheckerboardBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/FixedBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/TheEndBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/util/MultiNoiseUtil.mapping
  mappings/net/minecraft/world/gen/BitRandom.mapping
  mappings/net/minecraft/world/gen/GaussianGenerator.mapping
  mappings/net/minecraft/world/gen/LegacySimpleRandom.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/StructuresConfig.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/feature/VegetationPlacedFeatures.mapping
Labels: new, port, release

#63 1.18.1-rc1 stuff
  mappings/net/minecraft/client/gl/Uniform.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/RealmsError.mapping
  mappings/net/minecraft/client/realms/exception/RealmsServiceException.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsGenericErrorScreen.mapping
  mappings/net/minecraft/client/render/Shader.mapping
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: new, release, ready to merge

#69 Fix hoglin repellent names
  mappings/net/minecraft/entity/ai/brain/sensor/HoglinSpecificSensor.mapping
  mappings/net/minecraft/entity/mob/HoglinBrain.mapping
Labels: refactor, release
