Repository QuiltMC/quilt-mappings, pull requests merged in 2021-11, with the labels that each got.

#28 Some networking mappings
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/network/NetworkState.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChunkData.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChunkDataS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameJoinS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/LightData.mapping
  mappings/net/minecraft/network/packet/s2c/play/LightUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/SetSimulationDistanceS2CPacket.mapping
Labels: new, snapshot, ready to merge

#27 Telemetry mappings
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/main/Main.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/util/Session.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryConstants.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryManager.mapping
  mappings/net/minecraft/util/ModStatus.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: new, snapshot, ready to merge

#25 Chunk and world-related mappings
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/unmapped/C_avyoogzg.mapping
  mappings/net/minecraft/world/SpawnDensityCapper.mapping
  mappings/net/minecraft/world/StructureHolder.mapping
  mappings/net/minecraft/world/biome/source/BiomeAccess.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/ProtoChunk.mapping
  mappings/net/minecraft/world/chunk/ReadOnlyChunk.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
Labels: new, snapshot, ready to merge

#21 Mob and peaceful entities mappings
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/mob/DrownedEntity.mapping
  mappings/net/minecraft/entity/mob/EndermanEntity.mapping
  mappings/net/minecraft/entity/mob/EvokerFangsEntity.mapping
  mappings/net/minecraft/entity/mob/Hoglin.mapping
  mappings/net/minecraft/entity/mob/HoglinBrain.mapping
  mappings/net/minecraft/entity/mob/HoglinEntity.mapping
  mappings/net/minecraft/entity/mob/IllusionerEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/Monster.mapping
  mappings/net/minecraft/entity/mob/PatrolEntity.mapping
  mappings/net/minecraft/entity/mob/PhantomEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
  mappings/net/minecraft/entity/mob/PiglinBruteBrain.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/mob/PillagerEntity.mapping
  mappings/net/minecraft/entity/mob/RavagerEntity.mapping
  mappings/net/minecraft/entity/mob/ShulkerEntity.mapping
  mappings/net/minecraft/entity/mob/SpiderEntity.mapping
  mappings/net/minecraft/entity/mob/VexEntity.mapping
  mappings/net/minecraft/entity/mob/ZoglinEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieVillagerEntity.mapping
  mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
  mappings/net/minecraft/entity/passive/AxolotlBrain.mapping
  mappings/net/minecraft/entity/passive/AxolotlEntity.mapping
  mappings/net/minecraft/entity/passive/BatEntity.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/entity/passive/CatEntity.mapping
  mappings/net/minecraft/entity/passive/ChickenEntity.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/GoatBrain.mapping
  mappings/net/minecraft/entity/passive/GoatEntity.mapping
  mappings/net/minecraft/entity/passive/HorseBaseEntity.mapping
  mappings/net/minecraft/entity/passive/LlamaEntity.mapping
  mappings/net/minecraft/entity/passive/MerchantEntity.mapping
  mappings/net/minecraft/entity/passive/OcelotEntity.mapping
  mappings/net/minecraft/entity/passive/PandaEntity.mapping
  mappings/net/minecraft/entity/passive/ParrotEntity.mapping
  mappings/net/minecraft/entity/passive/PassiveEntity.mapping
  mappings/net/minecraft/entity/passive/PolarBearEntity.mapping
  mappings/net/minecraft/entity/passive/RabbitEntity.mapping
  mappings/net/minecraft/entity/passive/SheepEntity.mapping
  mappings/net/minecraft/entity/passive/SnowGolemEntity.mapping
  mappings/net/minecraft/entity/passive/SquidEntity.mapping
  mappings/net/minecraft/entity/passive/TropicalFishEntity.mapping
  mappings/net/minecraft/entity/passive/TurtleEntity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/entity/passive/WanderingTraderEntity.mapping
Labels: new, snapshot

#31 Improve some mappings from #21
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/passive/AxolotlBrain.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/entity/passive/CatEntity.mapping
  mappings/net/minecraft/entity/passive/GoatBrain.mapping
  mappings/net/minecraft/entity/passive/GoatEntity.mapping
  mappings/net/minecraft/entity/passive/PandaEntity.mapping
  mappings/net/minecraft/entity/passive/TropicalFishEntity.mapping
  mappings/net/minecraft/entity/passive/TurtleEntity.mapping
Labels: refactor, snapshot, ready to merge

#36 Port datafixer mappings from yarn
  mappings/net/minecraft/datafixer/fix/AddFlagIfNotPresentFix.mapping
  mappings/net/minecraft/datafixer/fix/BlockEntityIdFix.mapping
  mappings/net/minecraft/datafixer/fix/BlockStateFlattening.mapping
  mappings/net/minecraft/datafixer/fix/ChunkHeightAndBiomeFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkLevelTagRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkPalettedStorageFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkStructuresTemplateRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkToProtoChunkFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityBlockStateFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityIdFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityPaintingMotiveFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityRedundantChanceTagsFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemIdFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemInstanceSpawnEggFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemInstanceTheFlatteningFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemPotionFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemStackEnchantmentFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemStackUuidFix.mapping
  mappings/net/minecraft/datafixer/fix/LeavesFix.mapping
  mappings/net/minecraft/datafixer/fix/LevelDataGeneratorOptionsFix.mapping
  mappings/net/minecraft/datafixer/fix/LevelFlatGeneratorInfoFix.mapping
  mappings/net/minecraft/datafixer/fix/NewVillageFix.mapping
  mappings/net/minecraft/datafixer/fix/OptionsKeyLwjgl3Fix.mapping
  mappings/net/minecraft/datafixer/fix/PointOfInterestRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/ProtoChunkTickListFix.mapping
  mappings/net/minecraft/datafixer/fix/SavedDataVillageCropFix.mapping
  mappings/net/minecraft/datafixer/fix/StatsCounterFix.mapping
  mappings/net/minecraft/datafixer/fix/UntaggedSpawnerFix.mapping
  mappings/net/minecraft/datafixer/fix/VillagerXpRebuildFix.mapping
  mappings/net/minecraft/datafixer/fix/WorldGenSettingsDisallowOldCustomWorldsFix.mapping
  mappings/net/minecraft/datafixer/fix/WorldGenSettingsHeightAndBiomeFix.mapping
  mappings/net/minecraft/datafixer/fix/WorldUuidFix.mapping
  mappings/net/minecraft/datafixer/mapping/LegacyBiomeMapping.mapping
  mappings/net/minecraft/datafixer/schema/Schema2831.mapping
  mappings/net/minecraft/datafixer/schema/Schema2832.mapping
  mappings/net/minecraft/datafixer/schema/Schema2842.mapping
Labels: new, port, snapshot

#37 Port data gen, advancement criterion and some other random mappings
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/TravelCriterion.mapping
  mappings/net/minecraft/advancement/criterion/VillagerTradeCriterion.mapping
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/model/Texture.mapping
  mappings/net/minecraft/data/client/model/When.mapping
  mappings/net/minecraft/data/dev/NbtProvider.mapping
  mappings/net/minecraft/data/report/RegistryDumpProvider.mapping
  mappings/net/minecraft/data/server/AbstractTagProvider.mapping
  mappings/net/minecraft/data/server/AdvancementsProvider.mapping
  mappings/net/minecraft/data/server/AdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/BlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/FishingLootTableGenerator.mapping
  mappings/net/minecraft/data/server/HusbandryTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/LootTablesProvider.mapping
  mappings/net/minecraft/fluid/FlowableFluid.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/nbt/visitor/NbtOrderedStringFormatter.mapping
  mappings/net/minecraft/nbt/visitor/NbtTextFormatter.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/tag/Tag.mapping
  mappings/net/minecraft/tag/TagManagerLoader.mapping
  mappings/net/minecraft/text/Style.mapping
  mappings/net/minecraft/village/Merchant.mapping
Labels: new, port, snapshot

#39 Map shared constants and fix some typos
  mappings/net/minecraft/SharedConstants.mapping
Labels: new, snapshot

#7 Completely redo the QM buildscript into Java
  .github/workflows/publish.yml
  .gitignore
  README.md
  build.gradle
  buildSrc/build.gradle
  buildSrc/gradle.properties
  buildSrc/src/main/java/quilt/internal/Constants.java
  buildSrc/src/main/java/quilt/internal/FileConstants.java
  buildSrc/src/main/java/quilt/internal/MappingsExtension.java
  buildSrc/src/main/java/quilt/internal/MappingsPlugin.java
  buildSrc/src/main/java/quilt/internal/tasks/DefaultMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/MappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractTinyMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AddProposedFieldMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/BuildMappingsTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/CheckMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/CompressTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/InvertPerVersionMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MappingsV2JarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyV2Task.java
  buildSrc/src/main/java/quilt/internal/tasks/build/TinyJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/jarmapping/MapNamedJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/jarmapping/MapPerVersionMappingsJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/mappings/EnigmaMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadMinecraftJarsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadMinecraftLibrariesTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadPerVersionMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadVersionsManifestTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadWantedVersionManifestTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/ExtractServerJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/MergeJarsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/UnpickJarTask.java
  buildSrc/src/main/java/quilt/internal/util/DownloadImmediate.java
  buildSrc/src/main/java/quilt/internal/util/JarRemapper.java
Labels: toolchain, update-base, snapshot

#44 Fix update base script
  .github/actions/update-base/.gitignore
  .github/actions/update-base/action.yml
  .github/actions/update-base/dist/index.mjs
  .github/actions/update-base/index.mjs
  .github/actions/update-base/package-lock.json
  .github/actions/update-base/package.json
  .github/workflows/update-base.yml
Labels: bug, toolchain, snapshot

#38 Port block mappings
  mappings/net/minecraft/block/AbstractBannerBlock.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractLichenBlock.mapping
  mappings/net/minecraft/block/AbstractPlantStemBlock.mapping
  mappings/net/minecraft/block/AmethystClusterBlock.mapping
  mappings/net/minecraft/block/BedBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/ChestBlock.mapping
  mappings/net/minecraft/block/ComparatorBlock.mapping
  mappings/net/minecraft/block/ConnectingBlock.mapping
  mappings/net/minecraft/block/DetectorRailBlock.mapping
  mappings/net/minecraft/block/DispenserBlock.mapping
  mappings/net/minecraft/block/EntityShapeContext.mapping
  mappings/net/minecraft/block/FireBlock.mapping
  mappings/net/minecraft/block/FluidBlock.mapping
  mappings/net/minecraft/block/HorizontalConnectingBlock.mapping
  mappings/net/minecraft/block/MapColor.mapping
  mappings/net/minecraft/block/PowderSnowBlock.mapping
  mappings/net/minecraft/block/RespawnAnchorBlock.mapping
  mappings/net/minecraft/block/ShulkerBoxBlock.mapping
  mappings/net/minecraft/block/StonecutterBlock.mapping
  mappings/net/minecraft/block/VineBlock.mapping
  mappings/net/minecraft/block/WitherSkullBlock.mapping
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/BannerBlockEntity.mapping
  mappings/net/minecraft/block/entity/BeehiveBlockEntity.mapping
  mappings/net/minecraft/block/entity/BellBlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/block/entity/ConduitBlockEntity.mapping
  mappings/net/minecraft/block/entity/HopperBlockEntity.mapping
  mappings/net/minecraft/block/entity/JigsawBlockEntity.mapping
  mappings/net/minecraft/block/entity/StructureBlockBlockEntity.mapping
  mappings/net/minecraft/block/enums/JigsawOrientation.mapping
  mappings/net/minecraft/block/pattern/BlockPattern.mapping
  mappings/net/minecraft/block/pattern/BlockPatternBuilder.mapping
  mappings/net/minecraft/block/pattern/CachedBlockPosition.mapping
Labels: new, port, snapshot

#40 Sound mappings
  mappings/net/minecraft/client/sound/AbstractBeeSoundInstance.mapping
  mappings/net/minecraft/client/sound/AmbientSoundLoops.mapping
  mappings/net/minecraft/client/sound/AmbientSoundPlayer.mapping
  mappings/net/minecraft/client/sound/BiomeEffectSoundPlayer.mapping
  mappings/net/minecraft/client/sound/Channel.mapping
  mappings/net/minecraft/client/sound/ElytraSoundInstance.mapping
  mappings/net/minecraft/client/sound/GuardianAttackSoundInstance.mapping
  mappings/net/minecraft/client/sound/MinecartInsideSoundInstance.mapping
  mappings/net/minecraft/client/sound/MovingMinecartSoundInstance.mapping
  mappings/net/minecraft/client/sound/MusicTracker.mapping
  mappings/net/minecraft/client/sound/MusicType.mapping
  mappings/net/minecraft/client/sound/OggAudioStream.mapping
  mappings/net/minecraft/client/sound/RepeatingAudioStream.mapping
  mappings/net/minecraft/client/sound/Sound.mapping
  mappings/net/minecraft/client/sound/SoundEngine.mapping
  mappings/net/minecraft/client/sound/SoundLoader.mapping
  mappings/net/minecraft/client/sound/SoundManager.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
  mappings/net/minecraft/client/sound/Source.mapping
  mappings/net/minecraft/client/sound/WeightedSoundSet.mapping
Labels: new, port, snapshot

#42 Map the new Online Options screen (and friends)
  mappings/net/minecraft/client/gui/screen/option/OnlineOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/OptionsScreen.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/Option.mapping
Labels: new, snapshot

#49 Integrate Filament into buildscript
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/quilt/internal/Constants.java
  buildSrc/src/main/java/quilt/internal/MappingsPlugin.java
  buildSrc/src/main/java/quilt/internal/tasks/build/GeneratePackageInfoMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MappingsV2JarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/JavadocLintTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/CombineUnpickDefinitionsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/RemapUnpickDefinitionsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/UnpickJarTask.java
  buildSrc/src/main/java/quilt/internal/util/UnpickUtil.java
Labels: enhancement, refactor, toolchain

#50 Add mappingLint task replacing javadocLint
  build.gradle
  buildSrc/src/main/java/quilt/internal/Constants.java
  buildSrc/src/main/java/quilt/internal/MappingsPlugin.java
  buildSrc/src/main/java/quilt/internal/tasks/build/GeneratePackageInfoMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/Checker.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/ErrorReporter.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/FieldNamingChecker.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/JavadocChecker.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/JavadocLintTask.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/MappingLintTask.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/Severity.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/RemapUnpickDefinitionsTask.java
  mappings/net/minecraft/unused/packageinfo/PackageInfoJrzdbbtu.mapping
Labels: enhancement, toolchain, snapshot

#54 Revert get prefix dropping, fix some other stuff.
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/tag/Tag.mapping
Labels: bug, enhancement, refactor

#41 Javadoc the enchantments package
  gradle/wrapper/gradle-wrapper.properties
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/enchantment/EnchantmentTarget.mapping
Labels: snapshot, javadoc

#43 Add decompiler API
  build.gradle
  buildSrc/build.gradle
  buildSrc/gradle.properties
  buildSrc/src/main/java/quilt/internal/Constants.java
  buildSrc/src/main/java/quilt/internal/decompile/AbstractDecompiler.java
  buildSrc/src/main/java/quilt/internal/decompile/DecompilerProvider.java
  buildSrc/src/main/java/quilt/internal/decompile/Decompilers.java
  buildSrc/src/main/java/quilt/internal/decompile/cfr/CfrDecompiler.java
  buildSrc/src/main/java/quilt/internal/decompile/cfr/CfrObfuscationMapping.java
  buildSrc/src/main/java/quilt/internal/decompile/cfr/CfrSinkFactory.java
  buildSrc/src/main/java/quilt/internal/decompile/javadoc/ClassJavadocProvider.java
  buildSrc/src/main/java/quilt/internal/decompile/javadoc/FieldJavadocProvider.java
  buildSrc/src/main/java/quilt/internal/decompile/javadoc/MethodJavadocProvider.java
  buildSrc/src/main/java/quilt/internal/decompile/quiltflower/QuiltflowerDecompiler.java
  buildSrc/src/main/java/quilt/internal/decompile/quiltflower/QuiltflowerJavadocProvider.java
  buildSrc/src/main/java/quilt/internal/decompile/quiltflower/QuiltflowerResultSaver.java
  buildSrc/src/main/java/quilt/internal/tasks/decompile/DecompileTask.java
  gradle.properties
Labels: enhancement, refactor, toolchain, snapshot

#58 Add some NBT mappings.
  mappings/net/minecraft/nbt/AbstractNbtList.mapping
  mappings/net/minecraft/nbt/NbtByte.mapping
  mappings/net/minecraft/nbt/NbtByteArray.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/nbt/NbtDouble.mapping
  mappings/net/minecraft/nbt/NbtElement.mapping
  mappings/net/minecraft/nbt/NbtFloat.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/nbt/NbtInt.mapping
  mappings/net/minecraft/nbt/NbtIntArray.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/nbt/NbtList.mapping
  mappings/net/minecraft/nbt/NbtLong.mapping
  mappings/net/minecraft/nbt/NbtLongArray.mapping
  mappings/net/minecraft/nbt/NbtNull.mapping
  mappings/net/minecraft/nbt/NbtOps.mapping
  mappings/net/minecraft/nbt/NbtShort.mapping
  mappings/net/minecraft/nbt/NbtString.mapping
  mappings/net/minecraft/nbt/NbtType.mapping
  mappings/net/minecraft/nbt/scanner/NbtCollector.mapping
  mappings/net/minecraft/nbt/scanner/NbtScanner.mapping
  mappings/net/minecraft/nbt/scanner/SelectiveNbtCollector.mapping
  mappings/net/minecraft/nbt/scanner/SimpleNbtScanner.mapping
  mappings/net/minecraft/nbt/visitor/NbtElementVisitor.mapping
  mappings/net/minecraft/nbt/visitor/NbtTextFormatter.mapping
Labels: new, port, snapshot, ready to merge, javadoc

#59 Add dropInvalidMappings task
  buildSrc/gradle.properties
  buildSrc/src/main/java/quilt/internal/MappingsPlugin.java
  buildSrc/src/main/java/quilt/internal/tasks/build/DropInvalidMappingsTask.java
  gradle.properties
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/util/dynamic/RegistryOps.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/tick/OrderedTick.mapping
  mappings/net/minecraft/world/tick/Tick.mapping
Labels: enhancement, toolchain, snapshot, ready to merge
