Repository QuiltMC/quilt-mappings, pull requests merged in 2021-09, with the labels that each got.

#3 Map all shared constants
  mappings/net/minecraft/SharedConstants.mapping
Labels: new

#10 Restore methods and fields that could be matched.
  mappings/net/minecraft/MinecraftVersion.mapping
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/MapColor.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/client/color/world/BiomeColors.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/option/Option.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/sound/SoundEngine.mapping
  mappings/net/minecraft/client/world/BiomeColorCache.mapping
  mappings/net/minecraft/client/world/ClientChunkManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
  mappings/net/minecraft/loot/function/SetContentsLootFunction.mapping
  mappings/net/minecraft/loot/function/SetLootTableLootFunction.mapping
  mappings/net/minecraft/network/packet/s2c/play/BlockEntityUpdateS2CPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/TeamCommand.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/structure/StructureStart.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/world/BlockRenderView.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/MobSpawnerLogic.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/BuiltinBiomes.mapping
  mappings/net/minecraft/world/biome/DefaultBiomeCreator.mapping
  mappings/net/minecraft/world/biome/source/BiomeAccess.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/chunk/ArrayPalette.mapping
  mappings/net/minecraft/world/chunk/BiMapPalette.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/IdListPalette.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/gen/ChunkRandom.mapping
  mappings/net/minecraft/world/gen/NoiseColumnSampler.mapping
  mappings/net/minecraft/world/gen/chunk/AquiferSampler.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/GenerationShapeConfig.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/ConfiguredSurfaceBuilder.mapping
  mappings/net/minecraft/world/level/storage/SaveVersionInfo.mapping
Labels: port

#14 Bunch of 21w38a mappings.
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/Option.mapping
  mappings/net/minecraft/server/command/dev/ChaseCommand.mapping
  mappings/net/minecraft/server/command/dev/ResetChunksCommand.mapping
  mappings/net/minecraft/structure/BuriedTreasureGenerator.mapping
  mappings/net/minecraft/structure/DesertTempleGenerator.mapping
  mappings/net/minecraft/structure/EndCityGenerator.mapping
  mappings/net/minecraft/structure/IglooGenerator.mapping
  mappings/net/minecraft/structure/JungleTempleGenerator.mapping
  mappings/net/minecraft/structure/MineshaftGenerator.mapping
  mappings/net/minecraft/structure/NetherFortressGenerator.mapping
  mappings/net/minecraft/structure/NetherFossilGenerator.mapping
  mappings/net/minecraft/structure/OceanRuinGenerator.mapping
  mappings/net/minecraft/structure/ShipwreckGenerator.mapping
  mappings/net/minecraft/structure/StrongholdGenerator.mapping
  mappings/net/minecraft/structure/StructurePiecesHolder.mapping
  mappings/net/minecraft/structure/StructureStart.mapping
  mappings/net/minecraft/structure/SwampHutGenerator.mapping
  mappings/net/minecraft/structure/WoodlandMansionGenerator.mapping
  mappings/net/minecraft/structure/piece/PoolStructurePiece.mapping
  mappings/net/minecraft/structure/piece/RuinedPortalStructurePiece.mapping
  mappings/net/minecraft/structure/piece/SimpleStructurePiece.mapping
  mappings/net/minecraft/structure/piece/StructurePiece.mapping
  mappings/net/minecraft/structure/piece/StructurePieceSerializationContext.mapping
  mappings/net/minecraft/structure/piece/StructurePieceType.mapping
  mappings/net/minecraft/structure/piece/StructurePieceWithDimensions.mapping
  mappings/net/minecraft/structure/piece/StructurePiecesHolder.mapping
  mappings/net/minecraft/unmapped/C_drcnbecc.mapping
  mappings/net/minecraft/unmapped/C_wwbyxkgc.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrStatsReader.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrStatsResultSerializer.mapping
  mappings/net/minecraft/util/profiling/jfr/data/ServerTickTimeData.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
Labels: refactor, new

#16 Map new shared constants
  mappings/net/minecraft/SharedConstants.mapping
Labels: new
