Repository QuiltMC/quilt-mappings, pull requests merged in 2022-07, with the labels that each got.

#207 Add simple type field auto mapping
  buildSrc/gradle.properties
  enigma_profile.json
  gradle.properties
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  simple_type_field_names.json5
Labels: toolchain, snapshot, final-comment-period, small

#206 Warden mappings
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/client/render/entity/WardenEmissiveLayer.mapping
  mappings/net/minecraft/client/render/entity/WardenRenderer.mapping
  mappings/net/minecraft/client/render/entity/animation/WardenAnimations.mapping
  mappings/net/minecraft/client/render/entity/model/WardenModel.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/NearestLivingEntitiesSensor.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/WardenEntitySensor.mapping
  mappings/net/minecraft/entity/ai/brain/task/DigTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/EmergeTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/InvestigateDisturbanceTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/RoarTargetSelectorTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/RoarTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/SniffTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/SonicBoomTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/StartSniffingTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/WardenLookAtEntityTask.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeNavigator.mapping
  mappings/net/minecraft/entity/effect/StatusEffectUtil.mapping
  mappings/net/minecraft/entity/mob/warden/AngerManager.mapping
  mappings/net/minecraft/entity/mob/warden/AngerState.mapping
  mappings/net/minecraft/entity/mob/warden/ForceUnmountTask.mapping
  mappings/net/minecraft/entity/mob/warden/WardenBrain.mapping
  mappings/net/minecraft/entity/mob/warden/WardenEntity.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/world/event/listener/DynamicGameEventListener.mapping
Labels: t: new, snapshot, reviews needed, final-comment-period, medium

#210 Map ChatNarratorManager and fix some stuff.
  .github/workflows/build.yml
  buildSrc/gradle.properties
  gradle.properties
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/option/NarratorMode.mapping
  mappings/net/minecraft/client/util/ChatNarratorManager.mapping
  simple_type_field_names.json5
Labels: enhancement, t: refactor, t: new, snapshot, javadoc, final-comment-period, small

#211 Map back textRenderer and its new variant, map networking changes.
  build.gradle
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/FontStorage.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/PacketSendListener.mapping
  mappings/net/minecraft/util/math/noise/InterpolatedNoiseSampler.mapping
  mappings/net/minecraft/world/gen/DensityFunctions.mapping
  mappings/net/minecraft/world/gen/feature/IcebergFeature.mapping
Labels: bug, documentation, enhancement, t: refactor, t: new, snapshot, javadoc, reviews needed, small, critical

#204 screen mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/ChatPreview.mapping
  mappings/net/minecraft/client/gui/ChatPreviewRequestHandler.mapping
  mappings/net/minecraft/client/gui/ChatReportCategory.mapping
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmChatLinkScreen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/WarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerWarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/AccessibilityOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/VideoOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeAlternativesWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookGhostSlots.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/gui/screen/world/OptimizeWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/SelectWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/gui/widget/ButtonListWidget.mapping
  mappings/net/minecraft/client/main/Main.mapping
  mappings/net/minecraft/client/network/ClientCommandSource.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/resource/language/LanguageDefinition.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasHolder.mapping
  mappings/net/minecraft/client/texture/TextureManager.mapping
  mappings/net/minecraft/client/util/Session.mapping
  mappings/net/minecraft/command/CommandSource.mapping
  mappings/net/minecraft/command/argument/PreviewedArgumentType.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/CustomPlayerNamesS2CPacket.mapping
  mappings/net/minecraft/util/ChatUtil.mapping
Labels: t: new, snapshot, reviews needed, final-comment-period, medium
