Repository QuiltMC/quilt-mappings, pull requests merged in 2022-10, with the labels that each got.

#227 Add Intermediary Publication
  .gitignore
  build.gradle
  buildSrc/build.gradle
  buildSrc/gradle.properties
  buildSrc/src/main/java/quilt/internal/FileConstants.java
  buildSrc/src/main/java/quilt/internal/MappingsPlugin.java
  buildSrc/src/main/java/quilt/internal/mappingio/CompleteInitializersVisitor.java
  buildSrc/src/main/java/quilt/internal/tasks/DefaultMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/MappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractHashedMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractTinyMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AddProposedMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MappingsV2JarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeIntermediaryTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyV2Task.java
  buildSrc/src/main/java/quilt/internal/tasks/build/RemoveIntermediaryTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/AbstractDownloadMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/CheckIntermediaryMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadIntermediaryMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadMinecraftLibrariesTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadPerVersionMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/gen/OpenGlConstantUnpickGenerator.java
  gradle.properties
  mappings/net/minecraft/client/particle/ParticleGroup.mapping
  mappings/net/minecraft/entity/ai/brain/task/PrepareRamTask.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChunkDeltaUpdateS2CPacket.mapping
  mappings/net/minecraft/particle/ParticleType.mapping
  mappings/net/minecraft/util/math/WordPackedArray.mapping
  settings.gradle
Labels: enhancement, meta, toolchain, final-comment-period, s: small

#243 Update @action/core to v1.9.1 to fix security vulnerability
  .github/actions/update-base/package-lock.json
  .github/actions/update-base/package.json
Labels: toolchain, v: release, final-comment-period, s: small

#240 Shorten FCP length
  CONTRIBUTING.md
Labels: meta, discussion, final-comment-period, s: small

#239 map `TreeDecorator`'s inner class
  mappings/net/minecraft/world/gen/treedecorator/TreeDecorator.mapping
Labels: t: new, v: release, final-comment-period, s: small

#244 Fix some issues
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/net/minecraft/client/font/MultilineText.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/render/DimensionVisualEffects.mapping
  mappings/net/minecraft/client/render/debug/GameTestDebugRenderer.mapping
  mappings/net/minecraft/world/chunk/WrapperProtoChunk.mapping
Labels: bug, t: refactor, v: release, final-comment-period, s: small

#252 Fix javadocs for 22w42a
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/client/multiplayer/chat/ChatLog.mapping
  mappings/net/minecraft/world/RegistryWorldView.mapping
Labels: bug, t: new, v: snapshot, javadoc, reviews needed, s: small, critical

#245 Rename some freezing related mappings
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModels.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/client/render/model/json/ModelOverrideList.mapping
  mappings/net/minecraft/client/sound/SoundManager.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/command/suggestion/SuggestionProviders.mapping
  mappings/net/minecraft/data/server/LootTablesProvider.mapping
  mappings/net/minecraft/data/server/RecipesProvider.mapping
  mappings/net/minecraft/data/server/recipe/ComplexRecipeJsonFactory.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/brain/task/LongJumpTask.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/ServerReloadableResources.mapping
  mappings/net/minecraft/server/command/DatapackCommand.mapping
  mappings/net/minecraft/server/command/TeamMsgCommand.mapping
  mappings/net/minecraft/server/function/FunctionLoader.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
  mappings/net/minecraft/structure/StructureManager.mapping
  mappings/net/minecraft/structure/StructureTemplateManager.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/tag/TagGroupLoader.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
  mappings/net/minecraft/world/level/LevelInfo.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: small

#249 Block Mappings
  mappings/net/minecraft/block/AbstractButtonBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/CarvedPumpkinBlock.mapping
  mappings/net/minecraft/block/ChiseledBookshelfBlock.mapping
  mappings/net/minecraft/block/DoorBlock.mapping
  mappings/net/minecraft/block/FenceGateBlock.mapping
  mappings/net/minecraft/block/PressurePlateBlock.mapping
  mappings/net/minecraft/block/SideShapeType.mapping
  mappings/net/minecraft/block/TrapdoorBlock.mapping
  mappings/net/minecraft/block/WeightedPressurePlateBlock.mapping
  mappings/net/minecraft/block/entity/BeaconBlockEntity.mapping
  mappings/net/minecraft/block/entity/ChiseledBookshelfBlockEntity.mapping
  mappings/net/minecraft/block/entity/JukeboxBlockEntity.mapping
  mappings/net/minecraft/item/MusicDiscItem.mapping
  mappings/net/minecraft/state/property/Properties.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#250 Map new resource loader stuff.
  mappings/net/minecraft/resource/MultiPackResourceManager.mapping
  mappings/net/minecraft/resource/NamespaceResourceManager.mapping
  mappings/net/minecraft/resource/Resource.mapping
  mappings/net/minecraft/resource/ResourceFactory.mapping
  mappings/net/minecraft/resource/ResourceIoSupplier.mapping
  mappings/net/minecraft/resource/ResourceMetadata.mapping
  mappings/net/minecraft/resource/pack/AbstractFileResourcePack.mapping
  mappings/net/minecraft/resource/pack/DefaultResourcePack.mapping
  mappings/net/minecraft/resource/pack/NioResourcePack.mapping
  mappings/net/minecraft/resource/pack/ResourcePack.mapping
  mappings/net/minecraft/resource/pack/ResourcePackProfile.mapping
  mappings/net/minecraft/resource/pack/ResourcePackSource.mapping
  mappings/net/minecraft/resource/pack/ZipResourcePack.mapping
  mappings/net/minecraft/resource/pack/metadata/BuiltInMetadata.mapping
  mappings/net/minecraft/resource/pack/metadata/MetadataSectionType.mapping
  mappings/net/minecraft/resource/pack/metadata/PackResourceMetadata.mapping
  mappings/net/minecraft/resource/pack/metadata/ResourceFilterMetadata.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/util/FileNameUtil.mapping
  mappings/net/minecraft/util/Identifier.mapping
  simple_type_field_names.json5
Labels: t: new, v: snapshot, final-comment-period, s: medium, critical

#248 Sign Mappings
  mappings/net/minecraft/block/AbstractSignBlock.mapping
  mappings/net/minecraft/block/CeilingHangingSignBlock.mapping
  mappings/net/minecraft/block/WallHangingSignBlock.mapping
  mappings/net/minecraft/block/entity/HangingSignBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractSignEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HangingSignEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SignEditScreen.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/block/entity/HangingSignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/state/properties/RotationSegment.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#256 ItemGroup mappings
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/item/LinkedItemStackHashSet.mapping
  simple_type_field_names.json5
Labels: t: new, v: snapshot, final-comment-period, s: small

#261 restore playSound mapping in World
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#262 Rename `ConditionalOverlayOwner` to `EnergySwirlOwner`
  mappings/net/minecraft/client/render/entity/feature/ConditionalOverlayOwner.mapping
  mappings/net/minecraft/client/render/entity/feature/EnergySwirlOwner.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: small

#264 Fix missing mappings and add ButtonWidget mappings.
  mappings/net/minecraft/client/gui/Drawable.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/widget/ButtonWidget.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
Labels: t: new, t: port, v: snapshot, s: small, critical

#263 Update QuiltFlower
  build.gradle
  buildSrc/gradle.properties
  buildSrc/src/main/java/quilt/internal/tasks/build/TransformJarClassesTask.java
  gradle.properties
Labels: toolchain, v: snapshot, final-comment-period, s: small
