Repository QuiltMC/quilt-mappings, pull requests merged in 2022-02, with the labels that each got.

#80 Drop invalid mappings in the update-base workflow
  .github/actions/update-base/action.yml
  .github/actions/update-base/dist/index.js
  .github/actions/update-base/index.js
  .github/actions/update-base/package-lock.json
  .github/workflows/update-base.yml
Labels: enhancement, toolchain, ready to merge

#76 Map all unmapped classes
  mappings/net/minecraft/command/argument/BlockPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/IdentifierArgumentType.mapping
  mappings/net/minecraft/data/info/WorldgenRegistryDumpReport.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/item/BlockPredicatesChecker.mapping
  mappings/net/minecraft/nbt/visitor/FieldSelector.mapping
  mappings/net/minecraft/nbt/visitor/FieldTree.mapping
  mappings/net/minecraft/nbt/visitor/SkipFields.mapping
  mappings/net/minecraft/network/NetworkState.mapping
  mappings/net/minecraft/network/listener/PacketListener.mapping
  mappings/net/minecraft/network/protocol/game/ServerPacketListener.mapping
  mappings/net/minecraft/server/command/LocateBiomeCommand.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
  mappings/net/minecraft/server/command/SpreadPlayersCommand.mapping
  mappings/net/minecraft/server/commands/PlaceFeatureCommand.mapping
  mappings/net/minecraft/unmapped/C_empvvetb.mapping
  mappings/net/minecraft/util/FastBufferedInputStream.mapping
  mappings/net/minecraft/util/Graph.mapping
  mappings/net/minecraft/util/SimpleBitStorage.mapping
  mappings/net/minecraft/util/ZeroBitStorage.mapping
  mappings/net/minecraft/util/collection/PackedIntegerArray.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/profiling/jfr/JvmProfiler.mapping
  mappings/net/minecraft/util/profiling/jfr/stats/NetworkPacketSummary.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/world/BlockCollisions.mapping
  mappings/net/minecraft/world/ChunkPosDistanceLevelPropagator.mapping
  mappings/net/minecraft/world/chunk/ChunkNbtScanner.mapping
  mappings/net/minecraft/world/chunk/ChunkTickTracker.mapping
  mappings/net/minecraft/world/chunk/SingleValuePalette.mapping
  mappings/net/minecraft/world/chunk/light/LevelPropagator.mapping
  mappings/net/minecraft/world/gen/BelowZeroRetrogen.mapping
  mappings/net/minecraft/world/gen/DensityConstants.mapping
  mappings/net/minecraft/world/gen/feature/PlacedFeature.mapping
  mappings/net/minecraft/world/gen/material/MaterialRuleList.mapping
  mappings/net/minecraft/world/gen/material/WorldGenMaterialRule.mapping
  mappings/net/minecraft/world/gen/structure/NoiseAffectingStructureFeature.mapping
  mappings/net/minecraft/world/gen/structure/StructureCheck.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
  mappings/net/minecraft/world/storage/loot/functions/SetPotionFunction.mapping
  mappings/net/minecraft/world/tick/ProtoChunkTicks.mapping
  mappings/net/minecraft/world/tick/Tick.mapping
  mappings/net/minecraft/world/tick/WorldGenTickScheduler.mapping
Labels: new, snapshot, ready to merge

#79 Map NoiseSampler (was NoiseColumnSampler)
  mappings/net/minecraft/world/biome/source/util/TerrainNoisePoint.mapping
  mappings/net/minecraft/world/biome/source/util/VanillaTerrainParameters.mapping
  mappings/net/minecraft/world/gen/NoiseColumnSampler.mapping
  mappings/net/minecraft/world/gen/NoiseSampler.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkNoiseSampler.mapping
Labels: new, snapshot, ready to merge

#73 Add new JavaDoc generation
  CONVENTIONS.md
  README.md
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/quilt/internal/decompile/cfr/CfrObfuscationMapping.java
  buildSrc/src/main/java/quilt/internal/decompile/javadoc/ClassJavadocProvider.java
  buildSrc/src/main/java/quilt/internal/decompile/javadoc/FieldJavadocProvider.java
  buildSrc/src/main/java/quilt/internal/decompile/javadoc/MethodJavadocProvider.java
  buildSrc/src/main/java/quilt/internal/decompile/quiltflower/QuiltflowerJavadocProvider.java
  buildSrc/src/main/java/quilt/internal/decompile/quiltflower/QuiltflowerResultSaver.java
  buildSrc/src/main/java/quilt/internal/tasks/build/InvertPerVersionMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/TransformJarClassesTask.java
  buildSrc/src/main/java/quilt/internal/util/MappingsJavadocProvider.java
  settings.gradle
  src/doclet/java/quilt/internal/taglet/MappingTaglet.java
  src/doclet/resources/copy_on_click.js
  src/doclet/resources/javadoc_header.txt
  src/doclet/resources/style.css
Labels: bug, enhancement, toolchain, snapshot, reviews needed

#75 Speed up gradle tasks by using caching
  .github/workflows/build.yml
  build.gradle
  buildSrc/src/main/java/quilt/internal/MappingsPlugin.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractTinyMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AddProposedFieldMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/BuildMappingsTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/CheckMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/CompressTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/InvertPerVersionMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyV2Task.java
  buildSrc/src/main/java/quilt/internal/tasks/build/TinyJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/jarmapping/MapNamedJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/jarmapping/MapPerVersionMappingsJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/mappings/EnigmaMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadMinecraftLibrariesTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadVersionsManifestTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadWantedVersionManifestTask.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/MergeJarsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/UnpickJarTask.java
  src/doclet/resources/style.css
Labels: enhancement, refactor, toolchain, snapshot, discussion, reviews needed

#82 22w06a tag stuff
  mappings/net/minecraft/data/server/AbstractTagProvider.mapping
  mappings/net/minecraft/tag/BlockTags.mapping
  mappings/net/minecraft/tag/EntityTypeTags.mapping
  mappings/net/minecraft/tag/FluidTags.mapping
  mappings/net/minecraft/tag/GameEventTags.mapping
  mappings/net/minecraft/tag/Tag.mapping
  mappings/net/minecraft/tag/TagGroupLoader.mapping
  mappings/net/minecraft/tag/TagKey.mapping
  mappings/net/minecraft/tag/TagManagerLoader.mapping
  mappings/net/minecraft/util/Holder.mapping
  mappings/net/minecraft/util/HolderSet.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: new, snapshot, ready to merge

#85 Fix some issues with the update-base workflow
  .github/actions/update-base/dist/index.js
  .github/actions/update-base/index.js
  .github/workflows/update-base.yml
Labels: bug, toolchain, ready to merge

#83 22w06a stuff
  mappings/net/minecraft/block/EntityShapeContext.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/PeriodicNotificationManager.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/datafixer/fix/FlattenStructureSettingsFix.mapping
  mappings/net/minecraft/entity/ai/goal/ClimbOnTopOfPowderSnowGoal.mapping
  mappings/net/minecraft/entity/ai/goal/Goal.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/loot/entry/TagEntry.mapping
  mappings/net/minecraft/resource/AutoCloseableResourceManager.mapping
  mappings/net/minecraft/resource/HolderSetCodec.mapping
  mappings/net/minecraft/resource/MultiPackResourceManager.mapping
  mappings/net/minecraft/server/ServerReloadableResources.mapping
  mappings/net/minecraft/server/WorldStem.mapping
  mappings/net/minecraft/structure/ConcentricRingsStructurePlacement.mapping
  mappings/net/minecraft/structure/RandomSpreadStructurePlacement.mapping
  mappings/net/minecraft/structure/RandomSpreadType.mapping
  mappings/net/minecraft/structure/StructurePlacement.mapping
  mappings/net/minecraft/structure/StructurePlacementType.mapping
  mappings/net/minecraft/tag/TagNetworkSerialization.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryCodecs.mapping
  mappings/net/minecraft/util/registry/RegistryFixedCodec.mapping
  mappings/net/minecraft/util/registry/RegistryLoader.mapping
  mappings/net/minecraft/util/registry/RegistryOps.mapping
  mappings/net/minecraft/util/thread/ThreadExecutor.mapping
  mappings/net/minecraft/world/gen/chunk/StructuresConfig.mapping
Labels: new, snapshot, ready to merge

#89 Misc mappings
  mappings/net/minecraft/test/StructureTestUtil.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/test/TestServer.mapping
  mappings/net/minecraft/test/TestUtil.mapping
  mappings/net/minecraft/test/TimedTaskRunner.mapping
  mappings/net/minecraft/util/thread/LockHelper.mapping
  mappings/net/minecraft/util/thread/TaskExecutor.mapping
  mappings/net/minecraft/util/thread/TaskQueue.mapping
  mappings/net/minecraft/util/thread/ThreadExecutor.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/village/VillageGossipType.mapping
  mappings/net/minecraft/village/VillagerData.mapping
  mappings/net/minecraft/village/VillagerGossips.mapping
  mappings/net/minecraft/village/raid/Raid.mapping
Labels: new, snapshot, ready to merge

#88 Entity AI mappings
  mappings/net/minecraft/entity/ai/brain/Brain.mapping
  mappings/net/minecraft/entity/ai/brain/Schedule.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/AxolotlAttackablesSensor.mapping
  mappings/net/minecraft/entity/ai/brain/task/FindEntityTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/FindPointOfInterestTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/FollowMobTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/GiveGiftsToHeroTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/LeapingChargeTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/LongJumpTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/SeekWaterTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/TemptTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/VillagerTaskListProvider.mapping
  mappings/net/minecraft/entity/ai/brain/task/WalkTask.mapping
  mappings/net/minecraft/entity/ai/control/LookControl.mapping
  mappings/net/minecraft/entity/ai/control/MoveControl.mapping
  mappings/net/minecraft/entity/ai/goal/EscapeDangerGoal.mapping
  mappings/net/minecraft/entity/ai/goal/FollowOwnerGoal.mapping
  mappings/net/minecraft/entity/ai/goal/FollowParentGoal.mapping
  mappings/net/minecraft/entity/ai/goal/GoToVillageGoal.mapping
  mappings/net/minecraft/entity/ai/goal/Goal.mapping
  mappings/net/minecraft/entity/ai/goal/GoalSelector.mapping
  mappings/net/minecraft/entity/ai/goal/LookAtEntityGoal.mapping
  mappings/net/minecraft/entity/ai/goal/MoveToRaidCenterGoal.mapping
  mappings/net/minecraft/entity/ai/goal/TargetGoal.mapping
  mappings/net/minecraft/entity/ai/pathing/BirdNavigation.mapping
  mappings/net/minecraft/entity/ai/pathing/LandPathNodeMaker.mapping
  mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeNavigator.mapping
  mappings/net/minecraft/entity/ai/pathing/WaterPathNodeMaker.mapping
  mappings/net/minecraft/entity/player/HungerConstants.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: new, snapshot, ready to merge

#86 Fix a name in ServerReloadableResources, and map some minor stuff.
  mappings/net/minecraft/resource/MultiPackResourceManager.mapping
  mappings/net/minecraft/resource/ProfiledResourceReload.mapping
  mappings/net/minecraft/server/ServerReloadableResources.mapping
  mappings/net/minecraft/server/function/FunctionLoader.mapping
Labels: documentation, refactor, new, snapshot, ready to merge

#94 Fix broken parameter names in RootSystemFeature
  buildSrc/gradle.properties
  gradle.properties
  mappings/net/minecraft/world/gen/feature/RootSystemFeature.mapping
Labels: bug, snapshot, reviews needed

#68 Miscellaneous mappings, mostly world gen
  mappings/net/minecraft/client/particle/BlockMarkerParticle.mapping
  mappings/net/minecraft/data/info/WorldGenRegistryDumpReport.mapping
  mappings/net/minecraft/datafixer/fix/BedBlockEntityFix.mapping
  mappings/net/minecraft/entity/ai/brain/VisibleLivingEntitiesCache.mapping
  mappings/net/minecraft/structure/PostPlacementProcessor.mapping
  mappings/net/minecraft/structure/StructurePiecesCollector.mapping
  mappings/net/minecraft/structure/StructurePiecesGenerator.mapping
  mappings/net/minecraft/structure/StructurePiecesGeneratorFactory.mapping
  mappings/net/minecraft/structure/StructurePiecesList.mapping
  mappings/net/minecraft/structure/piece/StructurePiece.mapping
  mappings/net/minecraft/structure/piece/StructurePiecesHolder.mapping
  mappings/net/minecraft/util/WinNativeModuleLister.mapping
  mappings/net/minecraft/util/math/BlockBox.mapping
  mappings/net/minecraft/util/math/Quantiles.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrListener.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrStatsResultSerializer.mapping
  mappings/net/minecraft/util/profiling/jfr/ProfiledDuration.mapping
  mappings/net/minecraft/util/profiling/jfr/data/ChunkGenerationData.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/TimedStat.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/TimedStatsSummary.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ProtoChunk.mapping
  mappings/net/minecraft/world/chunk/SingularPalette.mapping
  mappings/net/minecraft/world/chunk/palette/Palette.mapping
  mappings/net/minecraft/world/chunk/palette/SingleValuePalette.mapping
  mappings/net/minecraft/world/gen/BelowZeroRetrogen.mapping
  mappings/net/minecraft/world/gen/blockpredicate/BlockPredicate.mapping
  mappings/net/minecraft/world/gen/blockpredicate/HasSturdyFaceBlockPredicate.mapping
  mappings/net/minecraft/world/gen/blockpredicate/MatchingBlockTagBlockPredicate.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/PlacedFeature.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/StructureSpawnOverride.mapping
  mappings/net/minecraft/world/gen/feature/WeightedPlacedFeature.mapping
  mappings/net/minecraft/world/gen/feature/util/FeatureDebugLogger.mapping
  mappings/net/minecraft/world/gen/heightprovider/WeightedListHeightProvider.mapping
  mappings/net/minecraft/world/tick/EmptyTickSchedulers.mapping
Labels: new, port, snapshot, ready to merge

#97 Map some TagKey-related stuff, add documentation.
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/tag/TagKey.mapping
  mappings/net/minecraft/util/Holder.mapping
Labels: refactor, new, snapshot, ready to merge, javadoc

#90 22w07a + 1.18.2-pre1 + pre2 + pre3 stuff
  mappings/net/minecraft/client/gui/screen/Realms32bitWarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/WarningScreen.mapping
  mappings/net/minecraft/client/gui/widget/PlainTextButtonWidget.mapping
  mappings/net/minecraft/command/argument/ResourceKeyArgument.mapping
  mappings/net/minecraft/command/argument/ResourceOrTagIdentifierArgument.mapping
  mappings/net/minecraft/data/server/AbstractTagProvider.mapping
  mappings/net/minecraft/datafixer/fix/OverreachingTickFix.mapping
  mappings/net/minecraft/datafixer/fix/StructuresBecomeConfiguredFix.mapping
  mappings/net/minecraft/server/world/ChunkTaskPrioritySystem.mapping
  mappings/net/minecraft/tag/BiomeTags.mapping
  mappings/net/minecraft/tag/BiomeTagsProvider.mapping
  mappings/net/minecraft/tag/ConfiguredStructureTags.mapping
  mappings/net/minecraft/tag/ConfiguredStructureTagsProvider.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/noise/DoublePerlinNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/OctavePerlinNoiseSampler.mapping
  mappings/net/minecraft/world/biome/source/util/VanillaTerrainParameters.mapping
  mappings/net/minecraft/world/gen/DensityFunction.mapping
  mappings/net/minecraft/world/gen/DensityFunctions.mapping
  mappings/net/minecraft/world/gen/OreVeinCreator.mapping
  mappings/net/minecraft/world/gen/chunk/Blender.mapping
  mappings/net/minecraft/world/gen/chunk/SlideConfig.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeatures.mapping
  mappings/net/minecraft/world/gen/noise/BuiltinNoiseParameters.mapping
  mappings/net/minecraft/world/gen/noise/NoiseParametersKeys.mapping
  mappings/net/minecraft/world/gen/noise/NoiseRouter.mapping
  mappings/net/minecraft/world/gen/noise/NoiseRouterData.mapping
  mappings/net/minecraft/world/gen/noise/Noises.mapping
  mappings/net/minecraft/world/gen/structure/BuiltInStructureSets.mapping
  mappings/net/minecraft/world/gen/structure/BuiltInStructures.mapping
  mappings/net/minecraft/world/gen/structure/StructureSet.mapping
  mappings/net/minecraft/world/gen/structure/StructureSets.mapping
Labels: new, snapshot, ready to merge
