Repository QuiltMC/quilt-mappings, pull requests merged in 2022-11, with the labels that each got.

#269 Map several registry-related classes.
  mappings/net/minecraft/data/server/tag/AbstractTagProvider.mapping
  mappings/net/minecraft/data/server/tag/BlockTagsProvider.mapping
  mappings/net/minecraft/data/server/tag/TagsProvider.mapping
  mappings/net/minecraft/data/server/tag/UpdateOneTwentyBlockTagsProvider.mapping
  mappings/net/minecraft/entity/passive/CatType.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorLists.mapping
  mappings/net/minecraft/util/HolderLookup.mapping
  mappings/net/minecraft/util/dynamic/RegistryElementCodec.mapping
  mappings/net/minecraft/util/registry/Holder.mapping
  mappings/net/minecraft/util/registry/HolderLookup.mapping
  mappings/net/minecraft/util/registry/HolderOwner.mapping
  mappings/net/minecraft/util/registry/HolderProvider.mapping
  mappings/net/minecraft/util/registry/HolderSet.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryOps.mapping
  mappings/net/minecraft/util/registry/RegistrySetBuilder.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  mappings/net/minecraft/util/registry/VanillaDynamicRegistries.mapping
  mappings/net/minecraft/world/gen/carver/ConfiguredCarvers.mapping
Labels: t: refactor, t: new, v: snapshot, final-comment-period, s: small

#273 Fix typo in package
  mappings/net/minecraft/client/multiplayer/report/ReportEnvironment.mapping
Labels: v: snapshot, s: small, critical

#246 Upstream GitHub actions and other libraries.
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/update-base.yml
  build.gradle
  buildSrc/build.gradle
  buildSrc/gradle.properties
  buildSrc/settings.gradle
  buildSrc/src/main/java/quilt/internal/tasks/MappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MappingsV2JarTask.java
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: toolchain, v: snapshot, final-comment-period, s: small

#272 Registry Mappings
  mappings/net/minecraft/util/registry/BuiltInRegistries.mapping
  mappings/net/minecraft/util/registry/DefaultMappedRegistry.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/util/registry/HolderLookup.mapping
  mappings/net/minecraft/util/registry/HolderSet.mapping
  mappings/net/minecraft/util/registry/MutableRegistry.mapping
  mappings/net/minecraft/util/registry/Registries.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryCodecs.mapping
  mappings/net/minecraft/util/registry/RegistryKey.mapping
  mappings/net/minecraft/util/registry/RegistryLoader.mapping
  mappings/net/minecraft/util/registry/RegistryOps.mapping
  mappings/net/minecraft/util/registry/RegistrySetBuilder.mapping
  mappings/net/minecraft/util/registry/ResourceFileNamespace.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  mappings/net/minecraft/world/biome/source/BiomeSources.mapping
  mappings/net/minecraft/world/gen/BootstrapContext.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#258 Models and Sprite
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/option/OptionsScreen.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/render/ShaderProgram.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModels.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/ModelBaker.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/client/render/model/UnbakedModel.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/render/model/json/ModelVariantMap.mapping
  mappings/net/minecraft/client/resource/metadata/FrameSize.mapping
  mappings/net/minecraft/client/texture/MipmapHelper.mapping
  mappings/net/minecraft/client/texture/MissingSprite.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/texture/SpriteTicker.mapping
  mappings/net/minecraft/client/texture/TextureStitcher.mapping
  mappings/net/minecraft/client/util/ModelIdentifier.mapping
  mappings/net/minecraft/client/util/SpriteIdentifier.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryManager.mapping
  mappings/net/minecraft/command/EntitySelectorReader.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/resource/pack/metadata/ResourceFilterMetadata.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  simple_type_field_names.json5
Labels: t: new, v: snapshot, final-comment-period, s: medium

#274 map TrunkPlacer
  mappings/net/minecraft/world/gen/trunk/TrunkPlacer.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#275 a lot of new block mappings
  mappings/net/minecraft/block/BambooBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/FungusBlock.mapping
  mappings/net/minecraft/block/LandingBlock.mapping
  mappings/net/minecraft/block/LightBlock.mapping
  mappings/net/minecraft/block/MushroomPlantBlock.mapping
  mappings/net/minecraft/block/NoteBlock.mapping
  mappings/net/minecraft/block/NyliumBlock.mapping
  mappings/net/minecraft/block/SkullBlock.mapping
  mappings/net/minecraft/block/SpawnerBlock.mapping
  mappings/net/minecraft/block/enums/Instrument.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/entity/damage/ProjectileDamageSource.mapping
  mappings/net/minecraft/world/explosion/Explosion.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#283 GenerationSettings mappings
  mappings/net/minecraft/world/biome/GenerationSettings.mapping
Labels: t: new, v: snapshot, s: small, critical

#278 lots of new miscellaneous mappings
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/unmapped/C_jibygqpu.mapping
  mappings/net/minecraft/world/BlockCollisions.mapping
  mappings/net/minecraft/world/ChunkPosDistanceLevelPropagator.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/chunk/ReadableContainer.mapping
  mappings/net/minecraft/world/chunk/palette/PalettedContainer.mapping
  mappings/net/minecraft/world/gen/RandomState.mapping
  mappings/net/minecraft/world/gen/blockpredicate/BlockPredicate.mapping
  mappings/net/minecraft/world/gen/blockpredicate/MatchingBlockTagBlockPredicate.mapping
  mappings/net/minecraft/world/gen/blockpredicate/MatchingBlocksBlockPredicate.mapping
  mappings/net/minecraft/world/gen/blockpredicate/MatchingFluidsBlockPredicate.mapping
  mappings/net/minecraft/world/gen/carver/Carver.mapping
  mappings/net/minecraft/world/gen/carver/CarverConfig.mapping
  mappings/net/minecraft/world/gen/carver/CarverContext.mapping
  mappings/net/minecraft/world/gen/carver/CaveCarver.mapping
  mappings/net/minecraft/world/gen/carver/CaveCarverConfig.mapping
  mappings/net/minecraft/world/gen/carver/ConfiguredCarver.mapping
  mappings/net/minecraft/world/gen/carver/ConfiguredCarvers.mapping
  mappings/net/minecraft/world/gen/carver/RavineCarver.mapping
  mappings/net/minecraft/world/gen/carver/RavineCarverConfig.mapping
  mappings/net/minecraft/world/gen/chunk/AquiferSampler.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#280 move UnsizedItemStackSet to net.minecraft.item, fixes #277
  mappings/net/minecraft/item/UnsizedItemStackSet.mapping
  mappings/net/minecraft/unmapped/UnsizedItemStackSet.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#281 remove all usages of "level" to refer to a world
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeBuffetWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeFlatWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/DeathScreen.mapping
  mappings/net/minecraft/client/gui/screen/WorldLoadingScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/WorldSavePath.mapping
  mappings/net/minecraft/world/ChunkPosDistanceLevelPropagator.mapping
  mappings/net/minecraft/world/ChunkRegion.mapping
  mappings/net/minecraft/world/GameMode.mapping
  mappings/net/minecraft/world/ImmutableWorldSaveProperties.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/ServerWorldProperties.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/WorldInfo.mapping
  mappings/net/minecraft/world/WorldSaveProperties.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkTickTracker.mapping
  mappings/net/minecraft/world/storage/SaveVersionInfo.mapping
  mappings/net/minecraft/world/storage/SessionLock.mapping
  mappings/net/minecraft/world/storage/WorldSaveStorage.mapping
  mappings/net/minecraft/world/storage/WorldSaveSummary.mapping
  mappings/net/minecraft/world/storage/WorldStorageException.mapping
Labels: t: refactor, v: snapshot, discussion, final-comment-period, s: small

#282 telemetry mappings
  mappings/net/minecraft/client/util/telemetry/TelemetryManager.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryProperty.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryPropertyMap.mapping
  mappings/net/minecraft/client/util/telemetry/WorldTelemetryManager.mapping
  mappings/net/minecraft/client/util/telemetry/event/PerformanceMetricSamplerEvent.mapping
  mappings/net/minecraft/client/util/telemetry/event/SamplerTelemetryEvent.mapping
  mappings/net/minecraft/client/util/telemetry/event/SendableTelemetryEvent.mapping
  mappings/net/minecraft/client/util/telemetry/event/TelemetryEventInstance.mapping
  mappings/net/minecraft/client/util/telemetry/event/TelemetryEventSender.mapping
  mappings/net/minecraft/client/util/telemetry/event/TelemetryEventType.mapping
  mappings/net/minecraft/client/util/telemetry/event/WorldLoadEvent.mapping
  mappings/net/minecraft/client/util/telemetry/event/WorldLoadTimesEvent.mapping
  mappings/net/minecraft/client/util/telemetry/event/WorldUnloadEvent.mapping
  mappings/net/minecraft/client/util/telemetry/logging/JsonTelemetryEventLog.mapping
  mappings/net/minecraft/client/util/telemetry/logging/JsonTelemetryEventLogReader.mapping
  mappings/net/minecraft/client/util/telemetry/logging/TelemetryEventLog.mapping
  mappings/net/minecraft/client/util/telemetry/logging/TelemetryEventLogDirectory.mapping
  mappings/net/minecraft/client/util/telemetry/logging/TelemetryEventLogger.mapping
  mappings/net/minecraft/client/util/telemetry/logging/TelemetryLogManager.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#284 map VariantProvider and clean up variant <-> type distinction
  mappings/net/minecraft/client/render/entity/BoatEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/VariantProvider.mapping
  mappings/net/minecraft/entity/passive/AxolotlEntity.mapping
  mappings/net/minecraft/entity/passive/CatVariant.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/FrogEntity.mapping
  mappings/net/minecraft/entity/passive/FrogVariant.mapping
  mappings/net/minecraft/entity/passive/HorseEntity.mapping
  mappings/net/minecraft/entity/passive/LlamaEntity.mapping
  mappings/net/minecraft/entity/passive/MooshroomEntity.mapping
  mappings/net/minecraft/entity/passive/ParrotEntity.mapping
  mappings/net/minecraft/entity/passive/RabbitEntity.mapping
  mappings/net/minecraft/entity/passive/TropicalFishEntity.mapping
  mappings/net/minecraft/entity/vehicle/BoatEntity.mapping
  mappings/net/minecraft/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/registry/Registries.mapping
Labels: t: refactor, t: new, v: snapshot, final-comment-period, s: small

#285 improve world-related mappings
  mappings/net/minecraft/util/function/AbortableIterationConsumer.mapping
  mappings/net/minecraft/world/ChainedNeighborUpdater.mapping
  mappings/net/minecraft/world/GameRules.mapping
  mappings/net/minecraft/world/HeightLimitView.mapping
  mappings/net/minecraft/world/Heightmap.mapping
  mappings/net/minecraft/world/NeighborUpdater.mapping
  mappings/net/minecraft/world/SimpleNeighborUpdater.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/BuiltinBiomes.mapping
  mappings/net/minecraft/world/biome/OverworldBiomeCreator.mapping
  mappings/net/minecraft/world/biome/TheEndBiomeCreator.mapping
  mappings/net/minecraft/world/biome/TheNetherBiomeCreator.mapping
  mappings/net/minecraft/world/border/WorldBorder.mapping
  mappings/net/minecraft/world/chunk/light/LightingProvider.mapping
  mappings/net/minecraft/world/chunk/light/LightingView.mapping
  mappings/net/minecraft/world/entity/EntityIndex.mapping
  mappings/net/minecraft/world/entity/EntityLookup.mapping
  mappings/net/minecraft/world/gen/BelowZeroRetrogen.mapping
  mappings/net/minecraft/world/gen/treedecorator/AlterGroundTreeDecorator.mapping
  mappings/net/minecraft/world/gen/treedecorator/LeavesVineTreeDecorator.mapping
  mappings/net/minecraft/world/tick/OrderedTick.mapping
  mappings/net/minecraft/world/tick/ProtoChunkTicks.mapping
  mappings/net/minecraft/world/tick/Tick.mapping
  mappings/net/minecraft/world/tick/WorldGenTickScheduler.mapping
  mappings/net/minecraft/world/tick/WorldTickScheduler.mapping
  mappings/net/minecraft/world/timer/Timer.mapping
  mappings/net/minecraft/world/timer/TimerCallbackSerializer.mapping
  mappings/net/minecraft/world/updater/WorldUpdater.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#286 fix toInitialChunkDataNbt() mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
Labels: t: refactor, v: snapshot, discussion, final-comment-period, s: small

#288 Bunch of mappings and docs.
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/Drawable.mapping
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/tooltip/Tooltip.mapping
  mappings/net/minecraft/client/gui/widget/ButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/CenteredTextWidget.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/ScrollableWidget.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/PiglinHeadEntityModel.mapping
  mappings/net/minecraft/client/render/entity/CamelEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
  mappings/net/minecraft/client/render/entity/model/FrogEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/PiglinEntityModel.mapping
  mappings/net/minecraft/resource/AutoCloseableResourceManager.mapping
  mappings/net/minecraft/resource/MultiPackResourceManager.mapping
  mappings/net/minecraft/resource/NamespaceResourceManager.mapping
  mappings/net/minecraft/resource/ReloadableResourceManager.mapping
  mappings/net/minecraft/resource/Resource.mapping
  mappings/net/minecraft/resource/ResourceIoSupplier.mapping
  mappings/net/minecraft/resource/ResourceManager.mapping
  mappings/net/minecraft/resource/ResourceMetadata.mapping
  mappings/net/minecraft/resource/ResourceReload.mapping
  mappings/net/minecraft/resource/ResourceType.mapping
  mappings/net/minecraft/resource/SinglePreparationResourceReloader.mapping
  mappings/net/minecraft/resource/pack/DataPackSettings.mapping
  mappings/net/minecraft/resource/pack/DefaultResourcePack.mapping
  mappings/net/minecraft/resource/pack/ResourcePack.mapping
  mappings/net/minecraft/resource/pack/ResourcePackManager.mapping
  mappings/net/minecraft/util/FileNameUtil.mapping
  mappings/net/minecraft/util/IdentifierPattern.mapping
  mappings/net/minecraft/util/ProgressListener.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/math/Axis.mapping
Labels: documentation, t: new, v: snapshot, final-comment-period, s: medium
