Repository QuiltMC/quilt-mappings, pull requests merged in 2022-12, with the labels that each got.

#289 Updates dependencies
  buildSrc/src/main/java/quilt/internal/tasks/unpick/UnpickJarTask.java
  gradle/libs.versions.toml
  unpick-definitions/rabbit_types.unpick
  unpick-logging.properties
Labels: toolchain, v: snapshot, final-comment-period, s: small

#290 restore my reverted prs
  mappings/net/minecraft/client/gui/screen/CustomizeBuffetWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeFlatWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/WorldLoadingScreen.mapping
  mappings/net/minecraft/client/util/telemetry/event/PerformanceMetricSamplerEvent.mapping
  mappings/net/minecraft/client/util/telemetry/event/SamplerTelemetryEvent.mapping
  mappings/net/minecraft/client/util/telemetry/event/TelemetryEventSender.mapping
  mappings/net/minecraft/client/util/telemetry/event/WorldLoadEvent.mapping
  mappings/net/minecraft/client/util/telemetry/event/WorldLoadTimesEvent.mapping
  mappings/net/minecraft/client/util/telemetry/event/WorldUnloadEvent.mapping
  mappings/net/minecraft/item/UnsizedItemStackSet.mapping
  mappings/net/minecraft/world/GameMode.mapping
  mappings/net/minecraft/world/ImmutableWorldSaveProperties.mapping
  mappings/net/minecraft/world/SimpleNeighborUpdater.mapping
  mappings/net/minecraft/world/WorldInfo.mapping
  mappings/net/minecraft/world/storage/SaveVersionInfo.mapping
  mappings/net/minecraft/world/storage/SessionLock.mapping
  mappings/net/minecraft/world/storage/WorldSaveStorage.mapping
  mappings/net/minecraft/world/storage/WorldSaveStorageException.mapping
  mappings/net/minecraft/world/storage/WorldSaveSummary.mapping
Labels: t: refactor, v: snapshot, reviews needed, s: small

#295 Update to Gradle 7.6, use Java 19 instead of 18 on CI
  .github/workflows/build.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: toolchain, final-comment-period, s: small

#292 some miscellaneous new mappings
  mappings/net/minecraft/data/server/advancement/AdvancementTabGenerator.mapping
  mappings/net/minecraft/data/server/advancement/AdventureAdvancementTabGenerator.mapping
  mappings/net/minecraft/data/server/advancement/EndAdvancementTabGenerator.mapping
  mappings/net/minecraft/data/server/advancement/HusbandryAdvancementTabGenerator.mapping
  mappings/net/minecraft/data/server/advancement/NetherAdvancementTabGenerator.mapping
  mappings/net/minecraft/data/server/advancement/StoryAdvancementTabGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/EntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/LootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/VanillaEntityLootTableGenerator.mapping
  mappings/net/minecraft/datafixer/fix/EntityGoatMissingStateFix.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityTypePredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityVariantPredicate.mapping
  mappings/net/minecraft/predicate/entity/TypeSpecificPredicate.mapping
  mappings/net/minecraft/util/collection/IdListUtil.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#297 Check named classes aren't in the default unmapped package
  buildSrc/src/main/java/quilt/internal/tasks/lint/EntryNamingChecker.java
Labels: enhancement, toolchain, v: snapshot, final-comment-period, s: small

#300 rename registry classes for 1.19.3
  mappings/net/minecraft/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/registry/Registries.mapping
  mappings/net/minecraft/registry/RegistryKeys.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: small

#296 Map Atlas code, much happier this time around
  mappings/com/mojang/blaze3d/texture/TextureUtil.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/particle/SpriteProvider.mapping
  mappings/net/minecraft/client/render/model/SpriteAtlasManager.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasHolder.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasManager.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/texture/SpriteContents.mapping
  mappings/net/minecraft/client/texture/SpriteLoader.mapping
  mappings/net/minecraft/client/texture/TextureStitcherCannotFitException.mapping
  mappings/net/minecraft/client/texture/atlas/SpriteResourceLoader.mapping
  mappings/net/minecraft/client/texture/atlas/SpriteSource.mapping
  mappings/net/minecraft/client/texture/atlas/SpriteSourceType.mapping
  mappings/net/minecraft/client/texture/atlas/SpriteSources.mapping
  mappings/net/minecraft/client/texture/atlas/source/DirectorySpriteSource.mapping
  mappings/net/minecraft/client/texture/atlas/source/FilterSpriteSource.mapping
  mappings/net/minecraft/client/texture/atlas/source/SingleSpriteSource.mapping
  mappings/net/minecraft/client/texture/atlas/source/UnstitchSpriteSource.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#299 rename setShader to draw, fixes #238
  mappings/com/mojang/blaze3d/vertex/VertexBuffer.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: small

#254 Recipe mappings
  mappings/net/minecraft/data/server/ExperimentalRecipesProvider.mapping
  mappings/net/minecraft/data/server/RecipesProvider.mapping
  mappings/net/minecraft/data/server/VanillaRecipesProvider.mapping
  mappings/net/minecraft/data/server/recipe/CookingRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/CraftingRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/RecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/ShapedRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/ShapelessRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/SingleItemRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/SmithingRecipeJsonFactory.mapping
  mappings/net/minecraft/recipe/AbstractCookingRecipe.mapping
  mappings/net/minecraft/recipe/CookingCategory.mapping
  mappings/net/minecraft/recipe/CraftingCategory.mapping
  mappings/net/minecraft/recipe/CraftingRecipe.mapping
  mappings/net/minecraft/recipe/RecipeCategory.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
  mappings/net/minecraft/recipe/ShapelessRecipe.mapping
  mappings/net/minecraft/recipe/SpecialCraftingRecipe.mapping
Labels: t: refactor, t: new, v: release, final-comment-period, s: small

#303 ItemGroup mappings
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/item/ItemStack.mapping
Labels: t: new, v: release, final-comment-period, s: small

#314 fix missing netty javadoc
  build.gradle
  gradle.properties
Labels: bug, toolchain, v: release, final-comment-period

#308 Restore font and Blaze3D mappings
  mappings/com/mojang/blaze3d/lighting/DiffuseLighting.mapping
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/com/mojang/blaze3d/shader/Uniform.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/com/mojang/blaze3d/vertex/VertexConsumer.mapping
  mappings/net/minecraft/client/font/GlyphRenderer.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/client/font/UnicodeTextureFont.mapping
  mappings/net/minecraft/client/gl/PostProcessShader.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/render/Frustum.mapping
  mappings/net/minecraft/client/render/LightmapTextureManager.mapping
  mappings/net/minecraft/client/render/model/ModelBaker.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/recipe/SpecialRecipeSerializer.mapping
  mappings/net/minecraft/util/StringIdentifiable.mapping
Labels: t: new, v: release, final-comment-period, s: medium

#307 Command argument mappings (and cooking categories)
  mappings/net/minecraft/command/CommandBuildContext.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryEntryArgumentType.mapping
  mappings/net/minecraft/command/argument/SignedArgumentType.mapping
  mappings/net/minecraft/network/message/SignedChatMessage.mapping
  mappings/net/minecraft/recipe/book/CookingRecipeCategory.mapping
  mappings/net/minecraft/unmapped/C_zzdolisx.mapping
Labels: t: new, v: release, final-comment-period, s: small

#306 miscellaneous mappings, mostly dfu coverage
  mappings/net/minecraft/datafixer/fix/AdvancementCriteriaRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/BlendingDataRemoveFromNetherEndFix.mapping
  mappings/net/minecraft/datafixer/fix/BookFilteredTextRemovalFix.mapping
  mappings/net/minecraft/datafixer/fix/BritishShorthairCatVariantRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityPaintingFieldsRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/GoatHornIdFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemNbtFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemRemoveBlockEntityTagFix.mapping
  mappings/net/minecraft/datafixer/fix/OptionsAmbientOcclusionFix.mapping
  mappings/net/minecraft/datafixer/fix/OptionsProgrammerArtFix.mapping
  mappings/net/minecraft/datafixer/fix/PointOfInterestFix.mapping
  mappings/net/minecraft/datafixer/fix/PointOfInterestRemovalFix.mapping
  mappings/net/minecraft/datafixer/fix/SignFilteredTextRemovalFix.mapping
  mappings/net/minecraft/datafixer/schema/IdentifierNormalizingSchema.mapping
  mappings/net/minecraft/datafixer/schema/Schema100.mapping
  mappings/net/minecraft/datafixer/schema/Schema102.mapping
  mappings/net/minecraft/datafixer/schema/Schema1022.mapping
  mappings/net/minecraft/datafixer/schema/Schema106.mapping
  mappings/net/minecraft/datafixer/schema/Schema107.mapping
  mappings/net/minecraft/datafixer/schema/Schema1125.mapping
  mappings/net/minecraft/datafixer/schema/Schema135.mapping
  mappings/net/minecraft/datafixer/schema/Schema3202.mapping
  mappings/net/minecraft/datafixer/schema/Schema3203.mapping
  mappings/net/minecraft/datafixer/schema/Schema3204.mapping
  mappings/net/minecraft/item/map/MapState.mapping
Labels: t: refactor, t: new, v: release, final-comment-period, s: small

#315 Add buildscript tests
  buildSrc/build.gradle
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractTinyMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AddProposedMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/BuildMappingsTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/InvertPerVersionMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeIntermediaryTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyV2Task.java
  buildSrc/src/main/java/quilt/internal/tasks/build/RemoveIntermediaryTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/CombineUnpickDefinitionsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/RemapUnpickDefinitionsTask.java
  buildSrc/src/main/java/quilt/internal/util/JarRemapper.java
  buildSrc/src/test/java/quilt/internal/TasksTest.java
  buildSrc/src/test/java/quilt/internal/TestUtil.java
  buildSrc/src/test/java/quilt/internal/input/AClass.java
  buildSrc/src/test/java/quilt/internal/input/BEnum.java
  buildSrc/src/test/java/quilt/internal/input/CClass.java
  buildSrc/src/test/java/quilt/internal/input/DRecord.java
  buildSrc/src/test/java/quilt/internal/input/EClass.java
  buildSrc/src/test/java/quilt/internal/input/FEnum.java
  buildSrc/src/test/java/quilt/internal/input/GClass.java
  buildSrc/src/test/java/quilt/internal/input/HInterface.java
  buildSrc/src/test/java/quilt/internal/mappingio/CompleteInitializersVisitorTest.java
  buildSrc/src/test/java/quilt/internal/util/UnpickFile.java
  buildSrc/src/test/resources/completeInitializers.tiny
  buildSrc/src/test/resources/proguard-test.conf
  buildSrc/src/test/resources/test-intermediate-alt.tiny
  buildSrc/src/test/resources/test-intermediate.tiny
  buildSrc/src/test/resources/testProject/enigma_profile.json
  buildSrc/src/test/resources/testProject/mappings/com/example/AClass.mapping
  buildSrc/src/test/resources/testProject/mappings/com/example/BEnum.mapping
  buildSrc/src/test/resources/testProject/mappings/com/example/EClass.mapping
  buildSrc/src/test/resources/testProject/mappings/com/example/FEnum.mapping
  buildSrc/src/test/resources/testProject/mappings/com/example/GClass.mapping
  buildSrc/src/test/resources/testProject/unpick-definitions/e_class_flags.unpick
  buildSrc/src/test/resources/testProject/unpick-definitions/f_enum_flags.unpick
  buildSrc/src/test/resources/testProject/unpick-definitions/g_class_constants.unpick
  gradle/libs.versions.toml
Labels: enhancement, toolchain, v: release, final-comment-period, s: large

#320 disable "inconsistent inner class entries" warning in quiltflower
  buildSrc/src/main/java/quilt/internal/decompile/quiltflower/QuiltflowerDecompiler.java
Labels: enhancement, toolchain, v: release, final-comment-period

#298 Rename `ThreadedAnvilChunkStorage`
  CONVENTIONS.md
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ThreadedChunkManager.mapping
Labels: t: refactor, v: release, discussion, final-comment-period, s: small

#325 update javadoc draftsman to 1.2.2 -- fix "inconsistent generic signature" warnings
  buildSrc/src/main/java/quilt/internal/decompile/quiltflower/QuiltflowerDecompiler.java
  gradle/libs.versions.toml
Labels: bug, toolchain, v: release, final-comment-period, s: small

#328 Fix a wrong method reference in BlockEntity
  mappings/net/minecraft/block/entity/BlockEntity.mapping
Labels: bug, v: release, final-comment-period, s: small
