Repository QuiltMC/quilt-mappings, pull requests merged in 2022-05, with the labels that each got.

#160 Switch inaccurate BuiltInStructureSets to MojMap's StructureSetKeys
  mappings/net/minecraft/world/gen/structure/StructureSetKeys.mapping
Labels: t: refactor, release, final-comment-period, small

#167 Fix Merged Mappings
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractTinyMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyV2Task.java
Labels: bug, toolchain, snapshot, final-comment-period, small

#176 Restore nbt element
  mappings/net/minecraft/block/entity/SculkSensorBlockEntity.mapping
  mappings/net/minecraft/command/argument/NbtPathArgumentType.mapping
  mappings/net/minecraft/loot/function/CopyNbtLootFunction.mapping
  mappings/net/minecraft/nbt/AbstractNbtList.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/nbt/NbtElement.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/nbt/NbtList.mapping
  mappings/net/minecraft/nbt/scanner/NbtCollector.mapping
  mappings/net/minecraft/nbt/visitor/NbtOrderedStringFormatter.mapping
  mappings/net/minecraft/nbt/visitor/NbtTextFormatter.mapping
  mappings/net/minecraft/predicate/NbtPredicate.mapping
  mappings/net/minecraft/structure/piece/PoolStructurePiece.mapping
  mappings/net/minecraft/structure/piece/RuinedPortalStructurePiece.mapping
  mappings/net/minecraft/structure/piece/StructurePiece.mapping
  unpick-definitions/nbt_type_ids.unpick
Labels: t: new, t: port, snapshot, final-comment-period, small, critical

#177 Add sonic boom particle mapping
  mappings/net/minecraft/client/particle/ExplosionLargeParticle.mapping
  mappings/net/minecraft/client/particle/SonicBoomParticle.mapping
Labels: t: new, snapshot, final-comment-period, small

#179 rendering
  mappings/com/mojang/blaze3d/vertex/BufferBuilder.mapping
  mappings/com/mojang/blaze3d/vertex/BufferRenderer.mapping
  mappings/com/mojang/blaze3d/vertex/VertexBuffer.mapping
Labels: t: new, snapshot, final-comment-period, small

#180 searching
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/search/IdentifierSearch.mapping
  mappings/net/minecraft/client/search/IdentifierSearchTree.mapping
  mappings/net/minecraft/client/search/IntersectionIterator.mapping
  mappings/net/minecraft/client/search/MergingUniqueIterator.mapping
  mappings/net/minecraft/client/search/PlainTextSearch.mapping
  mappings/net/minecraft/client/search/PlainTextSearchTree.mapping
  mappings/net/minecraft/client/search/RefreshingSearchable.mapping
  mappings/net/minecraft/client/search/Searchable.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: t: new, snapshot, final-comment-period, small

#181 registry and tags
  mappings/net/minecraft/data/server/tag/BannerPatternTagProvider.mapping
  mappings/net/minecraft/data/server/tag/InstrumentTagProvider.mapping
  mappings/net/minecraft/data/server/tag/PoiTagProvider.mapping
  mappings/net/minecraft/item/BannerPatterns.mapping
  mappings/net/minecraft/item/Instrument.mapping
  mappings/net/minecraft/item/Instruments.mapping
  mappings/net/minecraft/tag/BannerPatternTags.mapping
  mappings/net/minecraft/tag/InstrumentTags.mapping
  mappings/net/minecraft/tag/PoiTags.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/world/poi/PointOfInterestTypes.mapping
Labels: t: new, snapshot, final-comment-period, small

#170 Rename `Screen#onClose` to `#closeScreen`
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookScreen.mapping
Labels: bug, t: refactor, snapshot, final-comment-period, small

#172 Rename `NarratorOptionsScreen` to `SimpleOptionsScreen`
  mappings/net/minecraft/client/gui/screen/option/SimpleOptionsScreen.mapping
Labels: bug, t: refactor, snapshot, final-comment-period, small

#173 Rename `BedBlock#isFree` to `#wakeVillager`
  mappings/net/minecraft/block/BedBlock.mapping
Labels: bug, t: refactor, snapshot, final-comment-period, small

#174 Rename `BookScreen#getTextAt` to `#getTextStyleAt`
  mappings/net/minecraft/client/gui/screen/ingame/BookScreen.mapping
Labels: bug, t: refactor, snapshot, final-comment-period, small

#175 Rename `EntityView#intersectsEntities` to `#doesNotIntersectEntities`
  mappings/net/minecraft/world/EntityView.mapping
Labels: bug, t: refactor, snapshot, final-comment-period, small

#182 Implement Quilt Enigma Plugin instead of Stitch
  build.gradle
  buildSrc/build.gradle
  buildSrc/gradle.properties
  buildSrc/src/main/java/quilt/internal/tasks/build/AddProposedFieldMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AddProposedMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyV2Task.java
  buildSrc/src/main/java/quilt/internal/tasks/setup/DownloadMinecraftLibrariesTask.java
  enigma_profile.json
  gradle.properties
Labels: enhancement, t: refactor, toolchain, snapshot, final-comment-period, small, medium

#178 items and blocks
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/FrogSpawnBlock.mapping
  mappings/net/minecraft/block/MangrovePropaguleBlock.mapping
  mappings/net/minecraft/block/Material.mapping
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/block/SculkSensorBlock.mapping
  mappings/net/minecraft/block/TripwireHookBlock.mapping
  mappings/net/minecraft/block/dispenser/BoatDispenserBehavior.mapping
  mappings/net/minecraft/block/entity/BannerPattern.mapping
  mappings/net/minecraft/block/sapling/MangroveSaplingGenerator.mapping
  mappings/net/minecraft/block/sapling/SaplingGenerator.mapping
  mappings/net/minecraft/enchantment/SwiftSneakEnchantment.mapping
  mappings/net/minecraft/item/ArmorStandItem.mapping
  mappings/net/minecraft/item/BannerPatternItem.mapping
  mappings/net/minecraft/item/BlockPredicatesChecker.mapping
  mappings/net/minecraft/item/CompassItem.mapping
  mappings/net/minecraft/item/CrossbowItem.mapping
  mappings/net/minecraft/item/DiskFragmentItem.mapping
  mappings/net/minecraft/item/InstrumentItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/MiningToolItem.mapping
  mappings/net/minecraft/item/map/MapState.mapping
Labels: t: new, snapshot, final-comment-period, small

#183 Map oxidization level getter
  mappings/net/minecraft/block/OxidizableBlock.mapping
  mappings/net/minecraft/block/OxidizableSlabBlock.mapping
  mappings/net/minecraft/block/OxidizableStairsBlock.mapping
Labels: t: new, snapshot, final-comment-period, small

#184 Port #167 (merged mappings fix) to 1.18.2
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractTinyMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyV2Task.java
Labels: bug, t: port, toolchain, release, final-comment-period, small

#185 Network encryption mappings
  build.gradle
  mappings/net/minecraft/block/OxidizableBlock.mapping
  mappings/net/minecraft/block/OxidizableSlabBlock.mapping
  mappings/net/minecraft/block/OxidizableStairsBlock.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
  mappings/net/minecraft/network/encryption/PlayerPublicKey.mapping
  mappings/net/minecraft/network/encryption/SignatureUpdater.mapping
  mappings/net/minecraft/network/encryption/SignatureValidator.mapping
  mappings/net/minecraft/network/encryption/Signer.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerListS2CPacket.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/MeCommand.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/util/UuidUtil.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: t: new, snapshot, final-comment-period, medium

#191 Map a bunch of resource/tag stuff and some extra.
  mappings/net/minecraft/entity/passive/CatEntity.mapping
  mappings/net/minecraft/entity/passive/CatType.mapping
  mappings/net/minecraft/entity/passive/CatTypes.mapping
  mappings/net/minecraft/predicate/entity/EntityVariantPredicate.mapping
  mappings/net/minecraft/predicate/entity/LightningBoltPredicate.mapping
  mappings/net/minecraft/predicate/entity/SlimePredicate.mapping
  mappings/net/minecraft/resource/NamespaceResourceManager.mapping
  mappings/net/minecraft/resource/Resource.mapping
  mappings/net/minecraft/resource/ResourceFactory.mapping
  mappings/net/minecraft/resource/ResourceMetadata.mapping
  mappings/net/minecraft/tag/TagBuilder.mapping
  mappings/net/minecraft/tag/TagEntry.mapping
  mappings/net/minecraft/tag/TagFile.mapping
  mappings/net/minecraft/tag/TagGroupLoader.mapping
  mappings/net/minecraft/tag/TagManagerLoader.mapping
  mappings/net/minecraft/unmapped/C_bmhptpfz.mapping
  mappings/net/minecraft/unmapped/C_ljtxhtrw.mapping
Labels: t: refactor, t: new, snapshot, critical

#192 Swap lure and LOTS levels
  mappings/net/minecraft/entity/projectile/FishingBobberEntity.mapping
Labels: bug, snapshot, final-comment-period, small

#189 Document NetworkEncryptionUtils
  mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
Labels: documentation, t: port, snapshot, final-comment-period, small

#188 Chat and some other network-related mappings
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/world/GeneratorType.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/play/ChatCommandC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/RequestChatPreviewC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/AcknowledgeBlockChangeS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatMessageS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatPreviewS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatPreviewStateChangedS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ServerMetadataS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/SystemMessageS2CPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/ServerMetadata.mapping
  mappings/net/minecraft/server/Services.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/util/UserCache.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/profiler/Recorder.mapping
  mappings/net/minecraft/world/GameRules.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/chunk/ChunkManager.mapping
  mappings/net/minecraft/world/dimension/DimensionOptions.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
Labels: t: new, snapshot, final-comment-period, medium

#187 Map /place command
  buildSrc/gradle.properties
  gradle.properties
  mappings/net/minecraft/command/argument/ResourceKeyArgument.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/CommandOutput.mapping
  mappings/net/minecraft/server/command/PlaceComand.mapping
  mappings/net/minecraft/structure/StructureTemplateManager.mapping
  mappings/net/minecraft/util/Holder.mapping
Labels: t: new, snapshot, final-comment-period, small
