Repository QuiltMC/quilt-mappings, pull requests merged in 2022-08, with the labels that each got.

#212 Map EnumArgumentType
  mappings/net/minecraft/command/argument/EnumArgumentType.mapping
Labels: t: new, release, final-comment-period, small

#214 Add more automatic names
  simple_type_field_names.json5
Labels: toolchain, final-comment-period, small

#215 Update BrewingRecipeRegistry.mapping
  mappings/net/minecraft/recipe/BrewingRecipeRegistry.mapping
Labels: bug, t: refactor, small, critical

#217 Random fixes, map back some lost stuff.
  mappings/net/minecraft/client/gui/ChatPreview.mapping
  mappings/net/minecraft/client/gui/ChatReportCategory.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
Labels: t: refactor, t: new, v: release, final-comment-period, s: small

#219 Refactor getPosition() -> getModel() and add docs to MatrixStack.
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
Labels: documentation, t: refactor, v: release, javadoc, final-comment-period, s: small

#221 Rework Javadoc styling entirely to be Quilt-themed.
  src/doclet/resources/style.css
Labels: meta, javadoc, final-comment-period, s: small

#228 Add min/max mappings in `IntProperty`
  mappings/net/minecraft/state/property/IntProperty.mapping
Labels: t: new, v: release, final-comment-period, s: small

#223 Update a few stack/slot related method names and parameters.
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
Labels: t: refactor, v: release, final-comment-period, s: small

#225 Fix inverted loot pool entry classes.
  mappings/net/minecraft/loot/entry/GroupEntry.mapping
  mappings/net/minecraft/loot/entry/LootPoolEntryTypes.mapping
  mappings/net/minecraft/loot/entry/SequenceEntry.mapping
Labels: bug, t: refactor, v: release, final-comment-period, s: small

#220 Chat report stuff.
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/MultilineTextField.mapping
  mappings/net/minecraft/client/gui/screen/GenericWaitingScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/ChatReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/widget/EditBoxWidget.mapping
  mappings/net/minecraft/client/gui/widget/ScrollableWidget.mapping
  mappings/net/minecraft/client/input/CursorMovement.mapping
  mappings/net/minecraft/client/multiplayer/chat/ChatLog.mapping
  mappings/net/minecraft/client/multiplayer/chat/ChatLogImpl.mapping
  mappings/net/minecraft/client/multiplayer/chat/LoggedChatEvent.mapping
  mappings/net/minecraft/client/multiplayer/chat/LoggedChatMessage.mapping
  mappings/net/minecraft/client/multiplayer/chat/LoggedChatMessageLink.mapping
  mappings/net/minecraft/client/multiplayer/report/AbuseReportSender.mapping
  mappings/net/minecraft/client/multiplayer/report/chat/ChatReportBuilder.mapping
  mappings/net/minecraft/client/multiplayer/report/chat/ChatReportingContext.mapping
  mappings/net/minecraft/client/mutliplayer/report/ReportEnvironment.mapping
  mappings/net/minecraft/network/chat/SignedMessageHeader.mapping
  mappings/net/minecraft/unmapped/C_zzdolisx.mapping
  mappings/net/minecraft/util/Formatting.mapping
  mappings/net/minecraft/util/TextifiedException.mapping
Labels: t: new, v: release, final-comment-period, s: medium

#226 Add bunch of resource-loading and server-related mappings.
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldScreenProvider.mapping
  mappings/net/minecraft/client/resource/ClientBuiltinResourcePackProvider.mapping
  mappings/net/minecraft/client/world/WorldCreationContext.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/ServerReloadableResources.mapping
  mappings/net/minecraft/server/WorldLoader.mapping
  mappings/net/minecraft/server/WorldStem.mapping
  mappings/net/minecraft/server/integrated/IntegratedServer.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
  mappings/net/minecraft/test/TestServer.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  simple_type_field_names.json5
Labels: documentation, enhancement, t: new, v: release, javadoc, final-comment-period, s: medium

#234 Improve ServerWorld mappings
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/entity/EntityHandler.mapping
Labels: t: new, v: release, final-comment-period, s: small
