Repository QuiltMC/quilt-mappings, pull requests merged in 2022-04, with the labels that each got.

#60 PR Policy
  CONTRIBUTING.md
Labels: documentation, meta, snapshot, discussion, final-comment-period

#140 A bunch of 22w13a stuff
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/OnKilledCriterion.mapping
  mappings/net/minecraft/block/NoteBlock.mapping
  mappings/net/minecraft/client/render/entity/AllayRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/AllayEntityModel.mapping
  mappings/net/minecraft/data/server/HusbandryTabAdvancementGenerator.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/structure/processor/BlockRotStructureProcessor.mapping
  mappings/net/minecraft/world/event/EntityPositionSource.mapping
  mappings/net/minecraft/world/gen/StructureWeightSampler.mapping
  mappings/net/minecraft/world/gen/structure/TerrainAdjustment.mapping
Labels: t: new, snapshot, reviews needed

#130 Blocks and Items
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractLichenBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/EnchantingTableBlock.mapping
  mappings/net/minecraft/block/ExperienceDroppingBlock.mapping
  mappings/net/minecraft/block/FireBlock.mapping
  mappings/net/minecraft/block/FrogSpawnBlock.mapping
  mappings/net/minecraft/block/GlowLichenBlock.mapping
  mappings/net/minecraft/block/LeavesBlock.mapping
  mappings/net/minecraft/block/LichenSpreadBehavior.mapping
  mappings/net/minecraft/block/MangroveLeavesBlock.mapping
  mappings/net/minecraft/block/MangrovePropaguleBlock.mapping
  mappings/net/minecraft/block/MangroveRootsBlock.mapping
  mappings/net/minecraft/block/Material.mapping
  mappings/net/minecraft/block/MudBlock.mapping
  mappings/net/minecraft/block/SculkBlock.mapping
  mappings/net/minecraft/block/SculkCatalystBlock.mapping
  mappings/net/minecraft/block/SculkVeinBlock.mapping
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/CampfireBlockEntity.mapping
  mappings/net/minecraft/block/entity/EnchantingTableBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkCatalystBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkSensorBlockEntity.mapping
  mappings/net/minecraft/block/sculk/SculkBehavior.mapping
  mappings/net/minecraft/block/sculk/SculkVienSpreader.mapping
  mappings/net/minecraft/item/BoatItem.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/WaterPlaceableBlockItem.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/unmapped/SculkShriekerBlock.mapping
  mappings/net/minecraft/unmapped/SculkShriekerBlockEntity.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/world/event/BlockPositionSource.mapping
  mappings/net/minecraft/world/event/listener/GameEventListener.mapping
  mappings/net/minecraft/world/event/listener/SculkSensorListener.mapping
Labels: t: new, snapshot, final-comment-period

#144 New Random System
  mappings/net/minecraft/util/random/BitRandom.mapping
  mappings/net/minecraft/util/random/LegacySimpleRandom.mapping
  mappings/net/minecraft/util/random/PositionalRandomFactory.mapping
  mappings/net/minecraft/util/random/RandomGenerator.mapping
  mappings/net/minecraft/util/random/RandomSeed.mapping
  mappings/net/minecraft/util/random/SingleThreadedRandom.mapping
  mappings/net/minecraft/util/random/ThreadSafeLegacySimpleRandom.mapping
  mappings/net/minecraft/util/random/Xoroshiro128PlusPlusRandom.mapping
  mappings/net/minecraft/util/random/Xoroshiro128PlusPlusRandomImpl.mapping
  mappings/net/minecraft/world/gen/PositionalRandomFactory.mapping
  mappings/net/minecraft/world/gen/WorldGenRandom.mapping
Labels: t: refactor, t: new, snapshot, reviews needed, final-comment-period

#146 Fix javadoc generation when running locally
  build.gradle
  buildSrc/gradle.properties
  buildSrc/src/main/java/quilt/internal/tasks/build/TransformJarClassesTask.java
  buildSrc/src/main/java/quilt/internal/tasks/decompile/DecompileTask.java
  gradle.properties
Labels: bug, toolchain, snapshot, final-comment-period

#141 Allay mappings
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/brain/FlyingRandomStrollTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/FollowMobTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/GiveItemsToTargetTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/LookTargetUtil.mapping
  mappings/net/minecraft/entity/ai/brain/task/StayCloseToTargetTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/WalkToNearestVisibleWantedItemTask.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/passive/AllayBrain.mapping
  mappings/net/minecraft/entity/passive/AllayEntity.mapping
  mappings/net/minecraft/world/event/listener/DynamicGameEventListener.mapping
Labels: t: new, snapshot, final-comment-period

#153 Add missing particle mappings
  mappings/net/minecraft/client/particle/GlowParticle.mapping
  mappings/net/minecraft/client/particle/ShriekParticle.mapping
  mappings/net/minecraft/particle/ParticleTypes.mapping
  mappings/net/minecraft/particle/ShriekParticleEffect.mapping
Labels: t: new, snapshot, final-comment-period

#150 Commands and Datafixer
  mappings/net/minecraft/GameAndWorldVersion.mapping
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/datafixer/DataFixerMode.mapping
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/TypeReferences.mapping
  mappings/net/minecraft/datafixer/schema/Schema3082.mapping
  mappings/net/minecraft/datafixer/schema/Schema3083.mapping
  mappings/net/minecraft/datafixer/schema/Schema3084.mapping
  mappings/net/minecraft/datafixer/schema/Schema3086.mapping
  mappings/net/minecraft/datafixer/schema/Schema3087.mapping
  mappings/net/minecraft/server/command/WardenSpawnTrackerCommand.mapping
Labels: t: new, snapshot, reviews needed, final-comment-period

#149 Advancements
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/AdvancementManager.mapping
  mappings/net/minecraft/advancement/AdvancementPositioner.mapping
  mappings/net/minecraft/advancement/CriterionMerger.mapping
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/LocationCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PickedUpThrownItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerInteractedWithEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UseItemCriterion.mapping
Labels: t: new, snapshot, reviews needed, final-comment-period

#148 Fix issues/warnings building javadocs
  mappings/com/mojang/blaze3d/vertex/VertexBuffer.mapping
  mappings/net/minecraft/block/BedBlock.mapping
  mappings/net/minecraft/block/DyedCarpetBlock.mapping
  mappings/net/minecraft/block/InfestedBlock.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/particle/ParticleGroup.mapping
  mappings/net/minecraft/client/render/entity/model/MinecartEntityModel.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/task/PrepareRamTask.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChunkDeltaUpdateS2CPacket.mapping
  mappings/net/minecraft/obfuscate/DontObfuscate.mapping
  mappings/net/minecraft/particle/ParticleType.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/dynamic/RegistryElementCodec.mapping
  mappings/net/minecraft/util/math/WordPackedArray.mapping
  mappings/net/minecraft/util/random/RandomSeed.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/world/WorldDataVersion.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
Labels: bug, snapshot, javadoc, reviews needed, final-comment-period

#156 Rendering
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/com/mojang/blaze3d/vertex/BufferBuilder.mapping
  mappings/com/mojang/blaze3d/vertex/BufferRenderer.mapping
  mappings/com/mojang/blaze3d/vertex/VertexBuffer.mapping
  mappings/com/mojang/blaze3d/vertex/VertexFormat.mapping
Labels: t: new, snapshot, final-comment-period

#157 Frog Fixes
  mappings/net/minecraft/entity/ai/brain/task/LayFrogSpawnTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/LongJumpTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/LongJumpToPreferredBlockTask.mapping
Labels: bug, t: new, snapshot, reviews needed, final-comment-period

#159 Mostly paintings
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingEntity.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingVariant.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingVariants.mapping
  mappings/net/minecraft/tag/PaintingTags.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/world/dimension/DimensionTypes.mapping
Labels: t: new, snapshot, final-comment-period

#155 Text
  mappings/net/minecraft/client/gui/screen/ScreenTexts.mapping
  mappings/net/minecraft/text/MutableText.mapping
  mappings/net/minecraft/text/Style.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/text/Texts.mapping
  mappings/net/minecraft/text/TranslationException.mapping
  mappings/net/minecraft/text/component/KeybindComponent.mapping
  mappings/net/minecraft/text/component/KeybindTextResolver.mapping
  mappings/net/minecraft/text/component/LiteralComponent.mapping
  mappings/net/minecraft/text/component/NbtComponent.mapping
  mappings/net/minecraft/text/component/ScoreComponent.mapping
  mappings/net/minecraft/text/component/SelectorComponent.mapping
  mappings/net/minecraft/text/component/TextComponent.mapping
  mappings/net/minecraft/text/component/TranslatableComponent.mapping
  mappings/net/minecraft/text/component/TranslationException.mapping
  mappings/net/minecraft/text/data/BlockEntityData.mapping
  mappings/net/minecraft/text/data/EntityData.mapping
  mappings/net/minecraft/text/data/StorageData.mapping
  mappings/net/minecraft/text/data/TextData.mapping
Labels: t: new, snapshot, final-comment-period
