Repository QuiltMC/quilt-mappings, pull requests merged in 2022-06, with the labels that each got.

#194 Client option mappings
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/Option.mapping
  mappings/net/minecraft/text/ScreenTexts.mapping
  mappings/net/minecraft/text/component/TranslatableComponent.mapping
  mappings/net/minecraft/util/OptionEnum.mapping
Labels: t: refactor, t: new, snapshot, final-comment-period, medium

#195 Advancement loot mappings
  buildSrc/gradle.properties
  gradle.properties
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/AdvancementProgress.mapping
  mappings/net/minecraft/advancement/AdvancementRewards.mapping
  mappings/net/minecraft/advancement/criterion/TravelCriterion.mapping
  mappings/net/minecraft/loot/LootPool.mapping
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/loot/condition/LootConditionConsumingBuilder.mapping
  mappings/net/minecraft/loot/context/LootContext.mapping
  mappings/net/minecraft/loot/entry/AlternativeEntry.mapping
  mappings/net/minecraft/loot/entry/EntryCombiner.mapping
  mappings/net/minecraft/loot/entry/SequenceEntry.mapping
  mappings/net/minecraft/loot/entry/TagEntry.mapping
  mappings/net/minecraft/loot/function/ApplyBonusLootFunction.mapping
  mappings/net/minecraft/loot/function/ConditionalLootFunction.mapping
  mappings/net/minecraft/loot/function/EnchantRandomlyLootFunction.mapping
  mappings/net/minecraft/loot/function/LootFunctionConsumingBuilder.mapping
  mappings/net/minecraft/loot/function/SetBannerPatternFunction.mapping
  mappings/net/minecraft/loot/function/SetInstrumentFunction.mapping
  mappings/net/minecraft/nbt/NbtList.mapping
Labels: t: new, snapshot, final-comment-period, small

#199 Fix proposed parameter names in output mappings
  buildSrc/gradle.properties
  gradle.properties
Labels: bug, toolchain, snapshot, final-comment-period, small

#202 Refactor and make boolean return wording more consistent.
  CONVENTIONS.md
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/render/entity/feature/ConditionalOverlayOwner.mapping
  mappings/net/minecraft/client/render/entity/model/ModelWithHat.mapping
  mappings/net/minecraft/client/render/model/json/ModelVariantMap.mapping
  mappings/net/minecraft/entity/passive/CatEntity.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/nbt/NbtType.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/world/HeightLimitView.mapping
  mappings/net/minecraft/world/WorldDataVersion.mapping
Labels: t: refactor, snapshot, javadoc, final-comment-period, small
