Repository QuiltMC/quilt-mappings, pull requests merged in 2022-03, with the labels that each got.

#111 Item constants
  mappings/net/minecraft/item/BoneMealItem.mapping
  mappings/net/minecraft/item/BowItem.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/CrossbowItem.mapping
  mappings/net/minecraft/item/FilledMapItem.mapping
  mappings/net/minecraft/item/FireworkRocketItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ShieldItem.mapping
  mappings/net/minecraft/item/SpyglassItem.mapping
  mappings/net/minecraft/item/TridentItem.mapping
  mappings/net/minecraft/item/WrittenBookItem.mapping
  mappings/net/minecraft/item/map/MapIcon.mapping
  mappings/net/minecraft/item/map/MapState.mapping
Labels: t: new, release, final-comment-period

#106 Screen handler constants
  mappings/net/minecraft/screen/AbstractFurnaceScreenHandler.mapping
  mappings/net/minecraft/screen/AnvilScreenHandler.mapping
  mappings/net/minecraft/screen/BeaconScreenHandler.mapping
  mappings/net/minecraft/screen/BrewingStandScreenHandler.mapping
  mappings/net/minecraft/screen/CartographyTableScreenHandler.mapping
  mappings/net/minecraft/screen/CraftingScreenHandler.mapping
  mappings/net/minecraft/screen/ForgingScreenHandler.mapping
  mappings/net/minecraft/screen/Generic3x3ContainerScreenHandler.mapping
  mappings/net/minecraft/screen/GenericContainerScreenHandler.mapping
  mappings/net/minecraft/screen/GrindstoneScreenHandler.mapping
  mappings/net/minecraft/screen/HopperScreenHandler.mapping
  mappings/net/minecraft/screen/LecternScreenHandler.mapping
  mappings/net/minecraft/screen/LoomScreenHandler.mapping
  mappings/net/minecraft/screen/MerchantScreenHandler.mapping
  mappings/net/minecraft/screen/PlayerScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/ShulkerBoxScreenHandler.mapping
  mappings/net/minecraft/screen/StonecutterScreenHandler.mapping
Labels: t: new, release, final-comment-period

#103 Map various missing stuff, and some minor fixes.
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/fluid/Fluid.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/resource/ResourceFactory.mapping
  mappings/net/minecraft/text/OrderedText.mapping
  mappings/net/minecraft/util/Holder.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
Labels: t: refactor, t: new, release, javadoc, final-comment-period

#107 Block entity constants
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/BannerBlockEntity.mapping
  mappings/net/minecraft/block/entity/BeaconBlockEntity.mapping
  mappings/net/minecraft/block/entity/BellBlockEntity.mapping
  mappings/net/minecraft/block/entity/BrewingStandBlockEntity.mapping
  mappings/net/minecraft/block/entity/CampfireBlockEntity.mapping
  mappings/net/minecraft/block/entity/ChestBlockEntity.mapping
  mappings/net/minecraft/block/entity/ConduitBlockEntity.mapping
  mappings/net/minecraft/block/entity/DispenserBlockEntity.mapping
  mappings/net/minecraft/block/entity/EndGatewayBlockEntity.mapping
  mappings/net/minecraft/block/entity/HopperBlockEntity.mapping
  mappings/net/minecraft/block/entity/LecternBlockEntity.mapping
  mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
  mappings/net/minecraft/block/entity/ShulkerBoxBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
  mappings/net/minecraft/block/entity/StructureBlockBlockEntity.mapping
Labels: t: new, release, final-comment-period

#101 Map ChunkNoiseSampler
  mappings/net/minecraft/world/gen/chunk/Blender.mapping
  mappings/net/minecraft/world/gen/chunk/BlendingData.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkNoiseSampler.mapping
Labels: t: new, release, final-comment-period

#110 Jfr profiling mappings
  mappings/net/minecraft/util/profiling/jfr/JfrProfiler.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrStatsReader.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrStatsResult.mapping
  mappings/net/minecraft/util/profiling/jfr/JvmProfiler.mapping
  mappings/net/minecraft/util/profiling/jfr/data/GarbageCollectorHeapSummary.mapping
  mappings/net/minecraft/util/profiling/jfr/event/ChunkGenerationEvent.mapping
  mappings/net/minecraft/util/profiling/jfr/event/NetworkSummaryEvent.mapping
  mappings/net/minecraft/util/profiling/jfr/event/PacketReceivedEvent.mapping
  mappings/net/minecraft/util/profiling/jfr/event/PacketSentEvent.mapping
  mappings/net/minecraft/util/profiling/jfr/event/ServerTickTimeEvent.mapping
  mappings/net/minecraft/util/profiling/jfr/event/WorldLoadFinishedEvent.mapping
  mappings/net/minecraft/util/profiling/jfr/event/network/PacketEvent.mapping
  mappings/net/minecraft/util/profiling/jfr/stats/NetworkPacketSummary.mapping
Labels: t: new, release, final-comment-period

#114 Map a bunch of AI goals
  mappings/net/minecraft/entity/ai/goal/CatSitOnBlockGoal.mapping
  mappings/net/minecraft/entity/ai/goal/ClimbOnTopOfPowderSnowGoal.mapping
  mappings/net/minecraft/entity/ai/goal/FleeEntityGoal.mapping
  mappings/net/minecraft/entity/ai/goal/FollowGroupLeaderGoal.mapping
  mappings/net/minecraft/entity/ai/goal/FollowMobGoal.mapping
  mappings/net/minecraft/entity/ai/goal/FormCaravanGoal.mapping
  mappings/net/minecraft/entity/ai/goal/GoToVillageGoal.mapping
  mappings/net/minecraft/entity/ai/goal/IronGolemWanderAroundGoal.mapping
  mappings/net/minecraft/entity/ai/goal/MoveThroughVillageGoal.mapping
Labels: t: new, release, final-comment-period

#109 `util/math/**` mappings
  mappings/net/minecraft/util/math/AffineTransformations.mapping
  mappings/net/minecraft/util/math/AxisTransformation.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/math/ChunkPos.mapping
  mappings/net/minecraft/util/math/ChunkSectionPos.mapping
  mappings/net/minecraft/util/math/ColumnPos.mapping
  mappings/net/minecraft/util/math/Matrix3f.mapping
  mappings/net/minecraft/util/math/Matrix4f.mapping
  mappings/net/minecraft/util/math/Quaternion.mapping
  mappings/net/minecraft/util/math/Spline.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
  mappings/net/minecraft/util/math/WordPackedArray.mapping
  mappings/net/minecraft/util/math/floatprovider/ClampedNormalFloatProvider.mapping
  mappings/net/minecraft/util/math/floatprovider/ConstantFloatProvider.mapping
  mappings/net/minecraft/util/math/floatprovider/FloatProvider.mapping
  mappings/net/minecraft/util/math/floatprovider/FloatProviderType.mapping
  mappings/net/minecraft/util/math/floatprovider/TrapezoidFloatProvider.mapping
  mappings/net/minecraft/util/math/floatprovider/UniformFloatProvider.mapping
  mappings/net/minecraft/util/math/noise/DoublePerlinNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/InterpolatedNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/OctavePerlinNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/PerlinNoiseSampler.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseSamplingConfig.mapping
Labels: t: new, release, final-comment-period

#112 Util & Codecs mappings
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/collection/DefaultedList.mapping
  mappings/net/minecraft/util/collection/IdList.mapping
  mappings/net/minecraft/util/collection/Int2ObjectBiMap.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: t: new, release, final-comment-period

#102 fixes to piston related mappings
  mappings/net/minecraft/block/PistonBlock.mapping
  mappings/net/minecraft/block/PistonExtensionBlock.mapping
  mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
  mappings/net/minecraft/block/piston/PistonHandler.mapping
Labels: t: refactor, release, final-comment-period

#117 Map some net.minecraft.data stuff
  mappings/net/minecraft/data/DataCache.mapping
  mappings/net/minecraft/data/Main.mapping
  mappings/net/minecraft/data/SnbtProvider.mapping
  mappings/net/minecraft/data/client/BlockStateDefinitionProvider.mapping
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/model/BlockStateVariant.mapping
  mappings/net/minecraft/data/client/model/Model.mapping
  mappings/net/minecraft/data/client/model/MultipartBlockStateSupplier.mapping
  mappings/net/minecraft/data/client/model/PropertiesMap.mapping
  mappings/net/minecraft/data/client/model/SimpleModelSupplier.mapping
  mappings/net/minecraft/data/client/model/TexturedModel.mapping
  mappings/net/minecraft/data/client/model/VariantSettings.mapping
  mappings/net/minecraft/data/client/model/VariantsBlockStateSupplier.mapping
  mappings/net/minecraft/data/client/model/When.mapping
  mappings/net/minecraft/data/info/WorldGenRegistryDumpReport.mapping
  mappings/net/minecraft/data/report/RegistryDumpProvider.mapping
  mappings/net/minecraft/data/server/BarterLootTableGenerator.mapping
  mappings/net/minecraft/data/server/ChestLootTableGenerator.mapping
  mappings/net/minecraft/data/server/EndTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/EntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/FishingLootTableGenerator.mapping
  mappings/net/minecraft/data/server/GiftLootTableGenerator.mapping
  mappings/net/minecraft/data/server/HusbandryTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/ItemTagsProvider.mapping
  mappings/net/minecraft/data/server/NetherTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/RecipesProvider.mapping
  mappings/net/minecraft/data/server/StoryTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/recipe/ShapedRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/ShapelessRecipeJsonFactory.mapping
  mappings/net/minecraft/state/property/Property.mapping
Labels: t: new, release, final-comment-period

#116 Map a bunch of stuff in net.minecraft.server
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/server/LanServerPinger.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/ServerConfigHandler.mapping
  mappings/net/minecraft/server/ServerConfigList.mapping
  mappings/net/minecraft/server/ServerMetadata.mapping
  mappings/net/minecraft/server/ServerNetworkIo.mapping
  mappings/net/minecraft/server/ServerReloadableResources.mapping
  mappings/net/minecraft/server/ServerTask.mapping
  mappings/net/minecraft/server/WorldStem.mapping
  mappings/net/minecraft/server/command/AdvancementCommand.mapping
  mappings/net/minecraft/server/command/AttributeCommand.mapping
  mappings/net/minecraft/server/command/dev/ResetChunksCommand.mapping
  mappings/net/minecraft/server/commands/PlaceFeatureCommand.mapping
  mappings/net/minecraft/server/dedicated/AbstractPropertiesHandler.mapping
  mappings/net/minecraft/server/dedicated/DedicatedPlayerManager.mapping
  mappings/net/minecraft/server/dedicated/DedicatedServerWatchdog.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/dedicated/ServerMBean.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesLoader.mapping
  mappings/net/minecraft/server/dedicated/gui/DedicatedServerGui.mapping
  mappings/net/minecraft/server/dedicated/gui/PlayerStatsGui.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/integrated/IntegratedPlayerManager.mapping
  mappings/net/minecraft/server/integrated/IntegratedServer.mapping
  mappings/net/minecraft/server/network/DebugInfoSender.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
  mappings/net/minecraft/server/rcon/QueryResponseHandler.mapping
  mappings/net/minecraft/server/rcon/RconClient.mapping
  mappings/net/minecraft/server/rcon/RconListener.mapping
  mappings/net/minecraft/server/world/BlockEvent.mapping
Labels: t: new, release, final-comment-period

#123 Datafixer mappings
  mappings/net/minecraft/datafixer/fix/AddFlagIfNotPresentFix.mapping
  mappings/net/minecraft/datafixer/fix/AddTrappedChestFix.mapping
  mappings/net/minecraft/datafixer/fix/ChoiceTypesFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkHeightAndBiomeFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkLevelTagRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkLightRemoveFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkPalettedStorageFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkToProtoChunkFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityBlockStateFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityRedundantChanceTagsFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityTheRenameningBlock.mapping
  mappings/net/minecraft/datafixer/fix/EntityUuidFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityZombieVillagerTypeFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemPotionFix.mapping
  mappings/net/minecraft/datafixer/fix/LeavesFix.mapping
  mappings/net/minecraft/datafixer/fix/MissingDimensionFix.mapping
  mappings/net/minecraft/datafixer/fix/OptionsKeyLwjgl3Fix.mapping
  mappings/net/minecraft/datafixer/fix/PersistentStateUuidFix.mapping
  mappings/net/minecraft/datafixer/fix/ProtoChunkTickListFix.mapping
  mappings/net/minecraft/datafixer/fix/StructureSeparationDataFix.mapping
  mappings/net/minecraft/datafixer/fix/UntaggedSpawnerFix.mapping
  mappings/net/minecraft/datafixer/fix/VillagerFollowRangeFix.mapping
  mappings/net/minecraft/datafixer/fix/VillagerXpRebuildFix.mapping
  mappings/net/minecraft/datafixer/fix/WorldGenSettingsHeightAndBiomeFix.mapping
  mappings/net/minecraft/datafixer/fix/WorldUuidFix.mapping
  mappings/net/minecraft/datafixer/schema/IdentifierNormalizingSchema.mapping
  mappings/net/minecraft/datafixer/schema/Schema1451v6.mapping
  mappings/net/minecraft/datafixer/schema/Schema1460.mapping
  mappings/net/minecraft/datafixer/schema/Schema1470.mapping
  mappings/net/minecraft/datafixer/schema/Schema1801.mapping
  mappings/net/minecraft/datafixer/schema/Schema1904.mapping
  mappings/net/minecraft/datafixer/schema/Schema1906.mapping
  mappings/net/minecraft/datafixer/schema/Schema1920.mapping
  mappings/net/minecraft/datafixer/schema/Schema1931.mapping
  mappings/net/minecraft/datafixer/schema/Schema704.mapping
  mappings/net/minecraft/datafixer/schema/Schema705.mapping
  mappings/net/minecraft/datafixer/schema/Schema99.mapping
Labels: t: new, release, final-comment-period

#131 Fixes
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/gui/screen/option/VideoOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/option/DoubleOption.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/Option.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/command/argument/BlockArgumentParser.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommandTreeS2CPacket.mapping
  mappings/net/minecraft/resource/JsonDataLoader.mapping
  mappings/net/minecraft/resource/MultiPackResourceManager.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/ServerReloadableResources.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/function/FunctionLoader.mapping
  mappings/net/minecraft/structure/piece/PoolStructurePiece.mapping
  mappings/net/minecraft/structure/piece/RuinedPortalStructurePiece.mapping
  mappings/net/minecraft/tag/TagGroupLoader.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfoCcxthici.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfoDlimablg.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfoTfyklnov.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfoWqygiwsi.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfoYqdhsdjl.mapping
  mappings/net/minecraft/util/registry/RegistryResourceAccess.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/source/TheEndBiomeSource.mapping
  mappings/net/minecraft/world/gen/StructureChecker.mapping
  mappings/net/minecraft/world/gen/chunk/BlendingData.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkNoiseSampler.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceBuilder.mapping
Labels: bug, snapshot

#124 `net/minecraft/client` mappings
  buildSrc/gradle.properties
  enigma_profile.json
  gradle.properties
  mappings/net/minecraft/client/ClientBrandRetriever.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/font/BlankGlyph.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/FontStorage.mapping
  mappings/net/minecraft/client/font/GlyphAtlasTexture.mapping
  mappings/net/minecraft/client/font/MultilineText.mapping
  mappings/net/minecraft/client/font/TextHandler.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/client/font/TextVisitFactory.mapping
  mappings/net/minecraft/client/font/UnicodeTextureFont.mapping
  mappings/net/minecraft/client/font/WhiteRectangleGlyph.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeBuffetLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/narration/ScreenNarrator.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/network/AbstractClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/SocialInteractionsManager.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/realms/gui/screen/Realms32bitWarningScreen.mapping
  mappings/net/minecraft/client/texture/AbstractTexture.mapping
  mappings/net/minecraft/client/toast/RecipeToast.mapping
  mappings/net/minecraft/client/toast/SystemToast.mapping
  mappings/net/minecraft/client/toast/ToastManager.mapping
  mappings/net/minecraft/client/toast/TutorialToast.mapping
  mappings/net/minecraft/client/util/WindowProvider.mapping
  mappings/net/minecraft/client/world/BiomeColorCache.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/client/world/GeneratorType.mapping
Labels: t: new, release, final-comment-period

#126 n/m/world/chunk mappings
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkCache.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/ChunkToNibbleArrayMap.mapping
  mappings/net/minecraft/world/chunk/EmptyChunk.mapping
  mappings/net/minecraft/world/chunk/ReadOnlyChunk.mapping
  mappings/net/minecraft/world/chunk/UpgradeData.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/chunk/light/ChunkLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/LevelPropagator.mapping
  mappings/net/minecraft/world/chunk/light/LightStorage.mapping
  mappings/net/minecraft/world/chunk/light/LightingProvider.mapping
  mappings/net/minecraft/world/chunk/light/LightingView.mapping
  mappings/net/minecraft/world/chunk/light/SkyLightStorage.mapping
  mappings/net/minecraft/world/chunk/palette/BiMapPalette.mapping
  mappings/net/minecraft/world/chunk/palette/PalettedContainer.mapping
Labels: t: new, release, final-comment-period

#128 Add particle mappings for the 22w11a snapshot
  mappings/net/minecraft/client/particle/SculkChargeParticle.mapping
  mappings/net/minecraft/client/particle/SculkChargePopParticle.mapping
  mappings/net/minecraft/client/particle/SoulParticle.mapping
  mappings/net/minecraft/particle/SculkChargeParticleEffect.mapping
Labels: t: new, snapshot, final-comment-period

#125 n/m/loot mappings
  gradle.properties
  mappings/net/minecraft/command/argument/NbtPathArgumentType.mapping
  mappings/net/minecraft/loot/condition/AlternativeLootCondition.mapping
  mappings/net/minecraft/loot/condition/LootCondition.mapping
  mappings/net/minecraft/loot/condition/LootConditionManager.mapping
  mappings/net/minecraft/loot/context/LootContext.mapping
  mappings/net/minecraft/loot/entry/DynamicEntry.mapping
  mappings/net/minecraft/loot/entry/ItemEntry.mapping
  mappings/net/minecraft/loot/entry/LeafEntry.mapping
  mappings/net/minecraft/loot/entry/LootTableEntry.mapping
  mappings/net/minecraft/loot/entry/TagEntry.mapping
  mappings/net/minecraft/loot/function/ApplyBonusLootFunction.mapping
  mappings/net/minecraft/loot/function/CopyNameLootFunction.mapping
  mappings/net/minecraft/loot/function/CopyNbtLootFunction.mapping
  mappings/net/minecraft/loot/function/CopyStateFunction.mapping
  mappings/net/minecraft/loot/function/EnchantRandomlyLootFunction.mapping
  mappings/net/minecraft/loot/function/EnchantWithLevelsLootFunction.mapping
  mappings/net/minecraft/loot/function/ExplorationMapLootFunction.mapping
  mappings/net/minecraft/loot/function/LimitCountLootFunction.mapping
  mappings/net/minecraft/loot/function/LootFunctionManager.mapping
  mappings/net/minecraft/loot/function/LootingEnchantLootFunction.mapping
  mappings/net/minecraft/loot/function/SetAttributesLootFunction.mapping
  mappings/net/minecraft/loot/function/SetBannerPatternFunction.mapping
  mappings/net/minecraft/loot/function/SetContentsLootFunction.mapping
  mappings/net/minecraft/loot/function/SetCountLootFunction.mapping
  mappings/net/minecraft/loot/function/SetDamageLootFunction.mapping
  mappings/net/minecraft/loot/function/SetEnchantmentsLootFunction.mapping
  mappings/net/minecraft/loot/function/SetLootTableLootFunction.mapping
  mappings/net/minecraft/loot/function/SetLoreLootFunction.mapping
  mappings/net/minecraft/loot/function/SetNameLootFunction.mapping
  mappings/net/minecraft/loot/function/SetNbtLootFunction.mapping
  mappings/net/minecraft/loot/function/SetStewEffectLootFunction.mapping
  mappings/net/minecraft/loot/operator/BoundedIntUnaryOperator.mapping
  mappings/net/minecraft/loot/provider/nbt/StorageLootNbtProvider.mapping
  mappings/net/minecraft/loot/provider/number/BinomialLootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/number/ConstantLootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/number/ScoreLootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/number/UniformLootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/score/ContextLootScoreProvider.mapping
  mappings/net/minecraft/loot/provider/score/FixedLootScoreProvider.mapping
Labels: t: new, snapshot, final-comment-period

#122 net.minecraft.network stuff
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/DecoderHandler.mapping
  mappings/net/minecraft/network/LegacyQueryHandler.mapping
  mappings/net/minecraft/network/NetworkState.mapping
  mappings/net/minecraft/network/OffThreadException.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/PacketDeflater.mapping
  mappings/net/minecraft/network/PacketEncoder.mapping
  mappings/net/minecraft/network/PacketInflater.mapping
  mappings/net/minecraft/network/RateLimitedConnection.mapping
  mappings/net/minecraft/network/SizePrepender.mapping
  mappings/net/minecraft/network/SplitterHandler.mapping
  mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
  mappings/net/minecraft/network/encryption/PacketDecryptor.mapping
  mappings/net/minecraft/network/encryption/PacketEncryptor.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/play/BookUpdateC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerActionC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractBlockC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractEntityC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractItemC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateBeaconC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/AcknowledgeBlockChangeS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChunkDeltaUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommandTreeS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityEquipmentUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityStatusEffectS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ExplosionS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameJoinS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerRespawnS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/StatisticsS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/SynchronizeTagsS2CPacket.mapping
Labels: t: new, snapshot, final-comment-period

#129 Animations and Models
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/client/render/animation/Animation.mapping
  mappings/net/minecraft/client/render/animation/AnimationKeyframe.mapping
  mappings/net/minecraft/client/render/animation/Animator.mapping
  mappings/net/minecraft/client/render/animation/PartAnimation.mapping
  mappings/net/minecraft/client/render/entity/FrogEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/TadpoleEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/animation/FrogEntityAnimations.mapping
  mappings/net/minecraft/client/render/entity/model/FrogEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SinglePartEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/TadpoleEntityModel.mapping
  mappings/net/minecraft/entity/AnimationState.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: t: new, snapshot, final-comment-period

#134 Command mappings
  gradle/wrapper/gradle-wrapper.properties
  mappings/net/minecraft/command/BlockDataObject.mapping
  mappings/net/minecraft/command/CommandBuildContext.mapping
  mappings/net/minecraft/command/CommandSource.mapping
  mappings/net/minecraft/command/DataCommandStorage.mapping
  mappings/net/minecraft/command/EntityDataObject.mapping
  mappings/net/minecraft/command/EntitySelector.mapping
  mappings/net/minecraft/command/EntitySelectorOptions.mapping
  mappings/net/minecraft/command/StorageDataObject.mapping
  mappings/net/minecraft/command/TranslatableBuiltInExceptions.mapping
  mappings/net/minecraft/command/argument/ArgumentTypeInfo.mapping
  mappings/net/minecraft/command/argument/ArgumentTypeInfos.mapping
  mappings/net/minecraft/command/argument/ArgumentUtils.mapping
  mappings/net/minecraft/command/argument/BlockArgumentParser.mapping
  mappings/net/minecraft/command/argument/BlockPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/BlockStateArgumentType.mapping
  mappings/net/minecraft/command/argument/DoubleArgumentInfo.mapping
  mappings/net/minecraft/command/argument/EntityArgumentType.mapping
  mappings/net/minecraft/command/argument/FloatArgumentInfo.mapping
  mappings/net/minecraft/command/argument/IntegerTypeInfo.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStackArgument.mapping
  mappings/net/minecraft/command/argument/ItemStackArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/LongArgumentInfo.mapping
  mappings/net/minecraft/command/argument/ResourceKeyArgument.mapping
  mappings/net/minecraft/command/argument/ResourceOrTagIdentifierArgument.mapping
  mappings/net/minecraft/command/argument/ScoreHolderArgumentType.mapping
  mappings/net/minecraft/command/argument/SingletonArgumentInfo.mapping
  mappings/net/minecraft/command/argument/serialize/StringArgumentSerializer.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/util/HolderLookup.mapping
Labels: t: new, snapshot, final-comment-period

#136 Map diverse 22w11a resource stuff and fix javadocs.
  mappings/net/minecraft/resource/JsonDataLoader.mapping
  mappings/net/minecraft/resource/MultiPackResourceManager.mapping
  mappings/net/minecraft/resource/NamespaceResourceManager.mapping
  mappings/net/minecraft/resource/ResourceManager.mapping
  mappings/net/minecraft/resource/SourcedResource.mapping
  mappings/net/minecraft/resource/pack/ResourcePack.mapping
  mappings/net/minecraft/resource/pack/metadata/ResourceFilterMetadata.mapping
  src/packageDocs/java/net/minecraft/resource/package-info.java
Labels: documentation, t: new, snapshot, javadoc, reviews needed, final-comment-period

#137 22w11a & 12a datafixer mappings
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/fix/BlendingDataFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkDeleteIgnoredLightDataFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema3076.mapping
  mappings/net/minecraft/datafixer/schema/Schema3078.mapping
  mappings/net/minecraft/datafixer/schema/Schema3081.mapping
  mappings/net/minecraft/datafixer/schema/Schema3082.mapping
Labels: t: new, snapshot, final-comment-period
