Repository QuiltMC/quilt-mappings, pull requests merged in 2023-07, with the labels that each got.

#454 *nearly* polish off `net.minecraft.server`
  mappings/net/minecraft/advancement/AdvancementVisibilityEvaluator.mapping
  mappings/net/minecraft/advancement/PlayerAdvancementTracker.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/DecoratedPotBlock.mapping
  mappings/net/minecraft/block/entity/StructureBlockBlockEntity.mapping
  mappings/net/minecraft/block/enums/NoteBlockInstrument.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/network/encryption/PublicChatSession.mapping
  mappings/net/minecraft/network/encryption/SignatureValidator.mapping
  mappings/net/minecraft/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/ServerAdvancementLoader.mapping
  mappings/net/minecraft/server/ServerReloadableResources.mapping
  mappings/net/minecraft/server/Services.mapping
  mappings/net/minecraft/server/WorldLoader.mapping
  mappings/net/minecraft/server/command/DataCommand.mapping
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerQueryNetworkHandler.mapping
  mappings/net/minecraft/server/rcon/QueryResponseHandler.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ChunkLevels.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/PlayerChunkWatchingManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerEntityManager.mapping
  mappings/net/minecraft/server/world/ServerLightingProvider.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/server/world/ThreadedChunkManager.mapping
  mappings/net/minecraft/util/math/noise/DoublePerlinNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/InterpolatedNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/OctavePerlinNoiseSampler.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/chunk/ChunkLoadStatus.mapping
  mappings/net/minecraft/world/chunk/ChunkStatusChangeListener.mapping
  mappings/net/minecraft/world/entity/EntityHandler.mapping
  mappings/net/minecraft/world/gen/RandomState.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/chunk/GenerationShapeConfig.mapping
  mappings/net/minecraft/world/gen/noise/NoiseRouterData.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/VanillaSurfaceRules.mapping
Labels: t: new, v: release, final-comment-period, s: medium

#457 specify that some `Text.translatable` methods take a fallback
  mappings/net/minecraft/text/Text.mapping
Labels: t: refactor, v: release, reviews needed, final-comment-period, s: tiny

#456 yet more world stuff
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/DependencySorter.mapping
  mappings/net/minecraft/util/Symlink.mapping
  mappings/net/minecraft/util/path/AllowedSymlinkPathMatcher.mapping
  mappings/net/minecraft/util/path/InvalidSymlinkException.mapping
  mappings/net/minecraft/util/path/Symlink.mapping
  mappings/net/minecraft/util/path/SymlinkValidator.mapping
  mappings/net/minecraft/world/ChainedNeighborUpdater.mapping
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/ChunkTickTracker.mapping
  mappings/net/minecraft/world/chunk/UpgradeData.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/dimension/AreaHelper.mapping
  mappings/net/minecraft/world/entity/EntityTrackingSection.mapping
  mappings/net/minecraft/world/entity/EntityTrackingStatus.mapping
  mappings/net/minecraft/world/entity/SectionedEntityCache.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
  mappings/net/minecraft/world/storage/EntityChunkDataAccess.mapping
  mappings/net/minecraft/world/storage/RegionFile.mapping
  mappings/net/minecraft/world/storage/SectorMap.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
  mappings/net/minecraft/world/storage/WorldSaveStorage.mapping
  mappings/net/minecraft/world/tick/WorldTickScheduler.mapping
  mappings/net/minecraft/world/updater/WorldUpdater.mapping
Labels: t: new, v: release, final-comment-period, s: medium

#458 Midnight happenings
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/client/gui/screen/AbuseReportScreen.mapping
  mappings/net/minecraft/client/particle/BubblePopParticle.mapping
  mappings/net/minecraft/client/particle/CampfireSmokeParticle.mapping
  mappings/net/minecraft/client/particle/CherryLeafParticle.mapping
  mappings/net/minecraft/client/particle/CloudParticle.mapping
  mappings/net/minecraft/client/particle/EndRodParticle.mapping
  mappings/net/minecraft/client/particle/ExplosionSmokeParticle.mapping
  mappings/net/minecraft/client/particle/FishingParticle.mapping
  mappings/net/minecraft/client/particle/ItemBreakParticle.mapping
  mappings/net/minecraft/client/particle/NoteParticle.mapping
  mappings/net/minecraft/client/particle/ParticleFactory.mapping
  mappings/net/minecraft/client/particle/SquidInkParticle.mapping
  mappings/net/minecraft/client/particle/SweepAttackParticle.mapping
  mappings/net/minecraft/client/particle/TotemParticle.mapping
  mappings/net/minecraft/client/particle/VibrationParticle.mapping
  mappings/net/minecraft/client/util/ColorUtil.mapping
  mappings/net/minecraft/client/util/DefaultSkinHelper.mapping
  mappings/net/minecraft/client/util/ParticleUtil.mapping
  mappings/net/minecraft/item/SignItem.mapping
  mappings/net/minecraft/item/WallStandingBlockItem.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
  mappings/net/minecraft/util/UrlConstants.mapping
Labels: t: new, v: release, final-comment-period, s: small

#461 Added some mapping
  mappings/net/minecraft/client/gui/widget/MultilineScrollableWidget.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSubscriptionInfoScreen.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/entity/ai/brain/PrioritizedEntry.mapping
  mappings/net/minecraft/structure/Structure.mapping
  mappings/net/minecraft/structure/processor/CappedStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/StructureProcessor.mapping
  mappings/net/minecraft/unmapped/C_ctsfmifk.mapping
  mappings/net/minecraft/unmapped/C_czisrdmd.mapping
  mappings/net/minecraft/unmapped/C_smovfozc.mapping
  mappings/net/minecraft/unmapped/C_xaygoojx.mapping
  mappings/net/minecraft/unmapped/C_yfpegcpm.mapping
  mappings/net/minecraft/util/math/Direction.mapping
Labels: t: new, v: release, final-comment-period, s: small

#463 Add javadoc publishing code
  .github/workflows/publish.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: t: toolchain, v: release, final-comment-period, s: tiny
