Repository QuiltMC/quilt-mappings, pull requests merged in 2023-05, with the labels that each got.

#413 map color!
  .github/workflows/generate-diff.yml
  mappings/net/minecraft/block/MapColor.mapping
  mappings/net/minecraft/entity/Entity.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#414 spellcheck improvements
  buildSrc/src/main/java/quilt/internal/FileConstants.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/DownloadDictionaryFileTask.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/SpellingChecker.java
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/block/VineLogic.mapping
  mappings/net/minecraft/client/gui/screen/option/OptionsScreen.mapping
  mappings/net/minecraft/item/SmithingTemplateItem.mapping
  mappings/net/minecraft/registry/tag/BiomeTags.mapping
  mappings/net/minecraft/registry/tag/BlockTags.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/gen/feature/Feature.mapping
  mappings/net/minecraft/world/gen/feature/NetherConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/UndergroundConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/VegetationPlacedFeatures.mapping
Labels: t: toolchain, v: snapshot, reviews needed, final-comment-period, s: small

#408 client work: chat, screens, audio and quick play
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/QuickPlay.mapping
  mappings/net/minecraft/client/QuickPlayLogger.mapping
  mappings/net/minecraft/client/RunArgs.mapping
  mappings/net/minecraft/client/gui/LogoRenderer.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/screen/AbuseReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
  mappings/net/minecraft/client/gui/tab/Tab.mapping
  mappings/net/minecraft/client/gui/tab/TabManager.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/TabWidget.mapping
  mappings/net/minecraft/client/multiplayer/chat/LoggedChatEvent.mapping
  mappings/net/minecraft/client/multiplayer/chat/LoggedChatMessage.mapping
  mappings/net/minecraft/client/network/ClientLoginNetworkHandler.mapping
  mappings/net/minecraft/client/option/ServerList.mapping
  mappings/net/minecraft/client/sound/OggAudioStream.mapping
  mappings/net/minecraft/client/sound/PositionedSoundInstance.mapping
  mappings/net/minecraft/client/sound/SoundEngine.mapping
  mappings/net/minecraft/client/sound/SoundEntryDeserializer.mapping
  mappings/net/minecraft/client/sound/SoundListener.mapping
  mappings/net/minecraft/client/sound/SoundManager.mapping
  mappings/net/minecraft/client/sound/Source.mapping
  mappings/net/minecraft/client/texture/SpriteLoader.mapping
  mappings/net/minecraft/util/math/floatprovider/MultipliedFloatSupplier.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#409 map GuiGraphics and friends (formerly DrawableHelper)
  mappings/net/minecraft/client/gui/Drawable.mapping
  mappings/net/minecraft/client/gui/GuiGraphics.mapping
  mappings/net/minecraft/client/gui/LogoRenderer.mapping
  mappings/net/minecraft/client/gui/PlayerFaceRenderer.mapping
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/gui/hud/ChatMessageTag.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeFlatWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameModeSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractSignEditScreen.mapping
  mappings/net/minecraft/client/gui/tooltip/BundleTooltipComponent.mapping
  mappings/net/minecraft/client/gui/tooltip/DefaultTooltipPositioner.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipComponent.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipPositioner.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/EditBoxWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/PressableWidget.mapping
  mappings/net/minecraft/client/gui/widget/ScrollableWidget.mapping
  mappings/net/minecraft/client/gui/widget/TabWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/gui/tooltip/TooltipRenderHelper.mapping
  mappings/net/minecraft/util/math/Divisor.mapping
  simple_type_field_names.json5
Labels: t: new, v: snapshot, final-comment-period, s: medium

#412 map the light engine
  mappings/net/minecraft/network/packet/s2c/play/LightUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/data/LightData.mapping
  mappings/net/minecraft/util/math/ChunkSectionPos.mapping
  mappings/net/minecraft/world/ChunkLightBlockView.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/chunk/light/ChunkBlockLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/ChunkLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/ChunkSkyLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/ChunkSkyLightSources.mapping
  mappings/net/minecraft/world/chunk/light/LevelPriorityQueue.mapping
  mappings/net/minecraft/world/chunk/light/LevelPropagator.mapping
  mappings/net/minecraft/world/chunk/light/LightEventListener.mapping
  mappings/net/minecraft/world/chunk/light/LightStorage.mapping
  mappings/net/minecraft/world/chunk/light/LightingProvider.mapping
  mappings/net/minecraft/world/chunk/light/SkyLightStorage.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#417 fix a couple issues
  mappings/net/minecraft/data/server/loot_table/LootTableGenerator.mapping
  mappings/net/minecraft/world/SpawnDensityCapper.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#419 [1.19.4] Fix name collision in `DisplayEntity` with methods on `Entity`
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
Labels: bug, t: refactor, v: release, critical, s: tiny

#420 [1.20-pre1] Fix name collision in `DisplayEntity` with methods on `Entity`
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
Labels: bug, t: refactor, v: snapshot, critical, s: tiny

#422 1.20-pre1 datafixer mappings
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/TypeReferences.mapping
  mappings/net/minecraft/datafixer/fix/BeeHivePoiRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/BlockEntityRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkDeleteLightFix.mapping
  mappings/net/minecraft/datafixer/fix/DecoratedPotFieldRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityBrushableBlockFieldsRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/NamespacedTypeRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/RemapChunkStatusFix.mapping
  mappings/net/minecraft/datafixer/fix/RemoveFeatureFlagFix.mapping
  mappings/net/minecraft/datafixer/fix/StatusEffectDurationFix.mapping
  mappings/net/minecraft/datafixer/fix/UpdateSignBlockEntityNbtFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema3448.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#424 Map tag stuff and some registry stuff.
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/registry/Registries.mapping
  mappings/net/minecraft/registry/RegistryKeys.mapping
  mappings/net/minecraft/registry/tag/TagGroupLoader.mapping
  mappings/net/minecraft/registry/tag/TagNetworkSerialization.mapping
  mappings/net/minecraft/util/DependencySorter.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#423 Realms and some other client gui mappings
  mappings/net/minecraft/client/gui/CommonInputs.mapping
  mappings/net/minecraft/client/gui/widget/LinearLayoutWidget.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/dto/RealmsNotification.mapping
  mappings/net/minecraft/client/realms/dto/RealmsText.mapping
  mappings/net/minecraft/client/realms/gui/DataFetchers.mapping
  mappings/net/minecraft/client/realms/gui/RealmsDataFetcher.mapping
  mappings/net/minecraft/client/realms/gui/RealmsServerList.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/util/JsonUtils.mapping
  mappings/net/minecraft/client/realms/util/RealmsUtil.mapping
  unpick-definitions/key_codes.unpick
Labels: t: new, v: snapshot, final-comment-period, s: medium

#426 Update GitHub workflow actions
  .github/actions/diff-uploader/action.yml
  .github/actions/diff-uploader/dist/index.js
  .github/actions/diff-uploader/index.js
  .github/actions/diff-uploader/package-lock.json
  .github/actions/diff-uploader/package.json
  .github/actions/update-base/action.yml
  .github/actions/update-base/package-lock.json
  .github/actions/update-base/package.json
Labels: bug, enhancement, t: toolchain, final-comment-period, s: small

#430 succeed another mappings trawl
  mappings/net/minecraft/advancement/criterion/AbstractCriterionConditions.mapping
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/RecipeCraftedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsedEnderEyeCriterion.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/item/ModelPredicateProviderRegistry.mapping
  mappings/net/minecraft/client/particle/CherryLeafParticle.mapping
  mappings/net/minecraft/client/particle/RedDustParticle.mapping
  mappings/net/minecraft/client/particle/SuspendParticle.mapping
  mappings/net/minecraft/client/render/entity/model/BipedArmorEntityModel.mapping
  mappings/net/minecraft/client/texture/FaviconTexture.mapping
  mappings/net/minecraft/command/argument/EnumArgumentType.mapping
  mappings/net/minecraft/command/argument/HeightmapArgumentType.mapping
  mappings/net/minecraft/data/server/AdvancementsProvider.mapping
  mappings/net/minecraft/data/server/VanillaAdvancementsProvider.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/mob/SkeletonEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/inventory/CraftingInventory.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/network/packet/c2s/play/SignUpdateC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerRespawnS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/SignEditorOpenS2CPacket.mapping
  mappings/net/minecraft/particle/DustParticleEffect.mapping
  mappings/net/minecraft/predicate/NumberRange.mapping
  mappings/net/minecraft/recipe/MapExtendingRecipe.mapping
  mappings/net/minecraft/recipe/RecipeUnlocker.mapping
  mappings/net/minecraft/screen/SmithingScreenHandler.mapping
  mappings/net/minecraft/screen/StonecutterScreenHandler.mapping
  mappings/net/minecraft/server/command/ReturnCommand.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/structure/TrailRuinsGenerator.mapping
  mappings/net/minecraft/structure/VillageGenerator.mapping
  mappings/net/minecraft/text/CommonTexts.mapping
  mappings/net/minecraft/unmapped/C_bvrmpowj.mapping
  mappings/net/minecraft/unmapped/C_ektmmzcp.mapping
  mappings/net/minecraft/unmapped/C_qlsuqzcn.mapping
  mappings/net/minecraft/unmapped/C_wwetinhi.mapping
  mappings/net/minecraft/util/DyeColor.mapping
  mappings/net/minecraft/util/StringIdentifiable.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#431 Fix issues #429 and #428
  mappings/net/minecraft/block/CherrySaplingBlock.mapping
  mappings/net/minecraft/block/sapling/CherrySaplingGenerator.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipRenderHelper.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#425 loot tables and entities
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/Tameable.mapping
  mappings/net/minecraft/entity/damage/DamageSources.mapping
  mappings/net/minecraft/entity/damage/DamageTypes.mapping
  mappings/net/minecraft/entity/passive/HorseBaseEntity.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/loot/condition/AllOfLootCondition.mapping
  mappings/net/minecraft/loot/condition/AnyOfLootCondition.mapping
  mappings/net/minecraft/loot/condition/CompoundLootCondition.mapping
  mappings/net/minecraft/loot/condition/LootCondition.mapping
  mappings/net/minecraft/loot/context/LootContext.mapping
  mappings/net/minecraft/loot/context/LootContextParameterSet.mapping
  mappings/net/minecraft/world/BlockCollisions.mapping
  mappings/net/minecraft/world/CollisionView.mapping
  mappings/net/minecraft/world/dimension/AreaHelper.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#435 Map bunch of stuff, mainly entity stuff.
  mappings/net/minecraft/Bootstrap.mapping
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/criterion/AbstractCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemUsedOnLocationCriterion.mapping
  mappings/net/minecraft/datafixer/DataFixTypes.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/damage/FallLocation.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileUtil.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/inventory/CraftingInventory.mapping
  mappings/net/minecraft/inventory/RecipeInputInventory.mapping
  mappings/net/minecraft/item/BrushItem.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/unmapped/C_ektmmzcp.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/math/random/RandomSequence.mapping
  mappings/net/minecraft/util/random/RandomSeed.mapping
  mappings/net/minecraft/world/entity/EntityChangeListener.mapping
  mappings/net/minecraft/world/entity/EntityLike.mapping
Labels: t: refactor, t: new, v: snapshot, t: javadoc, final-comment-period, s: medium

#436 Redstone related refactors - 1.19.4 edition
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractPressurePlateBlock.mapping
  mappings/net/minecraft/block/ComparatorBlock.mapping
  mappings/net/minecraft/block/RedstoneDiodeBlock.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldView.mapping
Labels: t: refactor, t: port, v: release, final-comment-period, s: small
