Repository QuiltMC/quilt-mappings, pull requests merged in 2023-01, with the labels that each got.

#327 Do a random walk, come out with random mappings
  mappings/net/minecraft/block/WallPiglinSkullBlock.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmLinkScreen.mapping
  mappings/net/minecraft/client/gui/screen/TelemetryDataScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/ExperimentalFeaturesWarningScreen.mapping
  mappings/net/minecraft/client/gui/widget/container/AbstractContainerWidget.mapping
  mappings/net/minecraft/client/gui/widget/container/FrameWidget.mapping
  mappings/net/minecraft/client/gui/widget/container/GridWidget.mapping
  mappings/net/minecraft/client/gui/widget/container/LayoutSettings.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/Option.mapping
  mappings/net/minecraft/command/argument/BlockMirrorArgumentType.mapping
  mappings/net/minecraft/command/argument/BlockPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/BlockRotationArgumentType.mapping
  mappings/net/minecraft/command/argument/DimensionArgumentType.mapping
  mappings/net/minecraft/command/argument/GameModeArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStackArgumentType.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryEntryArgumentType.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/registry/HolderLookup.mapping
  mappings/net/minecraft/server/command/PublishCommand.mapping
  mappings/net/minecraft/server/command/SeedCommand.mapping
  mappings/net/minecraft/text/Texts.mapping
  mappings/net/minecraft/unmapped/C_ybgoyqmh.mapping
  mappings/net/minecraft/util/BlockMirror.mapping
  mappings/net/minecraft/util/BlockRotation.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: t: refactor, t: new, v: release, final-comment-period, s: medium

#332 Fix an inconsistent mojmap method name
  mappings/net/minecraft/entity/Entity.mapping
Labels: bug, v: release, reviews needed, s: small

#333 update enigma to 1.4.0
  gradle/libs.versions.toml
Labels: enhancement, toolchain, v: release, final-comment-period, s: small

#335 Fix #334
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
Labels: t: new, v: release, final-comment-period, s: small, critical

#338 New 23w03a mappings
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/GameAndWorldVersion.mapping
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/WorldVersion.mapping
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/client/InputType.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/gui/ElementPath.mapping
  mappings/net/minecraft/client/gui/LogoRenderer.mapping
  mappings/net/minecraft/client/gui/ParentElement.mapping
  mappings/net/minecraft/client/gui/screen/NavigationAxis.mapping
  mappings/net/minecraft/client/gui/screen/NavigationDirection.mapping
  mappings/net/minecraft/client/gui/screen/ScreenArea.mapping
  mappings/net/minecraft/client/gui/screen/ScreenPosition.mapping
  mappings/net/minecraft/client/gui/widget/AccessibilityOnboardingTextWidget.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/ElementListWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/MultilineTextWidget.mapping
  mappings/net/minecraft/client/gui/widget/SliderWidget.mapping
  mappings/net/minecraft/client/gui/widget/Widget.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsDownloadLatestWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsUploadScreen.mapping
  mappings/net/minecraft/network/BundlePacket.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#337 Use `build/mappings` for task outputs, instead of `.gradle/temp`
  build.gradle
  buildSrc/src/main/java/quilt/internal/FileConstants.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractTinyMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AddProposedMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/BuildMappingsTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/RemoveIntermediaryTask.java
  buildSrc/src/test/java/quilt/internal/TasksTest.java
Labels: enhancement, toolchain, v: snapshot, final-comment-period, s: small

#339 [23w03a] Complete all commands build context arguments (like execute command)
  mappings/net/minecraft/server/command/AttributeCommand.mapping
  mappings/net/minecraft/server/command/ClearCommand.mapping
  mappings/net/minecraft/server/command/CloneCommand.mapping
  mappings/net/minecraft/server/command/EffectCommand.mapping
  mappings/net/minecraft/server/command/EnchantCommand.mapping
  mappings/net/minecraft/server/command/FillCommand.mapping
  mappings/net/minecraft/server/command/GiveCommand.mapping
  mappings/net/minecraft/server/command/ItemCommand.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
  mappings/net/minecraft/server/command/LootCommand.mapping
  mappings/net/minecraft/server/command/ParticleCommand.mapping
  mappings/net/minecraft/server/command/SetBlockCommand.mapping
  mappings/net/minecraft/server/command/SummonCommand.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#342 Mappings for method in PathNodeMaker and method in AllayEntity for 1.19.3.
  mappings/net/minecraft/entity/ai/pathing/PathNodeMaker.mapping
  mappings/net/minecraft/entity/passive/AllayEntity.mapping
  mappings/net/minecraft/unmapped/C_mdnathub.mapping
Labels: t: new, v: release, final-comment-period, s: tiny

#343 update enigma to 1.5.0
  gradle/libs.versions.toml
Labels: t: toolchain, v: snapshot, final-comment-period, s: tiny

#323 Block loot table generators
  mappings/net/minecraft/data/server/loot_table/BlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/LootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/OneTwentyBlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/VanillaBlockLootTableGenerator.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#331 Add diff to artifacts
  .github/actions/diff-uploader/.gitignore
  .github/actions/diff-uploader/action.yml
  .github/actions/diff-uploader/dist/index.js
  .github/actions/diff-uploader/index.js
  .github/actions/diff-uploader/package-lock.json
  .github/actions/diff-uploader/package.json
  .github/workflows/build.yml
  .gitignore
  build.gradle
  buildSrc/src/main/java/quilt/internal/MappingsPlugin.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractTinyMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/diff/CheckTargetVersionExistsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/diff/CheckUnpickVersionsMatchTask.java
  buildSrc/src/main/java/quilt/internal/tasks/diff/DownloadTargetMappingJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/diff/RemapTargetMinecraftJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/jarmapping/MapJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/jarmapping/MapNamedJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/jarmapping/MapPerVersionMappingsJarTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/RemapUnpickDefinitionsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/UnpickJarTask.java
  gradle.properties
  gradle/libs.versions.toml
  mappings/net/minecraft/recipe/CookingCategory.mapping
  unpick-definitions/network_packets.unpick
Labels: t: toolchain, v: snapshot, final-comment-period, s: medium

#344 Loot table generator mappings
  mappings/net/minecraft/data/server/loot_table/BarteringLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/ChestLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/FishingLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/GiftLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/OneTwentyChestLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/OneTwentyEntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/OneTwentyFishingLootTableGenerator.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#345 Mapped textures for 23w04a
  .github/actions/diff-uploader/dist/index.js
  .github/actions/diff-uploader/index.js
  .github/workflows/build.yml
  .github/workflows/generate-diff.yml
  mappings/com/mojang/blaze3d/texture/NativeImage.mapping
  mappings/net/minecraft/client/texture/LazyLoadedTexture.mapping
  mappings/net/minecraft/client/texture/PaintingManager.mapping
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/client/texture/PlayerSkinTexture.mapping
  mappings/net/minecraft/client/texture/ResourceTexture.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasHolder.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/texture/atlas/SpriteSource.mapping
  mappings/net/minecraft/client/texture/atlas/source/PaletteSpriteSource.mapping
  mappings/net/minecraft/client/texture/atlas/source/UnstitchSpriteSource.mapping
  mappings/net/minecraft/client/util/ColorUtil.mapping
  mappings/net/minecraft/util/Identifier.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#349 Update Quilt Meta CI
  .github/workflows/publish.yml
Labels: t: toolchain, v: snapshot, s: tiny

#312 remove "worldgen" from carver and feature registry names
  mappings/net/minecraft/registry/Registries.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#317 fix javadoc and field name warnings
  buildSrc/src/main/java/quilt/internal/tasks/lint/FieldNamingChecker.java
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/block/AbstractLichenBlock.mapping
  mappings/net/minecraft/block/EndPortalFrameBlock.mapping
  mappings/net/minecraft/block/HorizontalConnectingBlock.mapping
  mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/EnchantmentScreen.mapping
  mappings/net/minecraft/client/network/LanServerQueryManager.mapping
  mappings/net/minecraft/client/particle/GlowParticle.mapping
  mappings/net/minecraft/client/realms/CheckedGson.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/render/block/entity/HangingSignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SkullBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/debug/ChunkLoadingDebugRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/SaddleFeatureRenderer.mapping
  mappings/net/minecraft/client/texture/atlas/SpriteSources.mapping
  mappings/net/minecraft/client/util/telemetry/event/WorldLoadEvent.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/SittingScanningPhase.mapping
  mappings/net/minecraft/entity/mob/PhantomEntity.mapping
  mappings/net/minecraft/entity/mob/VexEntity.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/TadpoleEntity.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/server/LanServerPinger.mapping
  mappings/net/minecraft/server/command/dev/ChaseCommand.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
  mappings/net/minecraft/server/rcon/RconBase.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrStatsResultSerializer.mapping
  mappings/net/minecraft/util/random/RandomSeed.mapping
  mappings/net/minecraft/world/WorldDataVersion.mapping
  mappings/net/minecraft/world/biome/source/util/OverworldBiomeParameters.mapping
  mappings/net/minecraft/world/gen/DensityFunctions.mapping
  mappings/net/minecraft/world/gen/decorator/BiomePlacementModifier.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: small

#321 rename WorldRenderer$BuiltChunkStorage to RenderableChunks
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#347 Issue #346 - Moved MessageRemovalS2CPacket
  mappings/net/minecraft/network/packet/s2c/play/MessageRemovalS2CPacket.mapping
Labels: bug, t: refactor, v: snapshot, final-comment-period, s: tiny

#350 Fix a Fabricism on the GameTest mappings
  mappings/net/minecraft/test/GameTest.mapping
Labels: v: snapshot, t: javadoc, final-comment-period, s: tiny
