Repository QuiltMC/quilt-mappings, pull requests merged in 2023-04, with the labels that each got.

#391 Some entity mappings
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractSignEditScreen.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/LimbData.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/Brain.mapping
  mappings/net/minecraft/entity/ai/brain/VisibleLivingEntitiesCache.mapping
  mappings/net/minecraft/entity/ai/goal/FollowOwnerGoal.mapping
  mappings/net/minecraft/entity/ai/goal/GoalSelector.mapping
  mappings/net/minecraft/entity/ai/goal/RearGoal.mapping
  mappings/net/minecraft/entity/ai/pathing/AmphibiousPathNodeMaker.mapping
  mappings/net/minecraft/entity/ai/pathing/LandPathNodeMaker.mapping
  mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeMaker.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonSpawnState.mapping
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/entity/mob/AbstractPiglinEntity.mapping
  mappings/net/minecraft/entity/mob/Angerable.mapping
  mappings/net/minecraft/entity/mob/ElderGuardianEntity.mapping
  mappings/net/minecraft/entity/mob/GhastEntity.mapping
  mappings/net/minecraft/entity/mob/GuardianEntity.mapping
  mappings/net/minecraft/entity/mob/HoglinEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/PathAwareEntity.mapping
  mappings/net/minecraft/entity/mob/SilverfishEntity.mapping
  mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
  mappings/net/minecraft/entity/mob/warden/AngerManager.mapping
  mappings/net/minecraft/entity/passive/AbstractDonkeyEntity.mapping
  mappings/net/minecraft/entity/passive/AllayEntity.mapping
  mappings/net/minecraft/entity/passive/AnimalEntity.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/GlowSquidEntity.mapping
  mappings/net/minecraft/entity/passive/GoatEntity.mapping
  mappings/net/minecraft/entity/passive/HorseBaseEntity.mapping
  mappings/net/minecraft/entity/passive/HorseColor.mapping
  mappings/net/minecraft/entity/passive/PandaEntity.mapping
  mappings/net/minecraft/entity/passive/PassiveEntity.mapping
  mappings/net/minecraft/entity/passive/SnifferEntity.mapping
  mappings/net/minecraft/entity/passive/StriderEntity.mapping
  mappings/net/minecraft/entity/passive/TadpoleBrain.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileUtil.mapping
  mappings/net/minecraft/entity/projectile/ShulkerBulletEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/PotionEntity.mapping
  mappings/net/minecraft/entity/vehicle/BoatEntity.mapping
  mappings/net/minecraft/entity/vehicle/StorageVehicle.mapping
  mappings/net/minecraft/entity/vehicle/TntMinecartEntity.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/play/SignUpdateC2SPacket.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#402 Redstone related mappings and refactors
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractPressurePlateBlock.mapping
  mappings/net/minecraft/block/ComparatorBlock.mapping
  mappings/net/minecraft/block/RedstoneDiodeBlock.mapping
  mappings/net/minecraft/world/RedstonePowerView.mapping
Labels: t: refactor, t: new, v: snapshot, final-comment-period, s: small

#405 More resource loader stuff!
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/particle/BlockLeakParticle.mapping
  mappings/net/minecraft/client/particle/ParticleFactory.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/resource/ClientBuiltinResourcePackProvider.mapping
  mappings/net/minecraft/client/resource/ResourceIndex.mapping
  mappings/net/minecraft/client/resource/language/LanguageManager.mapping
  mappings/net/minecraft/client/resource/language/TranslationStorage.mapping
  mappings/net/minecraft/client/resource/metadata/LanguageResourceMetadata.mapping
  mappings/net/minecraft/client/texture/DumpableTexture.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/texture/TextureManager.mapping
  mappings/net/minecraft/resource/fs/ResourceFile.mapping
  mappings/net/minecraft/resource/fs/ResourceFileAttributes.mapping
  mappings/net/minecraft/resource/fs/ResourceFileStore.mapping
  mappings/net/minecraft/resource/fs/ResourceFileSystem.mapping
  mappings/net/minecraft/resource/fs/ResourceFileSystemProvider.mapping
  mappings/net/minecraft/resource/fs/ResourcePath.mapping
  mappings/net/minecraft/resource/pack/DefaultResourcePackBuilder.mapping
  mappings/net/minecraft/resource/pack/ResourcePackManager.mapping
  mappings/net/minecraft/server/function/FunctionLoader.mapping
  mappings/net/minecraft/util/Language.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#407 Refactor ScreenTexts into CommonTexts
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/text/CommonTexts.mapping
  mappings/net/minecraft/text/Text.mapping
Labels: t: refactor, v: snapshot, t: javadoc, final-comment-period, s: tiny

#406 Bunch of stuff: signs, items, loot tables, and more.
  mappings/net/minecraft/block/FarmableBlock.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignText.mapping
  mappings/net/minecraft/data/PackMetadataProvider.mapping
  mappings/net/minecraft/data/server/loot_table/ArchaeologyLootTableGenerator.mapping
  mappings/net/minecraft/entity/AttackReferencePosOffsettingMount.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/passive/CamelEntity.mapping
  mappings/net/minecraft/item/DyeItem.mapping
  mappings/net/minecraft/item/GlowInkSacItem.mapping
  mappings/net/minecraft/item/InkSacItem.mapping
  mappings/net/minecraft/item/SignModifierItem.mapping
  mappings/net/minecraft/loot/LootDataKey.mapping
  mappings/net/minecraft/loot/LootDataLookup.mapping
  mappings/net/minecraft/loot/LootDataType.mapping
  mappings/net/minecraft/loot/LootManager.mapping
  mappings/net/minecraft/loot/LootTableReporter.mapping
  mappings/net/minecraft/predicate/TagPredicate.mapping
  mappings/net/minecraft/registry/Registries.mapping
  mappings/net/minecraft/registry/RegistryKeys.mapping
  mappings/net/minecraft/resource/JsonDataLoader.mapping
  mappings/net/minecraft/resource/SinglePreparationResourceReloader.mapping
  mappings/net/minecraft/structure/rule/block/entity/AppendLootRuleBlockEntityModifier.mapping
  mappings/net/minecraft/structure/rule/block/entity/AppendStaticRuleBlockEntityModifier.mapping
  mappings/net/minecraft/structure/rule/block/entity/ClearRuleBlockEntityModifier.mapping
  mappings/net/minecraft/structure/rule/block/entity/PassthroughRuleBlockEntityModifier.mapping
  mappings/net/minecraft/structure/rule/block/entity/RuleBlockEntityModifier.mapping
  mappings/net/minecraft/structure/rule/block/entity/RuleBlockEntityModifierType.mapping
  mappings/net/minecraft/util/CommonColors.mapping
Labels: documentation, t: new, v: snapshot, final-comment-period, s: medium
