Repository QuiltMC/quilt-mappings, pull requests merged in 2023-09, with the labels that each got.

#483 Networking mappings
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/connection/ClientConnectionState.mapping
  mappings/net/minecraft/client/network/AbstractClientNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientConfigurationNetworkHandler.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/network/NetworkSide.mapping
  mappings/net/minecraft/network/ServerConfigurationPacketHandler.mapping
  mappings/net/minecraft/network/configuration/ConfigurationTask.mapping
  mappings/net/minecraft/network/configuration/JoinWorldConfigurationTask.mapping
  mappings/net/minecraft/network/configuration/ServerResourcePackConfigurationTask.mapping
  mappings/net/minecraft/network/listener/AbstractServerPacketHandler.mapping
  mappings/net/minecraft/network/listener/ClientConfigurationPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerBasePacketListener.mapping
  mappings/net/minecraft/network/listener/ServerConfigurationPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerPingPacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/common/CustomPayloadC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/common/KeepConnectionAliveC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/common/PongC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/common/ResourcePackStatusUpdateC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/configuration/FinishConfigurationC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/CustomPayloadS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/DisconnectS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/KeepConnectionAliveS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/PingS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/ResourcePackS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/TagsSynchronizationS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/configuration/FinishConfigurationS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/configuration/RegistryDataS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/configuration/SynchronizeEnabledFeatureFlagsS2CPacket.mapping
  mappings/net/minecraft/server/network/ServerChunkSender.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerConnection.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/EntityTrackingListener.mapping
  mappings/net/minecraft/unmapped/C_xcfjcqcn.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#479 A small amount of 1.20.2 mappings
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/ChorusFlowerBlock.mapping
  mappings/net/minecraft/block/FlowerBlock.mapping
  mappings/net/minecraft/block/FluidDrainable.mapping
  mappings/net/minecraft/block/WallBlock.mapping
  mappings/net/minecraft/block/entity/BeaconBlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntityType.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/EquipmentSlot.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributes.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/SuspiciousStewEffectContainer.mapping
  mappings/net/minecraft/item/SuspiciousStewItem.mapping
  mappings/net/minecraft/util/shape/VoxelShape.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#493 Renaming non-abstract `AbstractButtonBlock` to `ButtonBlock`
  mappings/net/minecraft/block/ButtonBlock.mapping
Labels: t: refactor, v: snapshot, s: tiny

#488 Update some `EditGameRulesScreen` and `GameRules` mappings for accuracy and consistency
  mappings/net/minecraft/client/gui/screen/world/EditGameRulesScreen.mapping
  mappings/net/minecraft/world/GameRules.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: medium

#501 Switch to the new Minecraft Wiki URL
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/world/World.mapping
Labels: v: release, t: javadoc, final-comment-period, s: tiny
