Repository QuiltMC/quilt-mappings, pull requests merged in 2023-08, with the labels that each got.

#468 Quiltflower -> Vineflower
  .github/workflows/generate-diff.yml
  README.md
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/quilt/internal/decompile/Decompilers.java
  buildSrc/src/main/java/quilt/internal/decompile/vineflower/VineflowerDecompiler.java
  buildSrc/src/main/java/quilt/internal/decompile/vineflower/VineflowerJavadocProvider.java
  buildSrc/src/main/java/quilt/internal/decompile/vineflower/VineflowerResultSaver.java
  gradle/libs.versions.toml
Labels: t: toolchain, v: release, final-comment-period, s: small

#469 mostly client mappings
  mappings/net/minecraft/block/BlockSetType.mapping
  mappings/net/minecraft/block/LavaCauldronBlock.mapping
  mappings/net/minecraft/block/PowderSnowCauldronBlock.mapping
  mappings/net/minecraft/block/SignBlock.mapping
  mappings/net/minecraft/block/cauldron/AbstractCauldronBlock.mapping
  mappings/net/minecraft/block/cauldron/CauldronBlock.mapping
  mappings/net/minecraft/block/cauldron/LavaCauldronBlock.mapping
  mappings/net/minecraft/block/cauldron/LeveledCauldronBlock.mapping
  mappings/net/minecraft/block/cauldron/PowderSnowCauldronBlock.mapping
  mappings/net/minecraft/block/dispenser/DispenserBlock.mapping
  mappings/net/minecraft/block/piston/PistonBlock.mapping
  mappings/net/minecraft/block/piston/PistonExtensionBlock.mapping
  mappings/net/minecraft/block/piston/PistonHeadBlock.mapping
  mappings/net/minecraft/block/sapling/SaplingBlock.mapping
  mappings/net/minecraft/block/sculk/SculkBlock.mapping
  mappings/net/minecraft/block/sculk/SculkCatalystBlock.mapping
  mappings/net/minecraft/block/sculk/SculkSensorBlock.mapping
  mappings/net/minecraft/block/sculk/SculkShriekerBlock.mapping
  mappings/net/minecraft/block/sculk/SculkVeinBlock.mapping
  mappings/net/minecraft/block/sign/AbstractSignBlock.mapping
  mappings/net/minecraft/block/sign/CeilingHangingSignBlock.mapping
  mappings/net/minecraft/block/sign/SignBlock.mapping
  mappings/net/minecraft/block/sign/SignType.mapping
  mappings/net/minecraft/block/sign/WallHangingSignBlock.mapping
  mappings/net/minecraft/block/sign/WallSignBlock.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/multiplayer/prediction/BlockStatePredictionManager.mapping
  mappings/net/minecraft/client/network/ClientLoginNetworkHandler.mapping
  mappings/net/minecraft/client/util/ChatNarratorManager.mapping
  mappings/net/minecraft/client/util/NetworkUtils.mapping
  mappings/net/minecraft/client/util/ParticleUtil.mapping
  mappings/net/minecraft/client/util/PlayerKeyPairManager.mapping
  mappings/net/minecraft/client/util/ScreenshotRecorder.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryManager.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryProperty.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryPropertyMap.mapping
  mappings/net/minecraft/client/util/telemetry/WorldTelemetryManager.mapping
  mappings/net/minecraft/client/util/telemetry/event/GameLoadTimesEvent.mapping
  mappings/net/minecraft/client/util/telemetry/event/TelemetryEventType.mapping
  mappings/net/minecraft/client/util/telemetry/event/WorldLoadEvent.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/client/world/FlatWorldGeneratorPresets.mapping
  mappings/net/minecraft/client/world/GeneratorType.mapping
  mappings/net/minecraft/client/world/GeneratorTypes.mapping
  mappings/net/minecraft/client/world/WorldCreationContext.mapping
  mappings/net/minecraft/client/world/WorldCreator.mapping
  mappings/net/minecraft/unmapped/C_czisrdmd.mapping
  mappings/net/minecraft/util/Graph.mapping
  mappings/net/minecraft/util/SegmentedAnglePrecision.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
Labels: t: new, v: release, final-comment-period, s: medium

#473 Use new Javadoc publishing, link to Quilt Loader.
  .github/workflows/publish.yml
  build.gradle
  gradle/libs.versions.toml
Labels: t: toolchain, v: snapshot, final-comment-period

#471 more client mappings!
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/font/BitmapFont.mapping
  mappings/net/minecraft/client/font/CodepointMap.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/FontRenderType.mapping
  mappings/net/minecraft/client/font/FontStorage.mapping
  mappings/net/minecraft/client/font/FontTypeProvider.mapping
  mappings/net/minecraft/client/font/GlyphAtlasTexture.mapping
  mappings/net/minecraft/client/font/GlyphRenderer.mapping
  mappings/net/minecraft/client/font/UnihexFont.mapping
  mappings/net/minecraft/client/gui/ChatReportCategory.mapping
  mappings/net/minecraft/client/gui/GuiAtlasManager.mapping
  mappings/net/minecraft/client/gui/GuiGraphics.mapping
  mappings/net/minecraft/client/gui/PlayerFaceRenderer.mapping
  mappings/net/minecraft/client/gui/widget/TelemetryEventWidget.mapping
  mappings/net/minecraft/client/multiplayer/prediction/PredictiveAction.mapping
  mappings/net/minecraft/client/multiplayer/report/chat/ChatReportContextBuilder.mapping
  mappings/net/minecraft/client/network/ClientAdvancementManager.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/client/option/CloudRenderMode.mapping
  mappings/net/minecraft/client/resource/ClientBuiltinResourcePackProvider.mapping
  mappings/net/minecraft/client/resource/metadata/GuiResourceMetadata.mapping
  mappings/net/minecraft/client/sound/Sound.mapping
  mappings/net/minecraft/client/sound/SoundListener.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
  mappings/net/minecraft/client/texture/MissingSprite.mapping
  mappings/net/minecraft/client/texture/PlayerSkin.mapping
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasHolder.mapping
  mappings/net/minecraft/client/texture/SpriteContents.mapping
  mappings/net/minecraft/client/texture/SpriteLoader.mapping
  mappings/net/minecraft/client/texture/SpriteScaling.mapping
  mappings/net/minecraft/client/texture/atlas/SpriteResourceLoader.mapping
  mappings/net/minecraft/client/texture/atlas/SpriteSource.mapping
  mappings/net/minecraft/client/texture/atlas/SpriteSources.mapping
  mappings/net/minecraft/client/texture/atlas/source/UnstitchSpriteSource.mapping
  mappings/net/minecraft/client/toast/AdvancementToast.mapping
  mappings/net/minecraft/client/toast/ToastManager.mapping
  mappings/net/minecraft/client/tutorial/CraftPlanksTutorialStepHandler.mapping
  mappings/net/minecraft/client/tutorial/FindTreeTutorialStepHandler.mapping
  mappings/net/minecraft/client/tutorial/MovementTutorialStepHandler.mapping
  mappings/net/minecraft/client/util/DefaultSkinHelper.mapping
  mappings/net/minecraft/client/util/SelectionManager.mapping
  mappings/net/minecraft/client/world/ClientChunkManager.mapping
  mappings/net/minecraft/command/SignedArgument.mapping
  mappings/net/minecraft/command/SignedCommand.mapping
  mappings/net/minecraft/command/argument/ArgumentSignatures.mapping
  mappings/net/minecraft/resource/ResourceMetadata.mapping
  mappings/net/minecraft/resource/pack/ResourcePackProfile.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#476 Some rendering mappings
  mappings/com/mojang/blaze3d/font/SpaceFont.mapping
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/com/mojang/blaze3d/texture/TextureUtil.mapping
  mappings/com/mojang/blaze3d/vertex/OverlayVertexConsumer.mapping
  mappings/net/minecraft/client/render/BuiltChunkStorage.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#465 rewrite readme
  CONTRIBUTING.md
  GUIDE.md
  README.md
Labels: documentation, v: snapshot, final-comment-period, s: small

#481 Resource mappings
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/resource/ResourceMetadata.mapping
  mappings/net/minecraft/resource/pack/BuiltinResourcePackProvider.mapping
  mappings/net/minecraft/resource/pack/CompositeResourcePack.mapping
  mappings/net/minecraft/resource/pack/FileResourcePackProvider.mapping
  mappings/net/minecraft/resource/pack/NioResourcePack.mapping
  mappings/net/minecraft/resource/pack/PackDetector.mapping
  mappings/net/minecraft/resource/pack/ResourcePack.mapping
  mappings/net/minecraft/resource/pack/ResourcePackCompatibility.mapping
  mappings/net/minecraft/resource/pack/ResourcePackProfile.mapping
  mappings/net/minecraft/resource/pack/ZipResourcePack.mapping
  mappings/net/minecraft/resource/pack/metadata/PackFeatureFlagsMetadataSection.mapping
  mappings/net/minecraft/resource/pack/metadata/PackOverlayMetadataSection.mapping
  mappings/net/minecraft/resource/pack/metadata/PackResourceMetadataSection.mapping
  mappings/net/minecraft/resource/pack/metadata/ResourceFilterMetadataSection.mapping
  mappings/net/minecraft/resource/pack/metadata/ResourceMetadataSectionReader.mapping
  mappings/net/minecraft/util/path/SymlinkValidator.mapping
Labels: t: refactor, t: new, v: snapshot, final-comment-period, s: small

#478 some mappings ^-^
  mappings/net/minecraft/advancement/AdvancementVisibilityEvaluator.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/BarrierBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/ChorusFlowerBlock.mapping
  mappings/net/minecraft/block/CropBlock.mapping
  mappings/net/minecraft/block/FluidDrainable.mapping
  mappings/net/minecraft/block/FluidFillable.mapping
  mappings/net/minecraft/block/PinkPetalsBlock.mapping
  mappings/net/minecraft/block/PitcherCropBlock.mapping
  mappings/net/minecraft/block/enums/DoubleBlockHalf.mapping
  mappings/net/minecraft/client/gui/hud/AbstractDebugChart.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPopupScreen.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/realms/RealmsAvailability.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/WorldLoader.mapping
  mappings/net/minecraft/server/WorldStem.mapping
  mappings/net/minecraft/util/Formatting.mapping
  mappings/net/minecraft/util/SampleLogger.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/world/entity/ai/brain/MemoryCondition.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny
