Repository QuiltMC/quilt-mappings, pull requests merged in 2023-03, with the labels that each got.

#370 Add DoubleNsCompleterVisitor and UnmappedNameRemoverVisitor
  buildSrc/src/main/java/quilt/internal/mappingio/CompleteInitializersVisitor.java
  buildSrc/src/main/java/quilt/internal/mappingio/DoubleNsCompleterVisitor.java
  buildSrc/src/main/java/quilt/internal/mappingio/UnmappedNameRemoverVisitor.java
  buildSrc/src/test/java/quilt/internal/mappingio/DoubleNsCompleterVisitorTest.java
  buildSrc/src/test/java/quilt/internal/mappingio/UnmappedNameRemoverVisitorTest.java
  buildSrc/src/test/resources/doubleNsCompleter.tiny
  buildSrc/src/test/resources/unmappedNameRemover.tiny
Labels: enhancement, t: toolchain, v: snapshot, s: medium

#371 Remove as much hashed names as possible from intermediary publication
  build.gradle
  buildSrc/src/main/java/quilt/internal/mappingio/UnmappedNameRemoverVisitor.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractTinyMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AddProposedMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeIntermediaryTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/MergeTinyV2Task.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/RemapUnpickDefinitionsTask.java
  buildSrc/src/test/java/quilt/internal/TasksTest.java
  buildSrc/src/test/java/quilt/internal/input/IClass.java
  buildSrc/src/test/java/quilt/internal/input/JClass.java
  buildSrc/src/test/java/quilt/internal/input/KClass.java
  buildSrc/src/test/java/quilt/internal/input/Keep.java
  buildSrc/src/test/java/quilt/internal/input/LClass.java
  buildSrc/src/test/java/quilt/internal/input/MInterface.java
  buildSrc/src/test/java/quilt/internal/input/NInterface.java
  buildSrc/src/test/java/quilt/internal/input/OClass.java
  buildSrc/src/test/java/quilt/internal/input/PClass.java
  buildSrc/src/test/java/quilt/internal/util/MappingAssertions.java
  buildSrc/src/test/resources/proguard-test.conf
  buildSrc/src/test/resources/test-intermediate-alt.tiny
  buildSrc/src/test/resources/test-intermediate.tiny
  buildSrc/src/test/resources/testProject/mappings/com/example/LClass.mapping
  buildSrc/src/test/resources/testProject/mappings/com/example/u/C_012.mapping
  gradle/libs.versions.toml
Labels: bug, t: toolchain, v: snapshot, final-comment-period, s: medium

#326 new structure and chunk mappings
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/server/world/ChunkTaskPrioritySystem.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/LevelPrioritizedQueue.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ThreadedChunkManager.mapping
  mappings/net/minecraft/structure/AncientCityData.mapping
  mappings/net/minecraft/structure/AncientCityGenerator.mapping
  mappings/net/minecraft/structure/BastionBridgeData.mapping
  mappings/net/minecraft/structure/BastionData.mapping
  mappings/net/minecraft/structure/BastionRemnantGenerator.mapping
  mappings/net/minecraft/structure/BastionTreasureData.mapping
  mappings/net/minecraft/structure/BastionUnitsData.mapping
  mappings/net/minecraft/structure/ConcentricRingPlacementCalculator.mapping
  mappings/net/minecraft/structure/DesertVillageData.mapping
  mappings/net/minecraft/structure/HoglinStableData.mapping
  mappings/net/minecraft/structure/PillagerOutpostGenerator.mapping
  mappings/net/minecraft/structure/PlainsVillageData.mapping
  mappings/net/minecraft/structure/PostPlacementProcessor.mapping
  mappings/net/minecraft/structure/RandomSpreadType.mapping
  mappings/net/minecraft/structure/SavannaVillageData.mapping
  mappings/net/minecraft/structure/SnowyVillageData.mapping
  mappings/net/minecraft/structure/Structure.mapping
  mappings/net/minecraft/structure/StructureManager.mapping
  mappings/net/minecraft/structure/StructurePlacement.mapping
  mappings/net/minecraft/structure/StructureTemplateManager.mapping
  mappings/net/minecraft/structure/TaigaVillageData.mapping
  mappings/net/minecraft/structure/piece/StructurePieceType.mapping
  mappings/net/minecraft/structure/pool/StructurePool.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/structure/pool/StructurePools.mapping
  mappings/net/minecraft/structure/processor/BlockRotStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/ProtectedBlocksStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorLists.mapping
  mappings/net/minecraft/unmapped/C_jibygqpu.mapping
  mappings/net/minecraft/util/math/BlockBox.mapping
  mappings/net/minecraft/village/VillagerType.mapping
  mappings/net/minecraft/world/chunk/ChunkManager.mapping
  mappings/net/minecraft/world/chunk/ChunkTickTracker.mapping
  mappings/net/minecraft/world/gen/WorldGeneratorOptions.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
  mappings/net/minecraft/world/poi/PointOfInterestTypes.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
Labels: t: refactor, t: new, v: snapshot, final-comment-period, s: medium

#382 Pink Petals Block Mappings
  mappings/net/minecraft/block/PinkPetalsBlock.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#357 cause build failure on bad casing
  buildSrc/src/main/java/quilt/internal/tasks/lint/FieldNamingChecker.java
  mappings/net/minecraft/potion/Potions.mapping
  mappings/net/minecraft/util/UuidUtil.mapping
Labels: enhancement, t: refactor, t: toolchain, v: snapshot, final-comment-period, s: tiny

#385 net.minecraft.item coverage
  mappings/net/minecraft/item/BannerItem.mapping
  mappings/net/minecraft/item/BoneMealItem.mapping
  mappings/net/minecraft/item/CompassItem.mapping
  mappings/net/minecraft/item/DecorationItem.mapping
  mappings/net/minecraft/item/Equippable.mapping
  mappings/net/minecraft/item/FilledMapItem.mapping
  mappings/net/minecraft/item/HoeItem.mapping
  mappings/net/minecraft/item/InstrumentItem.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/item/ShearsItem.mapping
  mappings/net/minecraft/item/SkullItem.mapping
  mappings/net/minecraft/item/SmithingTemplateItem.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterials.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPermutation.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#384 some random mappings
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/PeriodicNotificationManager.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/ParentElement.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmLinkScreen.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/InventoryScreen.mapping
  mappings/net/minecraft/client/gui/widget/ElementListWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/client/model/ModelTransformMode.mapping
  mappings/net/minecraft/client/multiplayer/chat/LoggedChatEvent.mapping
  mappings/net/minecraft/client/multiplayer/report/BanNoticeScreen.mapping
  mappings/net/minecraft/client/multiplayer/report/ReportReason.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/TrustLevel.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/sound/PositionedSoundInstance.mapping
  mappings/net/minecraft/text/ScreenTexts.mapping
  mappings/net/minecraft/unmapped/C_crjxgxtz.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#386 more random mappings
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/advancement/PlayerAdvancementTracker.mapping
  mappings/net/minecraft/block/CherryLeavesBlock.mapping
  mappings/net/minecraft/block/CherrySaplingBlock.mapping
  mappings/net/minecraft/block/TorchflowerBlock.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/color/block/BlockColors.mapping
  mappings/net/minecraft/client/color/world/BiomeColors.mapping
  mappings/net/minecraft/client/color/world/FoliageColors.mapping
  mappings/net/minecraft/client/color/world/GrassColors.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/client/font/UnicodeTextureFont.mapping
  mappings/net/minecraft/client/gui/screen/AbuseReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/ChatSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/CreditsAndAttributionScreen.mapping
  mappings/net/minecraft/client/gui/screen/ExperimentsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LegacySmithingScreen.mapping
  mappings/net/minecraft/client/gui/widget/ScrollableTexturedButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/TabWidget.mapping
  mappings/net/minecraft/client/gui/widget/TexturedWidget.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/render/block/entity/DecoratedPotBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SuspiciousSandBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/DisplayEntityRenderer.mapping
  mappings/net/minecraft/client/sound/SnifferSoundInstance.mapping
  mappings/net/minecraft/client/util/ParticleUtil.mapping
  mappings/net/minecraft/client/util/PlayerKeyPairManager.mapping
  mappings/net/minecraft/client/util/PlayerKeyPairManagerImpl.mapping
  mappings/net/minecraft/command/SignedArgument.mapping
  mappings/net/minecraft/data/server/VanillaLootTableProvider.mapping
  mappings/net/minecraft/data/server/loot_table/DesertArchaeologyLootTableGenerator.mapping
  mappings/net/minecraft/datafixer/schema/Schema3325.mapping
  mappings/net/minecraft/datafixer/schema/Schema3326.mapping
  mappings/net/minecraft/datafixer/schema/Schema3327.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/LivingEntitySensor.mapping
  mappings/net/minecraft/entity/damage/DamageScalingType.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/loot/OneTwentyArchaeologyLootTables.mapping
  mappings/net/minecraft/network/packet/s2c/play/ClientPlayS2CPacket.mapping
  mappings/net/minecraft/recipe/DecoratedPotRecipe.mapping
  mappings/net/minecraft/screen/LegacySmithingScreenHandler.mapping
  mappings/net/minecraft/util/SegmentedAnglePrecision.mapping
  mappings/net/minecraft/util/UrlConstants.mapping
  mappings/net/minecraft/world/biome/OverworldBiomeCreator.mapping
  mappings/net/minecraft/world/gen/BiomeData.mapping
  mappings/net/minecraft/world/gen/feature/EndConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/MiscConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/NetherConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/OceanConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/OreConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/PileConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/TreeConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/UndergroundConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/VegetationConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/util/ConfiguredFeatureUtil.mapping
  mappings/net/minecraft/world/gen/foliage/CherryFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/trunk/CherryTrunkPlacer.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#380 utility and misc
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/network/AbstractClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/LanServerQueryManager.mapping
  mappings/net/minecraft/client/network/MultiplayerServerListPinger.mapping
  mappings/net/minecraft/client/network/OtherClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/world/ClientChunkManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/util/Arm.mapping
  mappings/net/minecraft/util/collection/IndexedIterable.mapping
  mappings/net/minecraft/util/collection/PackedIntegerArray.mapping
  mappings/net/minecraft/util/collection/SortedArraySet.mapping
  mappings/net/minecraft/util/collection/Weighting.mapping
  mappings/net/minecraft/util/crash/CrashReport.mapping
  mappings/net/minecraft/util/crash/CrashReportSection.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/dynamic/ForwardingDynamicOps.mapping
  mappings/net/minecraft/util/function/ToFloatFunction.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/math/Box.mapping
  mappings/net/minecraft/util/math/ColumnPos.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
  mappings/net/minecraft/util/math/floatprovider/ClampedNormalFloatProvider.mapping
  mappings/net/minecraft/util/math/intprovider/IntProvider.mapping
  mappings/net/minecraft/util/thread/LockHelper.mapping
  mappings/net/minecraft/world/chunk/ChunkManager.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
Labels: t: new, v: snapshot, reviews needed, final-comment-period, s: medium

#376 even more entity things
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/client/render/model/json/ModelTransformationMode.mapping
  mappings/net/minecraft/client/util/ColorUtil.mapping
  mappings/net/minecraft/entity/AreaEffectCloudEntity.mapping
  mappings/net/minecraft/entity/Attackable.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityStatuses.mapping
  mappings/net/minecraft/entity/EquipmentSlot.mapping
  mappings/net/minecraft/entity/FallingBlockEntity.mapping
  mappings/net/minecraft/entity/InteractionEntity.mapping
  mappings/net/minecraft/entity/InventoryOwner.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/MovementFlag.mapping
  mappings/net/minecraft/entity/Ownable.mapping
  mappings/net/minecraft/entity/PacketPositionCodec.mapping
  mappings/net/minecraft/entity/SaddledComponent.mapping
  mappings/net/minecraft/entity/SpawnRestriction.mapping
  mappings/net/minecraft/entity/Tameable.mapping
  mappings/net/minecraft/entity/damage/DamageTracker.mapping
  mappings/net/minecraft/entity/damage/DeathMessageType.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandler.mapping
  mappings/net/minecraft/entity/decoration/Brightness.mapping
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/entity/decoration/ItemFrameEntity.mapping
  mappings/net/minecraft/entity/mob/Angerable.mapping
  mappings/net/minecraft/entity/mob/EndermanEntity.mapping
  mappings/net/minecraft/entity/mob/SpellcastingIllagerEntity.mapping
  mappings/net/minecraft/entity/mob/WaterCreatureEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieVillagerEntity.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerPoseUpdateS2CPacket.mapping
  mappings/net/minecraft/unmapped/C_itacphfv.mapping
  mappings/net/minecraft/util/math/AffineTransformation.mapping
  mappings/net/minecraft/world/World.mapping
Labels: t: new, v: snapshot, reviews needed, final-comment-period, s: medium

#373 1.19.4 random things
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/block/DecoratedPotPatterns.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/model/ModelCuboidData.mapping
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/client/model/ModelPartBuilder.mapping
  mappings/net/minecraft/client/realms/CheckedGson.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/RepeatedNarrator.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BeaconBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/debug/GameEventDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/PathfindingDebugRenderer.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingEntity.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/item/SmithingTemplateItem.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterials.mapping
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/registry/DynamicRegistrySync.mapping
  mappings/net/minecraft/registry/Registries.mapping
  mappings/net/minecraft/registry/Registry.mapping
  mappings/net/minecraft/resource/HolderSetCodec.mapping
  mappings/net/minecraft/scoreboard/AbstractTeam.mapping
  mappings/net/minecraft/scoreboard/Scoreboard.mapping
  mappings/net/minecraft/scoreboard/ScoreboardCriterion.mapping
  mappings/net/minecraft/scoreboard/ScoreboardState.mapping
  mappings/net/minecraft/scoreboard/Team.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/sound/SoundEvents.mapping
  mappings/net/minecraft/test/TestServer.mapping
  mappings/net/minecraft/text/Style.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/text/component/TranslatableComponent.mapping
  mappings/net/minecraft/util/Arm.mapping
  mappings/net/minecraft/util/JsonHelper.mapping
  mappings/net/minecraft/util/Language.mapping
  mappings/net/minecraft/util/LowercaseEnumTypeAdapterFactory.mapping
  mappings/net/minecraft/util/SignType.mapping
  mappings/net/minecraft/util/SimpleBitStorage.mapping
  mappings/net/minecraft/util/collection/SortedArraySet.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/shape/ArrayVoxelShape.mapping
  mappings/net/minecraft/world/MobSpawnerLogic.mapping
  mappings/net/minecraft/world/event/listener/GameEventListener.mapping
  mappings/net/minecraft/world/gen/BootstrapContext.mapping
  mappings/net/minecraft/world/gen/DensityFunctions.mapping
  unpick-definitions/scoreboard.unpick
Labels: t: new, v: snapshot, reviews needed, final-comment-period, s: medium

#387 Fix conflicting names
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/entity/passive/AbstractDonkeyEntity.mapping
  mappings/net/minecraft/entity/passive/HorseBaseEntity.mapping
Labels: bug, t: refactor, v: release, final-comment-period, critical, s: tiny

#390 data tracker set methods
  mappings/net/minecraft/entity/data/DataTracker.mapping
Labels: t: new, v: release, final-comment-period, s: tiny

#389 A bunch of gui mappings
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/ResourcePackOrganizer.mapping
  mappings/net/minecraft/client/gui/widget/TabWidget.mapping
Labels: t: new, v: release, final-comment-period, s: small

#395 Use draw and not computeVertices for methods that draw in TextRenderer.
  mappings/net/minecraft/client/font/TextRenderer.mapping
Labels: t: refactor, v: release, final-comment-period, s: tiny

#392 mappings & refactor for tags providers
  mappings/net/minecraft/data/server/tag/OneTwentyBiomeTagsProvider.mapping
  mappings/net/minecraft/data/server/tag/OneTwentyBlockTagsProvider.mapping
  mappings/net/minecraft/data/server/tag/UpdateOneTwentyBlockTagsProvider.mapping
Labels: t: refactor, t: new, final-comment-period, s: tiny

#400 Miscellaneous Block Mappings for 1.20
  mappings/net/minecraft/block/CalibratedSculkSensorBlock.mapping
  mappings/net/minecraft/block/PitcherCropBlock.mapping
  mappings/net/minecraft/block/SnifferEggBlock.mapping
  mappings/net/minecraft/block/TorchflowerCropBlock.mapping
  mappings/net/minecraft/block/entity/CalibratedSculkSensorBlockEntity.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#394 Remap ItemRenderer and several other stuff.
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/ParentElement.mapping
  mappings/net/minecraft/client/gui/RotatingCubeMapRenderer.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipComponent.mapping
  mappings/net/minecraft/client/render/LightmapTextureManager.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/ShaderProgram.mapping
  mappings/net/minecraft/client/render/item/HeldItemRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/model/BakedQuadFactory.mapping
  mappings/net/minecraft/client/render/model/json/ModelOverrideList.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
  mappings/net/minecraft/util/math/GivensParameters.mapping
  mappings/net/minecraft/util/math/MatrixUtil.mapping
Labels: documentation, t: new, t: port, v: snapshot, final-comment-period, s: small

#397 a few screen handler mappings
  mappings/net/minecraft/screen/BeaconScreenHandler.mapping
  mappings/net/minecraft/screen/ForgingScreenHandler.mapping
  mappings/net/minecraft/screen/slot/ItemCombinationSlotManager.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#401 screen handler mappings for 1.19, redo
  mappings/net/minecraft/screen/BeaconScreenHandler.mapping
  mappings/net/minecraft/screen/ForgingScreenHandler.mapping
  mappings/net/minecraft/screen/slot/ItemCombinationSlotManager.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
Labels: t: port, v: release, s: tiny
