Repository QuiltMC/quilt-mappings, pull requests merged in 2023-02, with the labels that each got.

#329 random mappings
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/dedicated/DedicatedPlayerManager.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/util/ChatUtil.mapping
  mappings/net/minecraft/util/DyeColor.mapping
  mappings/net/minecraft/util/FastBufferedInputStream.mapping
  mappings/net/minecraft/util/logging/LoggerPrintStream.mapping
  mappings/net/minecraft/util/logging/UncaughtExceptionHandler.mapping
  mappings/net/minecraft/util/logging/UncaughtExceptionLogger.mapping
  mappings/net/minecraft/util/math/noise/InterpolatedNoiseSampler.mapping
  mappings/net/minecraft/util/profiler/DebugRecorder.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrStatsResultSerializer.mapping
  mappings/net/minecraft/village/raid/RaidManager.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#351 Armor Trims
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/entity/feature/ArmorFeatureRenderer.mapping
  mappings/net/minecraft/item/ArmorItem.mapping
  mappings/net/minecraft/item/ArmorMaterial.mapping
  mappings/net/minecraft/item/ArmorMaterials.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/SmithingUpgradeItem.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterial.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterials.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPattern.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPatterns.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPermutation.mapping
  mappings/net/minecraft/text/ScreenTexts.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#348 Backport 323 (`Block loot table generators`) for 1.19.3
  mappings/net/minecraft/data/server/loot_table/BlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/LootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/OneTwentyBlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loot_table/VanillaBlockLootTableGenerator.mapping
Labels: t: new, t: port, v: release, final-comment-period, s: small

#352 improve data package coverage
  mappings/net/minecraft/data/DataCache.mapping
  mappings/net/minecraft/data/DataGenerator.mapping
  mappings/net/minecraft/data/DataPackOutput.mapping
  mappings/net/minecraft/data/DataProvider.mapping
  mappings/net/minecraft/data/DataWriter.mapping
  mappings/net/minecraft/data/SnbtProvider.mapping
  mappings/net/minecraft/data/client/BlockStateDefinitionProvider.mapping
  mappings/net/minecraft/data/client/ItemModelGenerator.mapping
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/model/Models.mapping
  mappings/net/minecraft/data/client/model/Texture.mapping
  mappings/net/minecraft/data/dev/NbtProvider.mapping
  mappings/net/minecraft/data/family/BlockFamilies.mapping
  mappings/net/minecraft/data/family/BlockFamily.mapping
  mappings/net/minecraft/data/report/BlockListProvider.mapping
  mappings/net/minecraft/data/report/CommandSyntaxProvider.mapping
  mappings/net/minecraft/data/server/RecipesProvider.mapping
  mappings/net/minecraft/data/server/advancement/AdvancementTabGenerator.mapping
  mappings/net/minecraft/data/server/recipe/BundleRecipesProvider.mapping
  mappings/net/minecraft/data/server/recipe/ComplexRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/CookingRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/CraftingRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/RecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/ShapedRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/ShapelessRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/SingleItemRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/tag/AbstractTagProvider.mapping
  mappings/net/minecraft/data/server/tag/BannerPatternTagProvider.mapping
  mappings/net/minecraft/data/server/tag/BiomeTagsProvider.mapping
  mappings/net/minecraft/data/server/tag/BlockTagsProvider.mapping
  mappings/net/minecraft/data/server/tag/CatTypeTagProvider.mapping
  mappings/net/minecraft/data/server/tag/EntityTypeTagsProvider.mapping
  mappings/net/minecraft/data/server/tag/FlatWorldGeneratorPresetTagProvider.mapping
  mappings/net/minecraft/data/server/tag/FluidTagsProvider.mapping
  mappings/net/minecraft/data/server/tag/GameEventTagsProvider.mapping
  mappings/net/minecraft/data/server/tag/InstrumentTagProvider.mapping
  mappings/net/minecraft/data/server/tag/ItemTagsProvider.mapping
  mappings/net/minecraft/data/server/tag/TagsProvider.mapping
  mappings/net/minecraft/data/server/tag/UpdateOneTwentyBlockTagsProvider.mapping
  mappings/net/minecraft/data/server/tag/WorldPresetTagProvider.mapping
  mappings/net/minecraft/datafixer/DataFixTypes.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/predicate/item/ItemPredicate.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#354 23w05a mappings, recipe refactors
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/data/server/recipe/LegacySmithingRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/TransformSmithingRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/TrimSmithingRecipeJsonFactory.mapping
  mappings/net/minecraft/item/ArmorMaterials.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/SmithingTemplateItem.mapping
  mappings/net/minecraft/recipe/AbstractCookingRecipe.mapping
  mappings/net/minecraft/recipe/BlastingRecipe.mapping
  mappings/net/minecraft/recipe/CampfireCookingRecipe.mapping
  mappings/net/minecraft/recipe/CookingRecipeSerializer.mapping
  mappings/net/minecraft/recipe/CuttingRecipe.mapping
  mappings/net/minecraft/recipe/FireworkStarRecipe.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/recipe/LegacySmithingRecipe.mapping
  mappings/net/minecraft/recipe/MapExtendingRecipe.mapping
  mappings/net/minecraft/recipe/Recipe.mapping
  mappings/net/minecraft/recipe/RecipeSerializer.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
  mappings/net/minecraft/recipe/ShapelessRecipe.mapping
  mappings/net/minecraft/recipe/SmeltingRecipe.mapping
  mappings/net/minecraft/recipe/SmithingRecipe.mapping
  mappings/net/minecraft/recipe/SmokingRecipe.mapping
  mappings/net/minecraft/recipe/SpecialCraftingRecipe.mapping
  mappings/net/minecraft/recipe/TransformSmithingRecipe.mapping
  mappings/net/minecraft/recipe/TrimSmithingRecipe.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/text/ScreenTexts.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
Labels: t: refactor, t: new, v: snapshot, s: medium

#359 Mappings for damage type tags (& Provider) & record class
  mappings/net/minecraft/data/server/tag/DamageTypeTagsProvider.mapping
  mappings/net/minecraft/entity/damage/DamageType.mapping
  mappings/net/minecraft/registry/tag/DamageTypeTags.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#356 Command plus random
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/command/BlockDataObject.mapping
  mappings/net/minecraft/command/CommandBuildContext.mapping
  mappings/net/minecraft/command/CommandSource.mapping
  mappings/net/minecraft/command/DataCommandObject.mapping
  mappings/net/minecraft/command/DataCommandStorage.mapping
  mappings/net/minecraft/command/EntityDataObject.mapping
  mappings/net/minecraft/command/EntitySelector.mapping
  mappings/net/minecraft/command/EntitySelectorOptions.mapping
  mappings/net/minecraft/command/EntitySelectorReader.mapping
  mappings/net/minecraft/command/StorageDataObject.mapping
  mappings/net/minecraft/command/argument/ArgumentSignatures.mapping
  mappings/net/minecraft/command/argument/ArgumentUtils.mapping
  mappings/net/minecraft/command/argument/BlockArgumentParser.mapping
  mappings/net/minecraft/command/argument/BlockPosArgumentType.mapping
  mappings/net/minecraft/command/argument/EnumArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/command/argument/NbtPathArgumentType.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryEntryArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryEntryOrTagArgument.mapping
  mappings/net/minecraft/command/argument/RegistryKeyOrTagKeyResult.mapping
  mappings/net/minecraft/command/argument/ResourceKeyArgument.mapping
  mappings/net/minecraft/command/argument/ScoreHolderArgumentType.mapping
  mappings/net/minecraft/command/argument/SingletonArgumentInfo.mapping
  mappings/net/minecraft/command/argument/TimeArgumentType.mapping
  mappings/net/minecraft/command/suggestion/SuggestionProviders.mapping
  mappings/net/minecraft/entity/passive/HorseBaseEntity.mapping
  mappings/net/minecraft/network/packet/s2c/play/ServerMetadataS2CPacket.mapping
  mappings/net/minecraft/server/command/AttributeCommand.mapping
  mappings/net/minecraft/server/command/CloneCommand.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/DamageCommand.mapping
  mappings/net/minecraft/server/command/DataCommand.mapping
  mappings/net/minecraft/server/command/DatapackCommand.mapping
  mappings/net/minecraft/server/command/EffectCommand.mapping
  mappings/net/minecraft/server/command/EnchantCommand.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/server/command/FillBiomeCommand.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
  mappings/net/minecraft/server/command/MeCommand.mapping
  mappings/net/minecraft/server/command/MessageCommand.mapping
  mappings/net/minecraft/server/command/PlaceCommand.mapping
  mappings/net/minecraft/server/command/RideCommand.mapping
  mappings/net/minecraft/server/command/SayCommand.mapping
  mappings/net/minecraft/server/command/ScheduleCommand.mapping
  mappings/net/minecraft/server/command/SummonCommand.mapping
  mappings/net/minecraft/server/command/TeamMsgCommand.mapping
  mappings/net/minecraft/server/command/WeatherCommand.mapping
  mappings/net/minecraft/server/command/dev/SpawnArmorTrimCommand.mapping
  mappings/net/minecraft/unmapped/C_ybgoyqmh.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/gen/trunk/UpwardsBranchingTrunkPlacer.mapping
Labels: t: new, v: snapshot, final-comment-period, s: large

#364 [1.19.3] Update Enigma to 1.6.1
  gradle/libs.versions.toml
Labels: t: toolchain, v: release, final-comment-period, s: tiny

#363 23w07a item and block things
  build.gradle
  mappings/net/minecraft/block/AbstractButtonBlock.mapping
  mappings/net/minecraft/block/AbstractPressurePlateBlock.mapping
  mappings/net/minecraft/block/BlockRenderType.mapping
  mappings/net/minecraft/block/BlockSetType.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/CaveVines.mapping
  mappings/net/minecraft/block/ChiseledBookshelfBlock.mapping
  mappings/net/minecraft/block/DecoratedPotBlock.mapping
  mappings/net/minecraft/block/DoorBlock.mapping
  mappings/net/minecraft/block/Material.mapping
  mappings/net/minecraft/block/PressurePlateBlock.mapping
  mappings/net/minecraft/block/TrapdoorBlock.mapping
  mappings/net/minecraft/block/WeightedPressurePlateBlock.mapping
  mappings/net/minecraft/block/entity/ChiseledBookshelfBlockEntity.mapping
  mappings/net/minecraft/block/entity/DecoratedPotBlockEntity.mapping
  mappings/net/minecraft/block/entity/HopperBlockEntity.mapping
  mappings/net/minecraft/block/entity/JukeboxBlockEntity.mapping
  mappings/net/minecraft/block/entity/SuspiciousSandBlockEntity.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/inventory/JukeboxInventory.mapping
  mappings/net/minecraft/item/BrushItem.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterial.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterials.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPatterns.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPermutation.mapping
  mappings/net/minecraft/recipe/RecipeManager.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#362 Random 23w07a mappings.
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/listener/PacketListener.mapping
  mappings/net/minecraft/network/packet/Packet.mapping
  mappings/net/minecraft/network/packet/PacketBundle.mapping
  mappings/net/minecraft/network/packet/s2c/play/DamageEventS2CPacket.mapping
  mappings/net/minecraft/resource/ReloadableResourceManager.mapping
  mappings/net/minecraft/resource/ResourceReload.mapping
  mappings/net/minecraft/resource/ResourceReloader.mapping
  mappings/net/minecraft/resource/ResourceType.mapping
  mappings/net/minecraft/resource/SimpleResourceReload.mapping
  mappings/net/minecraft/resource/pack/AbstractFileResourcePack.mapping
  mappings/net/minecraft/resource/pack/FileResourcePackProvider.mapping
  mappings/net/minecraft/resource/pack/NioResourcePack.mapping
  mappings/net/minecraft/resource/pack/VanillaDataPackProvider.mapping
  mappings/net/minecraft/resource/pack/ZipResourcePack.mapping
  mappings/net/minecraft/resource/pack/metadata/PackFeatureFlagsMetadata.mapping
  mappings/net/minecraft/resource/pack/metadata/PackResourceMetadata.mapping
  mappings/net/minecraft/resource/pack/metadata/ResourceFilterMetadata.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/ServerMetadata.mapping
  mappings/net/minecraft/util/collection/DataPool.mapping
  mappings/net/minecraft/util/math/ChunkPos.mapping
  mappings/net/minecraft/world/ChunkRegion.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/CollisionView.mapping
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
  mappings/net/minecraft/world/Difficulty.mapping
  mappings/net/minecraft/world/FeatureUpdater.mapping
  mappings/net/minecraft/world/ForcedChunkState.mapping
  mappings/net/minecraft/world/IdCountsState.mapping
  mappings/net/minecraft/world/LocalDifficulty.mapping
  mappings/net/minecraft/world/MobSpawnerEntry.mapping
  mappings/net/minecraft/world/MobSpawnerLogic.mapping
  mappings/net/minecraft/world/PersistentState.mapping
  mappings/net/minecraft/world/PortalForcer.mapping
  mappings/net/minecraft/world/RaycastContext.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/WanderingTraderManager.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  mappings/net/minecraft/world/WorldSaveProperties.mapping
  mappings/net/minecraft/world/biome/Biomes.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
Labels: t: refactor, t: new, v: snapshot, t: javadoc, final-comment-period, s: medium

#365 potions!
  mappings/net/minecraft/potion/Potions.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#367 Pack Metadata Provider mappings
  mappings/net/minecraft/data/server/PackMetadataProvider.mapping
Labels: t: new, v: release, final-comment-period, s: tiny

#369 Improve buildscript tests
  buildSrc/src/test/java/quilt/internal/TasksTest.java
  buildSrc/src/test/java/quilt/internal/mappingio/CompleteInitializersVisitorTest.java
  buildSrc/src/test/java/quilt/internal/mappingio/MappingVisitorTestBase.java
  buildSrc/src/test/java/quilt/internal/util/MappingAssertions.java
Labels: enhancement, t: toolchain, v: snapshot, reviews needed, s: small

#372 Map dynamic registry sync utility class
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/registry/DynamicRegistrySync.mapping
  mappings/net/minecraft/test/GameTest.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#374 add getArea() mapping in Widget
  mappings/net/minecraft/client/gui/widget/Widget.mapping
Labels: t: new, v: snapshot, critical, s: tiny

#375 Backport #372 to 1.19.3
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/registry/DynamicRegistrySync.mapping
Labels: t: port, v: release, final-comment-period, s: tiny
