Repository QuiltMC/quilt-mappings, pull requests merged in 2023-06, with the labels that each got.

#438 Remove mentions of datapack in favor of DataPack
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/client/gui/screen/DataPackFailureScreen.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/DataPackCommand.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#443 map some biome things and misc important things
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/recipe/DecoratedPotRecipe.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/recipe/RecipeMatcher.mapping
  mappings/net/minecraft/registry/VanillaDynamicRegistries.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/structure/ConcentricRingPlacementCalculator.mapping
  mappings/net/minecraft/world/ChunkLightBlockView.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/ChunkUpdateState.mapping
  mappings/net/minecraft/world/biome/OverworldBiomeCreator.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/biome/source/TheEndBiomeSource.mapping
  mappings/net/minecraft/world/biome/util/MultiNoiseBiomeSourceParameterList.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/feature/EndPlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/MiscPlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/NetherPlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/OceanPlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/OrePlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/TreePlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/UndergroundPlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/VegetationPlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/VillagePlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/util/PlacedFeatureUtil.mapping
Labels: t: new, v: release, final-comment-period, s: small

#437 Adjust the FCP durations for QM's needs
  CONTRIBUTING.md
Labels: t: toolchain, v: release, reviews needed

#445 Randomly map stuff again! (Refactor Edition)
  mappings/com/mojang/blaze3d/glfw/Window.mapping
  mappings/net/minecraft/block/CropBlock.mapping
  mappings/net/minecraft/block/Fertilizable.mapping
  mappings/net/minecraft/block/FungusBlock.mapping
  mappings/net/minecraft/block/PitcherCropBlock.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/KeyBind.mapping
  mappings/net/minecraft/client/option/Option.mapping
  mappings/net/minecraft/client/option/StickyKeyBind.mapping
  mappings/net/minecraft/client/render/animation/AnimationKeyframe.mapping
  mappings/net/minecraft/client/render/animation/PartAnimation.mapping
  mappings/net/minecraft/client/render/entity/model/ModelWithWaterPatch.mapping
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/fix/StatsCounterFix.mapping
  mappings/net/minecraft/sound/BiomeAdditionsSound.mapping
  mappings/net/minecraft/sound/BiomeMoodSound.mapping
  mappings/net/minecraft/stat/Stat.mapping
  mappings/net/minecraft/stat/StatFormatter.mapping
  mappings/net/minecraft/util/CommonColors.mapping
  mappings/net/minecraft/util/JsonHelper.mapping
  mappings/net/minecraft/util/SimpleBitStorage.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/ZipCompressor.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/world/MobSpawnerEntry.mapping
Labels: t: refactor, t: new, v: release, final-comment-period, s: small

#449 rename placeLogsAndLeaves to updateLeavesDistances
  mappings/net/minecraft/world/gen/feature/TreeFeature.mapping
Labels: t: refactor, v: release, final-comment-period, s: tiny

#450 Update enigma to 1.8.4
  gradle/libs.versions.toml
Labels: t: toolchain, v: release, final-comment-period, s: tiny

#451 Move ServerNetworkIo to net.minecraft.server.network
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/server/network/LocalServerHandshakeNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerNetworkIo.mapping
Labels: t: refactor, t: new, v: release, final-comment-period, s: tiny

#452 map some world and generation stuff
  mappings/net/minecraft/entity/boss/dragon/EnderDragonFight.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/world/FeatureUpdater.mapping
  mappings/net/minecraft/world/MobSpawnerEntry.mapping
  mappings/net/minecraft/world/PersistentStateManager.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/WorldSaveProperties.mapping
  mappings/net/minecraft/world/WorldView.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/util/MultiNoiseUtil.mapping
  mappings/net/minecraft/world/biome/source/util/OverworldBiomeParameters.mapping
  mappings/net/minecraft/world/dimension/WorldDimensions.mapping
  mappings/net/minecraft/world/gen/DensityFunction.mapping
  mappings/net/minecraft/world/gen/DensityFunctions.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
Labels: t: new, v: release, final-comment-period, s: medium
