Repository QuiltMC/quilt-mappings, pull requests merged in 2023-10, with the labels that each got.

#503 Packet listener mappings
  mappings/net/minecraft/client/gui/hud/chat/ChatMessageTag.mapping
  mappings/net/minecraft/client/network/ChatListener.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/network/listener/ClientPongPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerCommonPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommonPlayerSpawnInfo.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameStateUpdateS2CPacket.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#502 Proguard tweaks
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/test/java/quilt/internal/TasksTest.java
Labels: bug, enhancement, t: toolchain, v: snapshot, final-comment-period, s: tiny

#506 Fix sequence fields
  mappings/net/minecraft/client/multiplayer/prediction/PredictiveAction.mapping
  mappings/net/minecraft/client/network/BlockUpdatePredictionManager.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/client/network/PlayerActionPacketFactory.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerActionC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractionWithBlockC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractionWithItemC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/BlockUpdateAcknowledgmentS2CPacket.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#509 Added getAirSpeedMultiplier mapping in AquaticMoveControl
  mappings/net/minecraft/entity/ai/control/AquaticMoveControl.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#507 rename RecipeBook.toBeDisplayed and related methods
  mappings/net/minecraft/recipe/book/RecipeBook.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#508 Fix some misnomers
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#510 Added isValidPathNodeType mapping for method in EntityNavigation.
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#500 Map 1.20.2 abuse reporting changes and additions (previously just chat reporting)
  mappings/net/minecraft/client/gui/AbuseReportCategory.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/ChatReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/ChatSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/report/AbstractAbuseReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/report/AbuseReportCategoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/report/AbuseReportTypeScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/report/ChatAbuseReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/report/SkinAbuseReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/report/UsernameAbuseReportScreen.mapping
  mappings/net/minecraft/client/gui/widget/PlayerSkinModelWidget.mapping
  mappings/net/minecraft/client/gui/widget/list/multiplayer/SocialInteractionsPlayerElementListWidget.mapping
  mappings/net/minecraft/client/multiplayer/chat/LoggedChatMessage.mapping
  mappings/net/minecraft/client/multiplayer/report/AbstractAbuseReport.mapping
  mappings/net/minecraft/client/multiplayer/report/AbuseReportContext.mapping
  mappings/net/minecraft/client/multiplayer/report/AbuseReportContextBuilder.mapping
  mappings/net/minecraft/client/multiplayer/report/AbuseReportEnvironment.mapping
  mappings/net/minecraft/client/multiplayer/report/AbuseReportReason.mapping
  mappings/net/minecraft/client/multiplayer/report/AbuseReportSender.mapping
  mappings/net/minecraft/client/multiplayer/report/AbuseReportType.mapping
  mappings/net/minecraft/client/multiplayer/report/ChatAbuseReport.mapping
  mappings/net/minecraft/client/multiplayer/report/SkinAbuseReport.mapping
  mappings/net/minecraft/client/multiplayer/report/UsernameAbuseReport.mapping
  mappings/net/minecraft/client/multiplayer/report/chat/ChatReportContextBuilder.mapping
  mappings/net/minecraft/client/multiplayer/report/chat/ChatReportingContext.mapping
Labels: t: refactor, t: new, v: snapshot, final-comment-period, s: medium

#511 Added canPathDirectlyThrough mapping for method in EntityNavigation
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny
