Repository QuiltMC/quilt-mappings, pull requests merged in 2024-02, with the labels that each got.

#540 Fully map n/m/{village, stat, advancement, inventory}
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/AdvancementCriterion.mapping
  mappings/net/minecraft/advancement/AdvancementDisplay.mapping
  mappings/net/minecraft/advancement/AdvancementHolder.mapping
  mappings/net/minecraft/advancement/criterion/AnyBlockUseCriterionTrigger.mapping
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/DefaultBlockUseCriterionTrigger.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/inventory/JukeboxInventory.mapping
  mappings/net/minecraft/inventory/LootableInventory.mapping
  mappings/net/minecraft/inventory/SimpleInventory.mapping
  mappings/net/minecraft/stat/Stat.mapping
  mappings/net/minecraft/stat/StatType.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/village/TradeOfferList.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/village/VillagerData.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#543 Some command and ServerWorld-related mappings
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/server/dedicated/command/TransferCommand.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/math/random/RandomSequencesState.mapping
  mappings/net/minecraft/world/PersistentStateManager.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#544 Armor mappings
  mappings/net/minecraft/item/AnimalArmorItem.mapping
  mappings/net/minecraft/item/ArmorItem.mapping
  mappings/net/minecraft/item/ArmorMaterial.mapping
  mappings/net/minecraft/item/ArmorMaterials.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPermutation.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#546 Some random mappings
  mappings/com/mojang/blaze3d/lighting/DiffuseLighting.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/com/mojang/blaze3d/texture/NativeImage.mapping
  mappings/com/mojang/blaze3d/vertex/OverlayVertexConsumer.mapping
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/block/VaultBlock.mapping
  mappings/net/minecraft/block/entity/VaultBlockEntity.mapping
  mappings/net/minecraft/block/enums/VaultState.mapping
  mappings/net/minecraft/client/font/FreeTypeUtil.mapping
  mappings/net/minecraft/client/gui/screen/DataPackFailureScreen.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipProvider.mapping
  mappings/net/minecraft/client/gui/widget/list/multiplayer/ServerEntryListWidget.mapping
  mappings/net/minecraft/client/render/block/entity/TrialSpawnerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/VaultBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/WindChargeEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/BreezeEyesFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/BreezeWindFeatureRenderer.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/entity/WindChargeEntity.mapping
  mappings/net/minecraft/entity/damage/DamageTypes.mapping
  mappings/net/minecraft/nbt/StringNbtReader.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/common/DebugSampleS2CPacket.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/util/DebugSampleType.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/InteractionResult.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/UuidUtil.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/ServerWorldProperties.mapping
  mappings/net/minecraft/world/updater/WorldUpdater.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#549 Map new world events
  mappings/net/minecraft/world/WorldEvents.mapping
  unpick-definitions/world_events.unpick
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#548 Trial spawner mappings
  mappings/net/minecraft/block/Spawner.mapping
  mappings/net/minecraft/block/TrialSpawnerConfig.mapping
  mappings/net/minecraft/block/TrialSpawnerData.mapping
  mappings/net/minecraft/block/entity/TrialSpawnerBlockEntity.mapping
  mappings/net/minecraft/block/enums/TrialSpawnerState.mapping
  mappings/net/minecraft/client/render/block/entity/MobSpawnerBlockEntityRenderer.mapping
  mappings/net/minecraft/world/EntityDetector.mapping
  mappings/net/minecraft/world/MobSpawnerEntry.mapping
  mappings/net/minecraft/world/TrialSpawnerLogic.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#542 A few n/m/block and n/m/inventory mappings
  mappings/net/minecraft/block/BlockRegistryKeys.mapping
  mappings/net/minecraft/block/TrialSpawnerBlock.mapping
  mappings/net/minecraft/block/entity/DecoratedPotBlockEntity.mapping
  mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/inventory/SingleStackInventory.mapping
Labels: bug, t: new, v: snapshot, final-comment-period, s: tiny

#534 remove <ENTITY>_ prefixes from Animation fields
  mappings/net/minecraft/client/render/entity/animation/ArmadilloEntityAnimations.mapping
  mappings/net/minecraft/client/render/entity/animation/CamelEntityAnimations.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#551 Realms gui mappings
  mappings/net/minecraft/client/gui/screen/realms/RealmsBackupScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsBrokenWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsConfigureWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsCreateRealmScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsGenericErrorScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsMainScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsNotificationsScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsParentalConsentScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsPendingInvitesScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsResetNormalWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsResetWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsSelectWorldTemplateScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsSlotOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsUploadScreen.mapping
  mappings/net/minecraft/client/realms/task/CreateSnapshotRealmTask.mapping
  mappings/net/minecraft/world/storage/WorldSaveSummary.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#545 Misc updates to a bunch of things
  mappings/net/minecraft/command/argument/ItemStackArgumentType.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/TextArgumentType.mapping
  mappings/net/minecraft/item/FilledMapItem.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/map/MapBannerMarker.mapping
  mappings/net/minecraft/item/map/MapIcon.mapping
  mappings/net/minecraft/item/map/MapId.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterials.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPatterns.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/NetworkSide.mapping
  mappings/net/minecraft/network/NetworkStateTransitionHandler.mapping
  mappings/net/minecraft/network/PacketBundler.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/PacketEncoder.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/network/codec/PacketEncoder.mapping
  mappings/net/minecraft/network/packet/s2c/play/BlockEntityUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/BossBarUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommandSuggestionsUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/MapUpdateS2CPacket.mapping
  mappings/net/minecraft/particle/ParticleEffect.mapping
  mappings/net/minecraft/screen/AbstractRecipeScreenHandler.mapping
  mappings/net/minecraft/screen/BeaconScreenHandler.mapping
  mappings/net/minecraft/screen/EnchantmentScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/SmithingScreenHandler.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
  mappings/net/minecraft/text/CommonTexts.mapping
  mappings/net/minecraft/text/HoverEvent.mapping
  mappings/net/minecraft/text/Style.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/text/TextCodecs.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#552 Particle mappings
  mappings/net/minecraft/client/particle/BillboardParticle.mapping
  mappings/net/minecraft/client/particle/CherryLeafParticle.mapping
  mappings/net/minecraft/client/particle/DustPlumeParticle.mapping
  mappings/net/minecraft/client/particle/FlyTowardsPositionParticle.mapping
  mappings/net/minecraft/client/particle/GustEmitterParticle.mapping
  mappings/net/minecraft/client/particle/GustParticle.mapping
  mappings/net/minecraft/client/particle/ItemPickupParticle.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/particle/ShriekParticle.mapping
  mappings/net/minecraft/client/particle/SpriteProvider.mapping
  mappings/net/minecraft/client/particle/TrialSpawnerDetectionParticle.mapping
  mappings/net/minecraft/client/particle/VibrationParticle.mapping
  mappings/net/minecraft/client/particle/WhiteSmokeParticle.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small
