Repository QuiltMC/quilt-mappings, pull requests merged in 2024-01, with the labels that each got.

#522 Fix mapping source conflicts
  mappings/net/minecraft/client/gui/ElementPath.mapping
  mappings/net/minecraft/predicate/entity/EntityVariantPredicate.mapping
  mappings/net/minecraft/predicate/entity/TypeSpecificPredicate.mapping
  mappings/net/minecraft/text/component/StringComponent.mapping
  mappings/net/minecraft/util/function/ToFloatFunction.mapping
Labels: bug, v: snapshot, final-comment-period, s: tiny

#521 advancement mappings + codecs!
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/AdvancementCriterion.mapping
  mappings/net/minecraft/advancement/AdvancementDisplay.mapping
  mappings/net/minecraft/advancement/AdvancementRequirements.mapping
  mappings/net/minecraft/advancement/AdvancementType.mapping
  mappings/net/minecraft/advancement/criterion/AbstractCriterionTrigger.mapping
  mappings/net/minecraft/advancement/criterion/BeeNestDestroyedCriterionTrigger.mapping
  mappings/net/minecraft/advancement/criterion/BrewedPotionCriterionTrigger.mapping
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/CriterionConditions.mapping
  mappings/net/minecraft/advancement/criterion/CriterionTrigger.mapping
  mappings/net/minecraft/advancement/criterion/CriterionValidator.mapping
  mappings/net/minecraft/advancement/criterion/EnterBlockCriterionTrigger.mapping
  mappings/net/minecraft/advancement/criterion/InventoryChangedCriterionTrigger.mapping
  mappings/net/minecraft/advancement/criterion/SlideDownBlockCriterionTrigger.mapping
  mappings/net/minecraft/loot/condition/LootConditionTypes.mapping
  mappings/net/minecraft/predicate/ContextAwarePredicate.mapping
  mappings/net/minecraft/predicate/StatePredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/text/TextCodecs.mapping
  mappings/net/minecraft/util/ErrorReporter.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#520 Status effect mappings
  mappings/net/minecraft/entity/effect/AbsorptionStatusEffect.mapping
  mappings/net/minecraft/entity/effect/BadOmenStatusEffect.mapping
  mappings/net/minecraft/entity/effect/HungerStatusEffect.mapping
  mappings/net/minecraft/entity/effect/InstantHealthOrDamageStatusEffect.mapping
  mappings/net/minecraft/entity/effect/PoisonStatusEffect.mapping
  mappings/net/minecraft/entity/effect/RegenerationStatusEffect.mapping
  mappings/net/minecraft/entity/effect/SaturationStatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/effect/StatusEffectUtil.mapping
  mappings/net/minecraft/entity/effect/StatusEffects.mapping
  mappings/net/minecraft/entity/effect/WitherStatusEffect.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityStatusEffectUpdateS2CPacket.mapping
  mappings/net/minecraft/util/ChatUtil.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#524 Item mappings
  mappings/net/minecraft/block/sculk/SculkSensorBlock.mapping
  mappings/net/minecraft/client/gui/GuiGraphics.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsParentalConsentScreen.mapping
  mappings/net/minecraft/client/texture/PlayerSkinTexture.mapping
  mappings/net/minecraft/command/EntitySelectorReader.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/item/AnimalArmorItem.mapping
  mappings/net/minecraft/item/AxeItem.mapping
  mappings/net/minecraft/item/BoatItem.mapping
  mappings/net/minecraft/item/BrushItem.mapping
  mappings/net/minecraft/item/DyeableAnimalArmorItem.mapping
  mappings/net/minecraft/item/FilledMapItem.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/map/MapIcon.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPermutation.mapping
  mappings/net/minecraft/predicate/entity/EntityVariantPredicate.mapping
  mappings/net/minecraft/world/PersistentState.mapping
  mappings/net/minecraft/world/gen/chunk/BlendingData.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#525 Village mappings
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/village/TradeOfferList.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/village/VillagerGossips.mapping
  mappings/net/minecraft/village/raid/RaidManager.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#527 Upgrade gradle to 8.5 and enigma 2.1.0
  build.gradle
  buildSrc/src/main/java/quilt/internal/tasks/build/CompressTinyTask.java
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: t: toolchain, v: snapshot, final-comment-period, s: tiny

#528 Various mapping updates
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/potion/Potion.mapping
  mappings/net/minecraft/potion/PotionUtil.mapping
  mappings/net/minecraft/potion/Potions.mapping
  mappings/net/minecraft/util/ItemScatterer.mapping
  mappings/net/minecraft/util/UrlConstants.mapping
  mappings/net/minecraft/util/UserCache.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/UuidUtil.mapping
  mappings/net/minecraft/util/collection/DataPool.mapping
  mappings/net/minecraft/util/math/BlockPointer.mapping
  mappings/net/minecraft/util/math/random/RandomSequence.mapping
  mappings/net/minecraft/util/profiler/Profiler.mapping
  mappings/net/minecraft/util/profiling/jfr/JvmProfiler.mapping
  mappings/net/minecraft/util/profiling/jfr/event/network/PacketEvent.mapping
  mappings/net/minecraft/util/profiling/jfr/stats/NetworkPacketSummary.mapping
  mappings/net/minecraft/util/random/RandomSeed.mapping
  mappings/net/minecraft/util/random/Xoroshiro128PlusPlusRandom.mapping
  mappings/net/minecraft/util/shape/BitSetVoxelSet.mapping
  mappings/net/minecraft/util/shape/FractionalDoubleList.mapping
  mappings/net/minecraft/util/shape/SimplePairList.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#531 Rename `Entity#isServer` to `#canAiMove`
  mappings/net/minecraft/entity/Entity.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#533 Datafixer mappings
  mappings/net/minecraft/datafixer/TypeReferences.mapping
  mappings/net/minecraft/datafixer/fix/ChoiceWriteReadFix.mapping
  mappings/net/minecraft/datafixer/fix/DropInvalidSignDataFix.mapping
  mappings/net/minecraft/datafixer/fix/LevelLegacyWorldGenSettingsFix.mapping
  mappings/net/minecraft/datafixer/fix/PrimedTntBlockStateFix.mapping
  mappings/net/minecraft/datafixer/fix/ProjectileEntityItemTypeFix.mapping
  mappings/net/minecraft/datafixer/fix/RandomSequenceSettingsFix.mapping
  mappings/net/minecraft/datafixer/fix/RenameScoreboardDisplaySlotFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema3682.mapping
  mappings/net/minecraft/datafixer/schema/Schema3683.mapping
  mappings/net/minecraft/datafixer/schema/Schema3685.mapping
  mappings/net/minecraft/datafixer/schema/Schema3689.mapping
  mappings/net/minecraft/datafixer/schema/Schema3799.mapping
  mappings/net/minecraft/datafixers/fix/RandomSequenceSettingsFix.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#536 some mostly network related mappings
  mappings/net/minecraft/client/font/FreeTypeUtil.mapping
  mappings/net/minecraft/client/gui/screen/UnsupportedGraphicsScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsLongRunningMcoTaskScreen.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsLongRunningMcoTickableTaskScreen.mapping
  mappings/net/minecraft/client/realms/task/CreateWorldTask.mapping
  mappings/net/minecraft/network/ConnectionPhase.mapping
  mappings/net/minecraft/network/CookieStorage.mapping
  mappings/net/minecraft/network/PhaseConfiguration.mapping
  mappings/net/minecraft/network/packet/ConfigurationPacketTypes.mapping
  mappings/net/minecraft/network/packet/CookiePacketTypes.mapping
  mappings/net/minecraft/network/packet/HandshakePacketTypes.mapping
  mappings/net/minecraft/network/packet/LoginPacketTypes.mapping
  mappings/net/minecraft/network/packet/Packet.mapping
  mappings/net/minecraft/network/packet/PacketType.mapping
  mappings/net/minecraft/network/packet/PingPacketTypes.mapping
  mappings/net/minecraft/network/packet/PlayPacketTypes.mapping
  mappings/net/minecraft/network/packet/QueryPacketTypes.mapping
  mappings/net/minecraft/network/packet/StatusPacketTypes.mapping
  mappings/net/minecraft/network/packet/c2s/configuration/CookieResponseC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/BlockEntityTagQueryC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CommandBlockUpdateC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/ContainerSlotChangedC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/EntityTagQueryC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/ResetScorePacketS2C.mapping
  mappings/net/minecraft/network/packet/s2c/configuration/CookieRequestS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/BlockEventS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/BundleSplitterDelimiterS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ScoreboardObjectiveUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/query/StoreCookieS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/query/TransferS2CPacket.mapping
  mappings/net/minecraft/network/phase/ConfigurationPhases.mapping
  mappings/net/minecraft/network/phase/HandshakePhases.mapping
  mappings/net/minecraft/network/phase/LoginPhases.mapping
  mappings/net/minecraft/network/phase/PlayPhases.mapping
  mappings/net/minecraft/network/phase/StatusPhases.mapping
  mappings/net/minecraft/server/network/ClientInformation.mapping
  mappings/net/minecraft/server/network/ServerConfigurationNetworkHandler.mapping
  mappings/net/minecraft/util/FormattedException.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#537 Rename `Crafter` to `CrafterBlock`
  mappings/net/minecraft/block/CrafterBlock.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#535 Remove redundant docs
  mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
  mappings/net/minecraft/util/CommonColors.mapping
Labels: documentation, v: snapshot, final-comment-period, s: small

#538 Some Registry Names Refactoring
  mappings/net/minecraft/registry/Registries.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny
