Repository QuiltMC/quilt-mappings, pull requests merged in 2024-08, with the labels that each got.

#619 some mappings for worldrenderer
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: t: new, v: release, final-comment-period, s: tiny

#623 Complete nearly everything in item
  mappings/net/minecraft/item/BlockItem.mapping
  mappings/net/minecraft/item/CrossbowItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/LeadItem.mapping
  mappings/net/minecraft/item/UnsizedItemStackSet.mapping
  mappings/net/minecraft/item/map/MapDecorationTypes.mapping
  mappings/net/minecraft/item/map/MapState.mapping
Labels: t: new, v: release, final-comment-period, s: small

#624 f_zeffevqh uses BUILT_IN instead of BUILTIN #614
  mappings/net/minecraft/resource/pack/VanillaDataPackProvider.mapping
Labels: bug, v: release, final-comment-period, s: tiny

#612 some nbt work
  mappings/net/minecraft/nbt/NbtByteArray.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/nbt/NbtDouble.mapping
  mappings/net/minecraft/nbt/NbtElement.mapping
  mappings/net/minecraft/nbt/NbtFloat.mapping
  mappings/net/minecraft/nbt/NbtFormatException.mapping
  mappings/net/minecraft/nbt/NbtInt.mapping
  mappings/net/minecraft/nbt/NbtIntArray.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/nbt/NbtList.mapping
  mappings/net/minecraft/nbt/NbtLong.mapping
  mappings/net/minecraft/nbt/NbtLongArray.mapping
  mappings/net/minecraft/nbt/NbtOps.mapping
  mappings/net/minecraft/nbt/NbtShort.mapping
  mappings/net/minecraft/nbt/NbtString.mapping
  mappings/net/minecraft/nbt/NbtType.mapping
  mappings/net/minecraft/nbt/StringNbtReader.mapping
  mappings/net/minecraft/nbt/scanner/NbtScanner.mapping
  mappings/net/minecraft/nbt/scanner/SelectiveNbtCollector.mapping
  mappings/net/minecraft/nbt/visitor/FieldTree.mapping
  mappings/net/minecraft/nbt/visitor/NbtTextFormatter.mapping
  mappings/net/minecraft/nbt/visitor/SkipFields.mapping
  mappings/net/minecraft/nbt/visitor/StringNbtWriter.mapping
  mappings/net/minecraft/util/DelegatingDataOutput.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#626 command stuff attempt 2
  mappings/net/minecraft/command/EntitySelector.mapping
  mappings/net/minecraft/command/EntitySelectorReader.mapping
  mappings/net/minecraft/command/SignedCommand.mapping
  mappings/net/minecraft/command/argument/EntityArgumentType.mapping
  mappings/net/minecraft/command/argument/GameProfileArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemSlotsArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStackArgument.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/command/argument/NbtPathArgumentType.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/ScoreHolderArgumentType.mapping
  mappings/net/minecraft/command/argument/StyleArgumentType.mapping
  mappings/net/minecraft/loot/function/CopyCustomDataLootFunction.mapping
Labels: t: new, v: release, final-comment-period, s: small

#629 enable same-name proposal on non hashed mappings
  buildSrc/src/main/java/quilt/internal/tasks/lint/FindDuplicateMappingFilesTask.java
  enigma_profile.json
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
Labels: t: toolchain, v: snapshot, final-comment-period, s: medium

#628 World Renderer and Friends Mappings
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/com/mojang/blaze3d/framegraph/FrameGraphBuilder.mapping
  mappings/com/mojang/blaze3d/framegraph/FramePass.mapping
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/com/mojang/blaze3d/resource/CrossFrameResourcePool.mapping
  mappings/com/mojang/blaze3d/resource/GraphicsResourceAllocator.mapping
  mappings/com/mojang/blaze3d/resource/Handle.mapping
  mappings/com/mojang/blaze3d/resource/ResourceDescriptor.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/client/gl/ShaderEffect.mapping
  mappings/net/minecraft/client/render/BackgroundRenderer.mapping
  mappings/net/minecraft/client/render/BufferBuilderStorage.mapping
  mappings/net/minecraft/client/render/BuiltChunkStorage.mapping
  mappings/net/minecraft/client/render/CloudRenderer.mapping
  mappings/net/minecraft/client/render/DimensionVisualEffects.mapping
  mappings/net/minecraft/client/render/FogParameters.mapping
  mappings/net/minecraft/client/render/Frustum.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/LightmapTextureManager.mapping
  mappings/net/minecraft/client/render/MapRenderer.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/SectionOcclusionGraph.mapping
  mappings/net/minecraft/client/render/ShaderEffectConfig.mapping
  mappings/net/minecraft/client/render/ShaderProgram.mapping
  mappings/net/minecraft/client/render/ShapeRenderer.mapping
  mappings/net/minecraft/client/render/SkyRenderer.mapping
  mappings/net/minecraft/client/render/WeatherRenderer.mapping
  mappings/net/minecraft/client/render/WorldBorderRenderer.mapping
  mappings/net/minecraft/client/render/WorldFramebuffers.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/animation/Animator.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBufferBuilderPool.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBufferStorage.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/chunk/ChunkRenderRegion.mapping
  mappings/net/minecraft/client/render/chunk/ChunkRenderRegionCache.mapping
  mappings/net/minecraft/client/render/chunk/SectionBuilder.mapping
  mappings/net/minecraft/client/render/debug/OcclusionGraphDebugRenderer.mapping
  mappings/net/minecraft/client/render/state/MapRenderState.mapping
  mappings/net/minecraft/client/texture/MapSpriteManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/util/ArgbHelper.mapping
  mappings/net/minecraft/util/CommonColors.mapping
  mappings/net/minecraft/util/TriState.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: t: new, v: snapshot, t: javadoc, final-comment-period, s: large

#635 100% n.m.block
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/CommandBlock.mapping
  mappings/net/minecraft/block/EntityShapeContext.mapping
  mappings/net/minecraft/block/HeavyCoreBlock.mapping
  mappings/net/minecraft/block/PlantBlock.mapping
  mappings/net/minecraft/block/RedstoneTorchBlock.mapping
  mappings/net/minecraft/block/RedstoneWireBlock.mapping
  mappings/net/minecraft/block/ShapeContext.mapping
  mappings/net/minecraft/block/TrialSpawnerData.mapping
  mappings/net/minecraft/block/VaultBlock.mapping
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntityType.mapping
  mappings/net/minecraft/block/entity/FuelTimes.mapping
  mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
  mappings/net/minecraft/block/entity/VaultBlockEntity.mapping
  mappings/net/minecraft/block/entity/vault/VaultBlockEntity.mapping
  mappings/net/minecraft/block/entity/vault/VaultClientData.mapping
  mappings/net/minecraft/block/entity/vault/VaultConfig.mapping
  mappings/net/minecraft/block/entity/vault/VaultServerData.mapping
  mappings/net/minecraft/block/entity/vault/VaultSharedData.mapping
  mappings/net/minecraft/block/enums/RailShape.mapping
  mappings/net/minecraft/block/enums/VaultState.mapping
  mappings/net/minecraft/feature_flags/FeatureFlags.mapping
  mappings/net/minecraft/util/ActionResult.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/logic/ExperimentalRedstoneUtil.mapping
  mappings/net/minecraft/world/logic/Orientation.mapping
  mappings/net/minecraft/world/logic/RedstoneController.mapping
  unpick-definitions/set_block_state_flags.unpick
Labels: t: refactor, t: new, v: snapshot, final-comment-period, s: medium

#636 Fix a couple armor-y things
  mappings/net/minecraft/client/render/entity/feature/ArmorFeatureRenderer.mapping
  mappings/net/minecraft/recipe/ArmorDyeRecipe.mapping
  mappings/net/minecraft/recipe/DyeableRecipe.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny
