Repository QuiltMC/quilt-mappings, pull requests merged in 2024-09, with the labels that each got.

#638 24w37a ender pearls
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/EnderPearlEntity.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#639 Map OggAudioStream and some related stuff
  mappings/net/minecraft/client/sound/BufferedAudioStream.mapping
  mappings/net/minecraft/client/sound/ChannelList.mapping
  mappings/net/minecraft/client/sound/FiniteAudioStream.mapping
  mappings/net/minecraft/client/sound/OggAudioStream.mapping
Labels: t: port, v: snapshot, final-comment-period, s: small

#641 enigma 2.5.0 and plugin 2.2.3
  gradle/libs.versions.toml
Labels: t: toolchain, v: snapshot, s: tiny
