Repository QuiltMC/quilt-mappings, pull requests merged in 2024-10, with the labels that each got.

#644 Add a mappings server task
  build.gradle
  buildSrc/src/main/java/quilt/internal/tasks/mappings/EnigmaMappingsServerTask.java
Labels: enhancement, t: toolchain, v: snapshot, final-comment-period, s: small

#640 fix+clarify ChunkTickScheduler, complete n.m.world.tick
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/tick/ChunkTickScheduler.mapping
  mappings/net/minecraft/world/tick/OrderedTick.mapping
  mappings/net/minecraft/world/tick/ProtoChunkTicks.mapping
  mappings/net/minecraft/world/tick/SerializableTickScheduler.mapping
  mappings/net/minecraft/world/tick/Tick.mapping
  mappings/net/minecraft/world/tick/TickPriority.mapping
  mappings/net/minecraft/world/tick/TickScheduler.mapping
  mappings/net/minecraft/world/tick/TickSchedulerAccess.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: small

#637 Fix a couple loot-y things
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#648 map missing biome tags
  mappings/net/minecraft/registry/tag/BiomeTags.mapping
Labels: t: new, v: snapshot, reviews needed, s: tiny

#646 Named methods in `CreeperEntity` and `World`.
  mappings/net/minecraft/entity/mob/CreeperEntity.mapping
  mappings/net/minecraft/world/World.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny

#651 fix method conflict in `RegistrySetBuilder`
  mappings/net/minecraft/registry/RegistrySetBuilder.mapping
Labels: bug, t: refactor, v: snapshot, critical, s: tiny

#631 map recipes
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/recipe/AbstractCookingRecipe.mapping
  mappings/net/minecraft/recipe/BrewingRecipeRegistry.mapping
  mappings/net/minecraft/recipe/CookingCategory.mapping
  mappings/net/minecraft/recipe/CraftingHandler.mapping
  mappings/net/minecraft/recipe/CraftingRecipe.mapping
  mappings/net/minecraft/recipe/DecoratedPotRecipe.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/recipe/IngredientPlacement.mapping
  mappings/net/minecraft/recipe/InputSlotFiller.mapping
  mappings/net/minecraft/recipe/ItemMapper.mapping
  mappings/net/minecraft/recipe/Recipe.mapping
  mappings/net/minecraft/recipe/RecipeAccess.mapping
  mappings/net/minecraft/recipe/RecipeDisplayEntry.mapping
  mappings/net/minecraft/recipe/RecipeDisplayId.mapping
  mappings/net/minecraft/recipe/RecipeFinder.mapping
  mappings/net/minecraft/recipe/RecipeInputProvider.mapping
  mappings/net/minecraft/recipe/RecipeManager.mapping
  mappings/net/minecraft/recipe/RecipeMap.mapping
  mappings/net/minecraft/recipe/RecipeMatcher.mapping
  mappings/net/minecraft/recipe/RecipePlacementHelper.mapping
  mappings/net/minecraft/recipe/RecipePropertySet.mapping
  mappings/net/minecraft/recipe/RepairItemRecipe.mapping
  mappings/net/minecraft/recipe/SelectableRecipe.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
  mappings/net/minecraft/recipe/ShapedRecipePattern.mapping
  mappings/net/minecraft/recipe/ShapelessRecipe.mapping
  mappings/net/minecraft/recipe/SingleItemRecipe.mapping
  mappings/net/minecraft/recipe/SmithingRecipe.mapping
  mappings/net/minecraft/recipe/SpecialCraftingRecipe.mapping
  mappings/net/minecraft/recipe/StonecuttingRecipe.mapping
  mappings/net/minecraft/recipe/TransformSmithingRecipe.mapping
  mappings/net/minecraft/recipe/TransmuteRecipe.mapping
  mappings/net/minecraft/recipe/TrimSmithingRecipe.mapping
  mappings/net/minecraft/recipe/book/RecipeBook.mapping
  mappings/net/minecraft/recipe/book/RecipeBookCategory.mapping
  mappings/net/minecraft/recipe/book/RecipeBookOptions.mapping
  mappings/net/minecraft/recipe/book/RecipeBookType.mapping
  mappings/net/minecraft/recipe/display/FurnaceRecipeDisplay.mapping
  mappings/net/minecraft/recipe/display/RecipeDisplay.mapping
  mappings/net/minecraft/recipe/display/ShapedCraftingRecipeDisplay.mapping
  mappings/net/minecraft/recipe/display/ShapelessCraftingRecipeDisplay.mapping
  mappings/net/minecraft/recipe/display/SlotDisplay.mapping
  mappings/net/minecraft/recipe/display/SlotDisplayContext.mapping
  mappings/net/minecraft/recipe/display/SmithingRecipeDisplay.mapping
  mappings/net/minecraft/recipe/display/StonecutterRecipeDisplay.mapping
  mappings/net/minecraft/screen/AbstractCraftingScreenHandler.mapping
  mappings/net/minecraft/screen/AbstractRecipeScreenHandler.mapping
  mappings/net/minecraft/screen/CraftingScreenHandler.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/context/ContextKey.mapping
  mappings/net/minecraft/util/context/ContextKeySet.mapping
  mappings/net/minecraft/util/context/ContextMap.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/ServerWorldProperties.mapping
  mappings/net/minecraft/world/World.mapping
  simple_type_field_names.json5
Labels: t: new, v: snapshot, final-comment-period, s: medium

#650 Mapped some fields and methods in CreakingBrain and CreakingEntity.
  mappings/net/minecraft/entity/mob/CreakingBrain.mapping
  mappings/net/minecraft/entity/mob/CreakingEntity.mapping
Labels: t: new, v: snapshot, final-comment-period, s: tiny
