Repository QuiltMC/quilt-mappings, pull requests merged in 2024-07, with the labels that each got.

#598 start mapping new enchantment system
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/component/EnchantmentEffectComponentTypes.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentEffectContext.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/enchantment/EnchantmentLevelEntry.mapping
  mappings/net/minecraft/enchantment/Enchantments.mapping
  mappings/net/minecraft/enchantment/LevelBasedValue.mapping
  mappings/net/minecraft/enchantment/effect/AddValue.mapping
  mappings/net/minecraft/enchantment/effect/AllOfEffects.mapping
  mappings/net/minecraft/enchantment/effect/ApplyMobEffect.mapping
  mappings/net/minecraft/enchantment/effect/ConditionalEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/DamageEntity.mapping
  mappings/net/minecraft/enchantment/effect/DamageImmunity.mapping
  mappings/net/minecraft/enchantment/effect/DamageItem.mapping
  mappings/net/minecraft/enchantment/effect/EnchantmentAttribute.mapping
  mappings/net/minecraft/enchantment/effect/EnchantmentEffectTarget.mapping
  mappings/net/minecraft/enchantment/effect/EnchantmentEntityEffect.mapping
  mappings/net/minecraft/enchantment/effect/EnchantmentLocationBasedEffect.mapping
  mappings/net/minecraft/enchantment/effect/EnchantmentValueEffect.mapping
  mappings/net/minecraft/enchantment/effect/Explode.mapping
  mappings/net/minecraft/enchantment/effect/Ignite.mapping
  mappings/net/minecraft/enchantment/effect/MultiplyValue.mapping
  mappings/net/minecraft/enchantment/effect/PlaySound.mapping
  mappings/net/minecraft/enchantment/effect/RemoveBinomial.mapping
  mappings/net/minecraft/enchantment/effect/ReplaceBlock.mapping
  mappings/net/minecraft/enchantment/effect/ReplaceDisk.mapping
  mappings/net/minecraft/enchantment/effect/RunFunction.mapping
  mappings/net/minecraft/enchantment/effect/SetBlockProperties.mapping
  mappings/net/minecraft/enchantment/effect/SetValue.mapping
  mappings/net/minecraft/enchantment/effect/SpawnParticles.mapping
  mappings/net/minecraft/enchantment/effect/SummonEntity.mapping
  mappings/net/minecraft/enchantment/effect/TargetConditionalEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/provider/EnchantmentProvider.mapping
  mappings/net/minecraft/entity/DamageUtil.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/damage/DamageType.mapping
  mappings/net/minecraft/item/FoodComponent.mapping
  mappings/net/minecraft/loot/condition/AllOfLootCondition.mapping
  mappings/net/minecraft/world/explosion/SimpleExplosionBehavior.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#613 wordlist and deps update
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/quilt/internal/decompile/Decompilers.java
  buildSrc/src/main/java/quilt/internal/decompile/cfr/CfrDecompiler.java
  buildSrc/src/main/java/quilt/internal/decompile/cfr/CfrObfuscationMapping.java
  buildSrc/src/main/java/quilt/internal/decompile/cfr/CfrSinkFactory.java
  buildSrc/src/main/java/quilt/internal/mappingio/DoubleNsCompleterVisitor.java
  buildSrc/src/main/java/quilt/internal/mappingio/UnmappedNameRemoverVisitor.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AbstractTinyMergeTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/AddProposedMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/RemoveIntermediaryTask.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/DownloadDictionaryFileTask.java
  buildSrc/src/main/java/quilt/internal/tasks/unpick/RemapUnpickDefinitionsTask.java
  buildSrc/src/main/java/quilt/internal/util/MappingsJavadocProvider.java
  gradle/libs.versions.toml
Labels: t: toolchain, v: release, final-comment-period, s: medium

#608 Work on items
  mappings/net/minecraft/item/AdventureModePredicate.mapping
  mappings/net/minecraft/item/AnimalArmorItem.mapping
  mappings/net/minecraft/item/ArrowItem.mapping
  mappings/net/minecraft/item/AxeItem.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/CrossbowItem.mapping
  mappings/net/minecraft/item/FireworkRocketItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/ItemUsage.mapping
  mappings/net/minecraft/item/LeadItem.mapping
  mappings/net/minecraft/item/MaceItem.mapping
  mappings/net/minecraft/item/OminousBottleItem.mapping
  mappings/net/minecraft/item/RangedWeaponItem.mapping
  mappings/net/minecraft/item/SmithingTemplateItem.mapping
  mappings/net/minecraft/item/TridentItem.mapping
  mappings/net/minecraft/item/WindChargeItem.mapping
  mappings/net/minecraft/item/map/MapDecorationType.mapping
  mappings/net/minecraft/item/map/MapDecorationTypes.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPermutation.mapping
Labels: t: new, v: release, final-comment-period, s: tiny

#610 Bunch of resource stuff
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/resource/ClientBuiltinResourcePackProvider.mapping
  mappings/net/minecraft/client/resource/RemoteResourcePackProvider.mapping
  mappings/net/minecraft/client/resource/language/LanguageManager.mapping
  mappings/net/minecraft/client/resource/remote/Downloader.mapping
  mappings/net/minecraft/client/resource/remote/Reloader.mapping
  mappings/net/minecraft/client/resource/remote/RemotePackFeedback.mapping
  mappings/net/minecraft/client/resource/remote/RemotePackManager.mapping
  mappings/net/minecraft/client/resource/remote/RemoteResourcePackProvider.mapping
  mappings/net/minecraft/client/sound/SoundManager.mapping
  mappings/net/minecraft/client/util/NetworkUtils.mapping
  mappings/net/minecraft/registry/RegistryKeys.mapping
  mappings/net/minecraft/resource/PackPosition.mapping
  mappings/net/minecraft/resource/pack/BuiltinPackProvider.mapping
  mappings/net/minecraft/resource/pack/FilePackProvider.mapping
  mappings/net/minecraft/resource/pack/PackManager.mapping
  mappings/net/minecraft/resource/pack/PackProfile.mapping
  mappings/net/minecraft/resource/pack/PackProvider.mapping
  mappings/net/minecraft/server/ServerAdvancementLoader.mapping
  mappings/net/minecraft/server/ServerReloadableResources.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
  mappings/net/minecraft/util/DownloadCacheManager.mapping
  mappings/net/minecraft/util/DownloadQueue.mapping
  mappings/net/minecraft/util/ErrorReporter.mapping
Labels: t: refactor, t: new, v: release, final-comment-period, s: medium

#615 Some rendering stuff
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/com/mojang/blaze3d/font/Font.mapping
  mappings/com/mojang/blaze3d/font/FontOption.mapping
  mappings/com/mojang/blaze3d/font/SheetGlyphInfo.mapping
  mappings/com/mojang/blaze3d/font/TrueTypeFont.mapping
  mappings/com/mojang/blaze3d/framebuffer/Framebuffer.mapping
  mappings/com/mojang/blaze3d/shader/GlUniform.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/com/mojang/blaze3d/vertex/Buffer.mapping
  mappings/com/mojang/blaze3d/vertex/BufferBuilder.mapping
  mappings/com/mojang/blaze3d/vertex/BufferRenderer.mapping
  mappings/com/mojang/blaze3d/vertex/BuiltBuffer.mapping
  mappings/com/mojang/blaze3d/vertex/OverlayVertexConsumer.mapping
  mappings/com/mojang/blaze3d/vertex/Tessellator.mapping
  mappings/com/mojang/blaze3d/vertex/VertexBuffer.mapping
  mappings/com/mojang/blaze3d/vertex/VertexConsumer.mapping
  mappings/com/mojang/blaze3d/vertex/VertexFormat.mapping
  mappings/com/mojang/blaze3d/vertex/VertexFormatElement.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/FontStorage.mapping
  mappings/net/minecraft/client/font/FontTypeProvider.mapping
  mappings/net/minecraft/client/font/FreeTypeUtil.mapping
  mappings/net/minecraft/client/font/MultilineText.mapping
  mappings/net/minecraft/client/gl/JsonEffectGlShader.mapping
  mappings/net/minecraft/client/gl/PostProcessShader.mapping
  mappings/net/minecraft/client/gl/ShaderEffect.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/render/Camera.mapping
  mappings/net/minecraft/client/render/DeltaTracker.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/MapRenderer.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/ShaderProgram.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/VertexConsumerProvider.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/FluidRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BannerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BeaconBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/DecoratedPotBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SkullBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/StructureBlockBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/VaultBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GoalSelectorDebugRenderer.mapping
  mappings/net/minecraft/client/render/entity/ItemEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/animation/BreezeEntityAnimations.mapping
  mappings/net/minecraft/client/render/item/HeldItemRenderer.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/util/ColorUtil.mapping
  mappings/net/minecraft/client/util/ModelIdentifier.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
  mappings/net/minecraft/util/DyeColor.mapping
  mappings/net/minecraft/util/math/Box.mapping
Labels: t: new, v: release, final-comment-period, s: large

#611 improve villager
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
Labels: t: refactor, v: release, final-comment-period, s: tiny

#616 100% `net/minecraft/world/gen`
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/world/gen/DensityFunctions.mapping
  mappings/net/minecraft/world/gen/NoiseHelper.mapping
  mappings/net/minecraft/world/gen/RandomState.mapping
  mappings/net/minecraft/world/gen/StructureChecker.mapping
  mappings/net/minecraft/world/gen/StructureWeightSampler.mapping
  mappings/net/minecraft/world/gen/blockpredicate/BlockPredicate.mapping
  mappings/net/minecraft/world/gen/blockpredicate/BlockPredicateType.mapping
  mappings/net/minecraft/world/gen/blockpredicate/UnobstructedBlockPredicate.mapping
  mappings/net/minecraft/world/gen/chunk/AquiferSampler.mapping
  mappings/net/minecraft/world/gen/chunk/Blender.mapping
  mappings/net/minecraft/world/gen/chunk/BlendingData.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkNoiseSampler.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGeneratorConfig.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/feature/DesertPyramidFeature.mapping
  mappings/net/minecraft/world/gen/feature/DesertWellFeature.mapping
  mappings/net/minecraft/world/gen/feature/DimensionPadding.mapping
  mappings/net/minecraft/world/gen/feature/EndConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/EndPlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/EndPlatformFeature.mapping
  mappings/net/minecraft/world/gen/feature/EndPortalFeature.mapping
  mappings/net/minecraft/world/gen/feature/FeatureSorter.mapping
  mappings/net/minecraft/world/gen/feature/FixedPlacementModifier.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungusFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeMushroomFeature.mapping
  mappings/net/minecraft/world/gen/feature/IcebergFeature.mapping
  mappings/net/minecraft/world/gen/feature/JigsawFeature.mapping
  mappings/net/minecraft/world/gen/feature/LiquidSettings.mapping
  mappings/net/minecraft/world/gen/feature/MineshaftFeature.mapping
  mappings/net/minecraft/world/gen/feature/OreConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/OrePlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/VegetationConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/util/ConfiguredFeatureUtil.mapping
  mappings/net/minecraft/world/gen/feature/util/PlacedFeatureUtil.mapping
  mappings/net/minecraft/world/gen/foliage/CherryFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
  mappings/net/minecraft/world/gen/material/WorldGenMaterialRule.mapping
  mappings/net/minecraft/world/gen/noise/BuiltinNoiseParameters.mapping
  mappings/net/minecraft/world/gen/noise/NoiseParametersKeys.mapping
  mappings/net/minecraft/world/gen/noise/NoiseRouter.mapping
  mappings/net/minecraft/world/gen/noise/NoiseRouterData.mapping
  mappings/net/minecraft/world/gen/structure/TerrainAdjustment.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceRules.mapping
  mappings/net/minecraft/world/gen/trunk/CherryTrunkPlacer.mapping
Labels: t: refactor, t: new, v: release, final-comment-period, s: medium

#617 Add `findDuplicateMappingFiles` task
  buildSrc/src/main/java/quilt/internal/MappingsPlugin.java
  buildSrc/src/main/java/quilt/internal/tasks/lint/FindDuplicateMappingFilesTask.java
  mappings/net/minecraft/datafixer/fix/AttributeIdFix.mapping
  mappings/net/minecraft/datafixer/fix/AttributeModifierIdFix.mapping
  mappings/net/minecraft/datafixer/fix/RemoveEmptyItemInBrushableBlockFix.mapping
Labels: enhancement, t: toolchain, reviews needed, final-comment-period, s: small
