Repository QuiltMC/quilt-mappings, pull requests merged in 2024-06, with the labels that each got.

#595 fix typo in buttonwidget builder
  mappings/net/minecraft/client/gui/widget/button/ButtonWidget.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#592 mapped Identifier
  mappings/net/minecraft/util/Identifier.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#593 completed recipe and inventory
  mappings/net/minecraft/block/entity/BrewingStandBlockEntity.mapping
  mappings/net/minecraft/inventory/RecipeInputInventory.mapping
  mappings/net/minecraft/inventory/StackReference.mapping
  mappings/net/minecraft/recipe/AbstractCookingRecipe.mapping
  mappings/net/minecraft/recipe/BrewingRecipeRegistry.mapping
  mappings/net/minecraft/recipe/CookingRecipeSerializer.mapping
  mappings/net/minecraft/recipe/CraftingRecipeInput.mapping
  mappings/net/minecraft/recipe/CuttingRecipe.mapping
  mappings/net/minecraft/recipe/InputSlotFiller.mapping
  mappings/net/minecraft/recipe/MapExtendingRecipe.mapping
  mappings/net/minecraft/recipe/Recipe.mapping
  mappings/net/minecraft/recipe/RecipeCache.mapping
  mappings/net/minecraft/recipe/RecipeGridAligner.mapping
  mappings/net/minecraft/recipe/RecipeInput.mapping
  mappings/net/minecraft/recipe/RecipeManager.mapping
  mappings/net/minecraft/recipe/RepairItemRecipe.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
  mappings/net/minecraft/recipe/ShapedRecipePattern.mapping
  mappings/net/minecraft/recipe/ShapelessRecipe.mapping
  mappings/net/minecraft/recipe/SingleRecipeInput.mapping
  mappings/net/minecraft/recipe/SmithingRecipeInput.mapping
  mappings/net/minecraft/recipe/TransformSmithingRecipe.mapping
  mappings/net/minecraft/recipe/TrimSmithingRecipe.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#597 update enigma to 2.4
  buildSrc/src/main/java/quilt/internal/tasks/build/AddProposedMappingsTask.java
  buildSrc/src/main/java/quilt/internal/tasks/build/BuildMappingsTinyTask.java
  gradle/libs.versions.toml
Labels: t: toolchain, reviews needed, s: tiny

#599 Random assortment of partial mappings
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/com/mojang/blaze3d/glfw/Window.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/DecoratedPotPattern.mapping
  mappings/net/minecraft/block/DecoratedPotPatterns.mapping
  mappings/net/minecraft/block/WoodType.mapping
  mappings/net/minecraft/block/dispenser/ItemDispenserBehavior.mapping
  mappings/net/minecraft/block/sapling/SaplingBlock.mapping
  mappings/net/minecraft/block/sapling/TreeGrower.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/GameMenuScreen.mapping
  mappings/net/minecraft/client/gui/screen/GenericMessageScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/ServerLinksScreen.mapping
  mappings/net/minecraft/client/gui/widget/list/EntryListWidget.mapping
  mappings/net/minecraft/client/render/DeltaTracker.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderers.mapping
  mappings/net/minecraft/client/render/entity/OminousItemSpawnerEntityRenderer.mapping
  mappings/net/minecraft/data/server/tag/TradeRebalanceEnchantmentTagsProvider.mapping
  mappings/net/minecraft/datafixer/fix/AttributeModifierIdFix.mapping
  mappings/net/minecraft/datafixer/fix/ChoiceWriteReadFix.mapping
  mappings/net/minecraft/datafixer/fix/EmptyItemInVillagerTradeFix.mapping
  mappings/net/minecraft/datafixer/fix/JukeboxTicksSinceSongStartedFix.mapping
  mappings/net/minecraft/datafixer/fix/OptionsMenuBlurrinessFix.mapping
  mappings/net/minecraft/datafixer/fix/ParticleUnflatteningFix.mapping
  mappings/net/minecraft/datafixer/fix/RemoveEmptyItemInBrushableBlockFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema3808v2.mapping
  mappings/net/minecraft/datafixer/schema/Schema3818v5.mapping
  mappings/net/minecraft/datafixer/schema/Schema3938.mapping
  mappings/net/minecraft/nbt/NbtCrashException.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  simple_type_field_names.json5
Labels: t: new, v: snapshot, final-comment-period, s: small
