Repository QuiltMC/quilt-mappings, pull requests merged in 2024-04, with the labels that each got.

#571 a few random mappings
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/block/DecoratedPotPatterns.mapping
  mappings/net/minecraft/block/HeavyCoreBlock.mapping
  mappings/net/minecraft/block/HopperBlock.mapping
  mappings/net/minecraft/block/TrialSpawnerBlock.mapping
  mappings/net/minecraft/block/VaultBlock.mapping
  mappings/net/minecraft/command/argument/CoordinateArgument.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemSlotArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemSlotsArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/OperationArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryEntryOrTagArgument.mapping
  mappings/net/minecraft/command/argument/StyleArgumentType.mapping
  mappings/net/minecraft/command/argument/UuidArgumentType.mapping
  mappings/net/minecraft/data/client/ItemModelGenerator.mapping
  mappings/net/minecraft/data/server/RecipesProvider.mapping
  mappings/net/minecraft/data/server/loot/one_twenty_one/OneTwentyOneEquipmentLootTableProvider.mapping
  mappings/net/minecraft/data/server/loot_table/EquipmentLootTableGenerator.mapping
  mappings/net/minecraft/enchantment/BreachEnchantment.mapping
  mappings/net/minecraft/enchantment/DensityEnchantment.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/enchantment/WindBurstEnchantment.mapping
  mappings/net/minecraft/entity/passive/FrogVariant.mapping
  mappings/net/minecraft/inventory/Inventories.mapping
  mappings/net/minecraft/item/FoodComponent.mapping
  mappings/net/minecraft/item/FoodComponents.mapping
  mappings/net/minecraft/item/Instrument.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/item/MaceItem.mapping
  mappings/net/minecraft/item/MiningToolItem.mapping
  mappings/net/minecraft/item/OminousBottleItem.mapping
  mappings/net/minecraft/item/RangedWeaponItem.mapping
  mappings/net/minecraft/item/SmithingTemplateItem.mapping
  mappings/net/minecraft/item/SwordItem.mapping
  mappings/net/minecraft/item/WindChargeItem.mapping
  mappings/net/minecraft/item/map/MapDecorationType.mapping
  mappings/net/minecraft/item/map/MapDecorationTypes.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterial.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPattern.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPermutation.mapping
  mappings/net/minecraft/loot/LootTables.mapping
  mappings/net/minecraft/loot/condition/LocationCheckLootCondition.mapping
  mappings/net/minecraft/loot/context/LootContextTypes.mapping
  mappings/net/minecraft/loot/entry/LootTableEntry.mapping
  mappings/net/minecraft/loot/function/SetOminousBottleLootFunction.mapping
  mappings/net/minecraft/loot/function/SetWrittenBookPagesLootFunction.mapping
  mappings/net/minecraft/loot/function/ToggleTooltipsLootFunction.mapping
  mappings/net/minecraft/loot/provider/number/StorageLootNumberProvider.mapping
  mappings/net/minecraft/recipe/FireworkStarRecipe.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/text/TextCodecs.mapping
  mappings/net/minecraft/world/PersistentState.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#572 Did you want some more mappings here you go
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/block/dispenser/DispenserBlock.mapping
  mappings/net/minecraft/block/dispenser/ProjectileDispenserBehavior.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/option/AccessibilityOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/ChatOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/ControlsOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/FontOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/KeyBindOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/MouseOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/OnlineOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/OptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/SkinOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/SoundOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/VideoOptionsScreen.mapping
  mappings/net/minecraft/datafixer/fix/BlockEntityBannerNameComponentFix.mapping
  mappings/net/minecraft/datafixer/fix/BlockPosFormatFix.mapping
  mappings/net/minecraft/datafixer/fix/ChoiceWriteReadFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemStackComponentRemainderFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemStackNameComponentFix.mapping
  mappings/net/minecraft/datafixer/fix/LeavesFix.mapping
  mappings/net/minecraft/datafixer/fix/MapBannerBlockPosFormatFix.mapping
  mappings/net/minecraft/datafixer/fix/ProtoChunkTickListFix.mapping
  mappings/net/minecraft/datafixer/fix/TrialSpawnConfigTagFix.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreezeLongJumpTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreezeShootWhenStuckTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreezeSlideTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/LongJumpUtil.mapping
  mappings/net/minecraft/entity/ai/brain/task/RandomLookAroundTask.mapping
  mappings/net/minecraft/entity/effect/InfestedStatusEffect.mapping
  mappings/net/minecraft/entity/effect/OozingStatusEffect.mapping
  mappings/net/minecraft/entity/effect/RaidOmenStatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/effect/WeavingStatusEffect.mapping
  mappings/net/minecraft/entity/effect/WindChargedStatusEffect.mapping
  mappings/net/minecraft/item/ProjectileItem.mapping
  mappings/net/minecraft/network/HandlerNames.mapping
  mappings/net/minecraft/predicate/entity/EntitySubPredicateTypes.mapping
  mappings/net/minecraft/predicate/entity/RaiderPredicate.mapping
  mappings/net/minecraft/server/command/ClearCommand.mapping
  mappings/net/minecraft/server/command/CloneCommand.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#575 spellcheck dictionary update - remove "armour" and "initialise"
  buildSrc/src/main/java/quilt/internal/tasks/lint/DownloadDictionaryFileTask.java
Labels: t: toolchain, v: snapshot, final-comment-period, s: tiny

#574 some mappings in `n/m/world`
  mappings/net/minecraft/block/enums/TrialSpawnerState.mapping
  mappings/net/minecraft/entity/OminousItemSpawnerEntity.mapping
  mappings/net/minecraft/item/ProjectileItem.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/ChunkUpdateState.mapping
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
  mappings/net/minecraft/world/EntityDetector.mapping
  mappings/net/minecraft/world/ForcedChunkState.mapping
  mappings/net/minecraft/world/PersistentState.mapping
  mappings/net/minecraft/world/TrialSpawnerLogic.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  mappings/net/minecraft/world/WorldProperties.mapping
  mappings/net/minecraft/world/WorldView.mapping
  mappings/net/minecraft/world/biome/util/MultiNoiseBiomeSourceParameterList.mapping
  mappings/net/minecraft/world/chunk/ChunkType.mapping
  mappings/net/minecraft/world/event/GameEvent.mapping
  mappings/net/minecraft/world/event/PositionSourceType.mapping
  mappings/net/minecraft/world/event/listener/GameEventListener.mapping
  mappings/net/minecraft/world/storage/EntityChunkDataAccess.mapping
  mappings/net/minecraft/world/storage/ParsedSaveProperties.mapping
  mappings/net/minecraft/world/storage/RecreatedChunkStorage.mapping
  mappings/net/minecraft/world/storage/RegionFile.mapping
  mappings/net/minecraft/world/storage/RegionStorageKey.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
  mappings/net/minecraft/world/storage/SimpleRegionRecreationStorage.mapping
  mappings/net/minecraft/world/storage/SimpleRegionStorage.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
  mappings/net/minecraft/world/storage/WorldSaveStorage.mapping
  mappings/net/minecraft/world/updater/WorldUpdater.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#576 Rescue rai from mappings nightmare
  mappings/com/mojang/blaze3d/vertex/VertexConsumer.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/gui/GuiGraphics.mapping
  mappings/net/minecraft/client/gui/RotatingCubeMapRenderer.mapping
  mappings/net/minecraft/client/gui/hud/in_game/InGameHud.mapping
  mappings/net/minecraft/client/gui/screen/BackupPromptScreen.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/gui/screen/OutOfMemoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/ScreenArea.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/InventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SmithingScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/ControlsOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/FontOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/GameOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/LanguageOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/SkinOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditGameRulesScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/ExperimentalFeaturesWarningScreen.mapping
  mappings/net/minecraft/client/gui/widget/CheckboxWidget.mapping
  mappings/net/minecraft/client/gui/widget/button/ButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/button/CyclingButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/button/SpriteButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/list/option/KeyBindElementListWidget.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/sound/SoundManager.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
  mappings/net/minecraft/client/texture/MapDecorationSpriteManager.mapping
  mappings/net/minecraft/client/texture/StatusEffectSpriteManager.mapping
  mappings/net/minecraft/client/toast/RecipeToast.mapping
  mappings/net/minecraft/client/toast/SystemToast.mapping
  mappings/net/minecraft/client/toast/Toast.mapping
  mappings/net/minecraft/client/toast/ToastManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/client/world/WorldCreator.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/inventory/SimpleInventory.mapping
  mappings/net/minecraft/inventory/SlotRange.mapping
  mappings/net/minecraft/inventory/SlotRanges.mapping
  mappings/net/minecraft/item/map/MapIcon.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/world/GameRules.mapping
  mappings/net/minecraft/world/World.mapping
  src/constants/java/org/quiltmc/quiltmappings/constants/LlamaVariants.java
  src/constants/java/org/quiltmc/quiltmappings/constants/ParrotVariants.java
  unpick-definitions/llama_variants.unpick
  unpick-definitions/parrot_variants.unpick
Labels: t: new, v: snapshot, final-comment-period, s: medium

#578 fix buildscript for 24w14a
  .github/workflows/build.yml
  .github/workflows/generate-diff.yml
  .github/workflows/publish.yml
  .github/workflows/update-base.yml
  CONVENTIONS.md
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/quilt/internal/tasks/jarmapping/MapNamedJarTask.java
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
Labels: t: toolchain, v: snapshot

#580 fix deprecation errors
  buildSrc/src/main/java/quilt/internal/tasks/lint/MappingLintTask.java
Labels: t: toolchain, v: snapshot

#577 registry and inventory work
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/inventory/Inventories.mapping
  mappings/net/minecraft/inventory/LootableInventory.mapping
  mappings/net/minecraft/registry/DynamicRegistrySync.mapping
  mappings/net/minecraft/registry/HolderLookup.mapping
  mappings/net/minecraft/registry/HolderProvider.mapping
  mappings/net/minecraft/registry/HolderSet.mapping
  mappings/net/minecraft/registry/MutableRegistry.mapping
  mappings/net/minecraft/registry/RegistrationInfo.mapping
  mappings/net/minecraft/registry/Registry.mapping
  mappings/net/minecraft/registry/RegistryCloner.mapping
  mappings/net/minecraft/registry/RegistryFixedCodec.mapping
  mappings/net/minecraft/registry/RegistryKey.mapping
  mappings/net/minecraft/registry/RegistryLoader.mapping
  mappings/net/minecraft/registry/RegistryOps.mapping
  mappings/net/minecraft/registry/RegistrySetBuilder.mapping
  mappings/net/minecraft/registry/ReloadableRegistries.mapping
  mappings/net/minecraft/registry/SimpleRegistry.mapping
  mappings/net/minecraft/registry/tag/TagNetworkSerialization.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#579 complete entity, particle, and sound
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityAttachments.mapping
  mappings/net/minecraft/entity/EquipmentSlotGroup.mapping
  mappings/net/minecraft/entity/EquipmentTable.mapping
  mappings/net/minecraft/entity/EquipmentUser.mapping
  mappings/net/minecraft/entity/OminousItemSpawnerEntity.mapping
  mappings/net/minecraft/entity/effect/InfestedStatusEffect.mapping
  mappings/net/minecraft/entity/effect/OozingStatusEffect.mapping
  mappings/net/minecraft/entity/effect/WeavingStatusEffect.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/passive/WolfVariants.mapping
  mappings/net/minecraft/entity/player/HungerConstants.mapping
  mappings/net/minecraft/entity/player/HungerManager.mapping
  mappings/net/minecraft/particle/ColoredParticleEffect.mapping
  mappings/net/minecraft/particle/ParticleTypes.mapping
  mappings/net/minecraft/particle/VibrationParticleEffect.mapping
  mappings/net/minecraft/sound/SoundEvent.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small

#581 complete components, text, and village
  mappings/net/minecraft/client/item/TooltipConfig.mapping
  mappings/net/minecraft/component/DataComponentMap.mapping
  mappings/net/minecraft/component/DataComponentPatch.mapping
  mappings/net/minecraft/component/DataComponentType.mapping
  mappings/net/minecraft/component/PatchedDataComponentMap.mapping
  mappings/net/minecraft/component/type/AttributeModifiersComponent.mapping
  mappings/net/minecraft/component/type/BookContent.mapping
  mappings/net/minecraft/component/type/BundleContentsComponent.mapping
  mappings/net/minecraft/component/type/ContainerContentsComponent.mapping
  mappings/net/minecraft/component/type/DyedColorComponent.mapping
  mappings/net/minecraft/component/type/ItemEnchantmentsComponent.mapping
  mappings/net/minecraft/component/type/UnbreakableComponent.mapping
  mappings/net/minecraft/component/type/WritableBookContentComponent.mapping
  mappings/net/minecraft/component/type/WrittenBookContentComponent.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/TooltipAppender.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPermutation.mapping
  mappings/net/minecraft/predicate/DataComponentPredicate.mapping
  mappings/net/minecraft/registry/tag/EnchantmentTags.mapping
  mappings/net/minecraft/text/HoverEvent.mapping
  mappings/net/minecraft/text/TextCodecs.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/village/TradeableItem.mapping
Labels: t: new, v: snapshot, final-comment-period, s: small
