Repository QuiltMC/quilt-mappings, pull requests merged in 2024-03, with the labels that each got.

#556 World stuff
  mappings/net/minecraft/nbt/NbtFormatException.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/registry/HolderLookup.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/world/ChunkUpdateState.mapping
  mappings/net/minecraft/world/ForcedChunkState.mapping
  mappings/net/minecraft/world/GameRules.mapping
  mappings/net/minecraft/world/IdCountsState.mapping
  mappings/net/minecraft/world/PersistentState.mapping
  mappings/net/minecraft/world/PersistentStateManager.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/event/BlockPositionSource.mapping
  mappings/net/minecraft/world/event/EntityPositionSource.mapping
  mappings/net/minecraft/world/event/GameEvent.mapping
  mappings/net/minecraft/world/event/PositionSource.mapping
  mappings/net/minecraft/world/event/PositionSourceType.mapping
  mappings/net/minecraft/world/event/listener/GameEventListener.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
  mappings/net/minecraft/world/storage/ChunkStreamVersion.mapping
  mappings/net/minecraft/world/storage/EntityChunkDataAccess.mapping
  mappings/net/minecraft/world/storage/RegionBasedStorage.mapping
  mappings/net/minecraft/world/storage/RegionFile.mapping
  mappings/net/minecraft/world/storage/RegionStorage.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
  mappings/net/minecraft/world/storage/StorageInfo.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
  mappings/net/minecraft/world/storage/WorldSaveStorage.mapping
  mappings/net/minecraft/world/updater/SeparatedOutputVersionedChunkStorage.mapping
  mappings/net/minecraft/world/updater/SeparatedRegionStorage.mapping
  mappings/net/minecraft/world/updater/WorldUpdater.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#547 renamed Merchant.sendOffers Text param to merchantName
  mappings/net/minecraft/village/Merchant.mapping
Labels: bug, t: refactor, v: snapshot, reviews needed, final-comment-period, s: tiny

#558 More mappings
  mappings/net/minecraft/client/gui/screen/ingame/CartographyTableScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipe_book/RecipeBookGhostSlots.mapping
  mappings/net/minecraft/client/gui/screen/recipe_book/RecipeResultCollection.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/OptimizeWorldScreen.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipProvider.mapping
  mappings/net/minecraft/client/network/AbstractClientNetworkHandler.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/HotbarStorageEntry.mapping
  mappings/net/minecraft/client/option/Option.mapping
  mappings/net/minecraft/client/particle/FireworksSparkParticle.mapping
  mappings/net/minecraft/client/realms/FileUpload.mapping
  mappings/net/minecraft/client/render/Camera.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/MapRenderer.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/block/entity/VaultBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/ItemEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/StrayEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/WindChargeEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/WindChargeEntityModel.mapping
  mappings/net/minecraft/client/world/WorldCreator.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemPredicateReader.mapping
  mappings/net/minecraft/command/argument/ItemPredicateStringReader.mapping
  mappings/net/minecraft/command/argument/ItemSlotArgumentType.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/listener/ClientConfigurationPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerConfigurationPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/ConfigurationPacketTypes.mapping
  mappings/net/minecraft/network/packet/c2s/configuration/SelectKnownPacksC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/DebugSampleSubscriptionC2SPacket.mapping
  mappings/net/minecraft/network/packet/payload/CustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/configuration/SelectKnownPacksS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerListS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/TeamUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/data/LightData.mapping
  mappings/net/minecraft/network/packet/s2c/query/StoreCookieS2CPacket.mapping
  mappings/net/minecraft/potion/Potion.mapping
  mappings/net/minecraft/potion/Potions.mapping
Labels: t: new, v: snapshot, final-comment-period, s: medium

#563 More mappings (#558)
  mappings/net/minecraft/client/gui/screen/ingame/CartographyTableScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipe_book/RecipeBookGhostSlots.mapping
  mappings/net/minecraft/client/gui/screen/recipe_book/RecipeResultCollection.mapping
  mappings/net/minecraft/client/gui/screen/world/OptimizeWorldScreen.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipProvider.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/particle/FireworksSparkParticle.mapping
  mappings/net/minecraft/client/realms/FileUpload.mapping
  mappings/net/minecraft/client/render/MapRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/VaultBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/WindChargeEntityModel.mapping
  mappings/net/minecraft/command/argument/ItemPredicateReader.mapping
  mappings/net/minecraft/command/argument/ItemPredicateStringReader.mapping
  mappings/net/minecraft/command/argument/ItemSlotArgumentType.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/packet/c2s/configuration/SelectKnownPacksC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/DebugSampleSubscriptionC2SPacket.mapping
  mappings/net/minecraft/network/packet/payload/CustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/configuration/SelectKnownPacksS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerListS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/TeamUpdateS2CPacket.mapping
  mappings/net/minecraft/potion/Potion.mapping
Labels: t: port, v: snapshot, s: small

#562 Update github actions workflow steps
  .github/actions/diff-uploader/action.yml
  .github/actions/update-base/action.yml
  .github/workflows/build.yml
  .github/workflows/generate-diff.yml
  .github/workflows/publish.yml
  .github/workflows/update-base.yml
Labels: t: toolchain, v: snapshot, s: tiny

#559 item components
  mappings/net/minecraft/block/entity/BannerPattern.mapping
  mappings/net/minecraft/block/entity/BeehiveBlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/block/entity/Sherds.mapping
  mappings/net/minecraft/client/util/ColorUtil.mapping
  mappings/net/minecraft/component/DataComponent.mapping
  mappings/net/minecraft/component/DataComponentHolder.mapping
  mappings/net/minecraft/component/DataComponentMap.mapping
  mappings/net/minecraft/component/DataComponentPatch.mapping
  mappings/net/minecraft/component/DataComponentType.mapping
  mappings/net/minecraft/component/DataComponentTypes.mapping
  mappings/net/minecraft/component/PatchedDataComponentMap.mapping
  mappings/net/minecraft/component/type/AttributeModifiersComponent.mapping
  mappings/net/minecraft/component/type/BannerPatternsComponent.mapping
  mappings/net/minecraft/component/type/BlockStateComponent.mapping
  mappings/net/minecraft/component/type/BundleContentsComponent.mapping
  mappings/net/minecraft/component/type/ChargedProjectilesComponent.mapping
  mappings/net/minecraft/component/type/ContainerContentsComponent.mapping
  mappings/net/minecraft/component/type/ContainerLootComponent.mapping
  mappings/net/minecraft/component/type/CustomModelDataComponent.mapping
  mappings/net/minecraft/component/type/DebugStickStateComponent.mapping
  mappings/net/minecraft/component/type/DyedColorComponent.mapping
  mappings/net/minecraft/component/type/FireworkExplosionComponent.mapping
  mappings/net/minecraft/component/type/FireworksComponent.mapping
  mappings/net/minecraft/component/type/ItemEnchantmentsComponent.mapping
  mappings/net/minecraft/component/type/LodestoneTrackerComponent.mapping
  mappings/net/minecraft/component/type/LoreComponent.mapping
  mappings/net/minecraft/component/type/MapColorComponent.mapping
  mappings/net/minecraft/component/type/MapDecorationsComponent.mapping
  mappings/net/minecraft/component/type/MapPostProcessingComponent.mapping
  mappings/net/minecraft/component/type/NbtComponent.mapping
  mappings/net/minecraft/component/type/PotionContentsComponent.mapping
  mappings/net/minecraft/component/type/ProfileComponent.mapping
  mappings/net/minecraft/component/type/SuspiciousStewEffectsComponent.mapping
  mappings/net/minecraft/component/type/UnbreakableComponent.mapping
  mappings/net/minecraft/component/type/WritableBookContentComponent.mapping
  mappings/net/minecraft/component/type/WrittenBookContentComponent.mapping
  mappings/net/minecraft/entity/EquipmentSlotGroup.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeModifier.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/item/AdventureModePredicate.mapping
  mappings/net/minecraft/item/FilledMapItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/TooltipAppender.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterial.mapping
  mappings/net/minecraft/nbt/NbtOps.mapping
  mappings/net/minecraft/network/message/Filterable.mapping
  mappings/net/minecraft/predicate/BlockPredicate.mapping
  mappings/net/minecraft/registry/Holder.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: t: new, v: snapshot, final-comment-period, s: large
