Repository QuiltMC/quilt-mappings, pull requests merged in 2024-11, with the labels that each got.

#654 improve movement terminology
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: t: refactor, v: release, final-comment-period, s: tiny

#659 add a test to make sure broken unpick definitions error
  buildSrc/src/test/java/quilt/internal/TasksTest.java
  buildSrc/src/test/java/quilt/internal/TestUtil.java
  buildSrc/src/test/resources/testProject/broken-unpick-definitions/no_header.unpick
  buildSrc/src/test/resources/testProject/broken-unpick-definitions/working.unpick
  gradle/libs.versions.toml
Labels: t: toolchain, v: release, reviews needed, s: tiny

#657 some item model generator mappings
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/data/EquipmentModelDefinitionsProvider.mapping
  mappings/net/minecraft/data/client/ItemModelGenerator.mapping
  mappings/net/minecraft/item/equipment/EquipmentModel.mapping
  mappings/net/minecraft/item/equipment/EquipmentModels.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: t: new, v: release, final-comment-period, s: small

#658 update enigma to `2.5.2` and plugin to `2.3.1`
  build.gradle
  gradle/libs.versions.toml
  mappings/net/minecraft/client/render/model/BakedQuadFactory.mapping
  mappings/net/minecraft/loot/provider/score/LootScoreProvider.mapping
  mappings/net/minecraft/server/command/FunctionCommand.mapping
  mappings/net/minecraft/server/function/CommandFunction.mapping
Labels: t: toolchain, v: snapshot, final-comment-period, s: tiny

#667 Miscellaneous refactorings
  mappings/net/minecraft/client/gui/widget/button/SpriteButtonWidget.mapping
  mappings/net/minecraft/client/network/AbstractClientPlayerEntity.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny
