Repository QuiltMC/quilt-mappings, pull requests merged in 2024-05, with the labels that each got.

#582 Minecart Improvements
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
Labels: t: refactor, v: snapshot, wip, final-comment-period, s: tiny

#585 Enchantment and tool work
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/component/DataComponentTypes.mapping
  mappings/net/minecraft/component/type/ToolComponent.mapping
  mappings/net/minecraft/enchantment/BreachEnchantment.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/enchantment/WindBurstEnchantment.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/MaceItem.mapping
  mappings/net/minecraft/item/MiningToolItem.mapping
  mappings/net/minecraft/item/ShearsItem.mapping
  mappings/net/minecraft/item/SwordItem.mapping
  mappings/net/minecraft/item/ToolMaterial.mapping
  mappings/net/minecraft/item/ToolMaterials.mapping
  mappings/net/minecraft/item/TridentItem.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/world/explosion/Explosion.mapping
  mappings/net/minecraft/world/explosion/ExplosionBehavior.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: small

#586 Improved some `BoatEntity` mappings.
  mappings/net/minecraft/entity/vehicle/BoatEntity.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: tiny

#587 Improved some `BookEditScreen` and related names.
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/screen/LecternScreenHandler.mapping
Labels: bug, t: refactor, v: snapshot, final-comment-period, s: tiny

#588 Improved rail block related names.
  buildSrc/src/main/resources/minecraft_specific_words.txt
  mappings/net/minecraft/block/AbstractRailBlock.mapping
  mappings/net/minecraft/block/DetectorRailBlock.mapping
  mappings/net/minecraft/block/PoweredRailBlock.mapping
  mappings/net/minecraft/block/RailShaper.mapping
Labels: bug, t: refactor, v: snapshot, final-comment-period, s: tiny

#591 Fixed range method mappings.
  mappings/net/minecraft/util/random/RandomGenerator.mapping
Labels: bug, t: refactor, v: snapshot, final-comment-period, s: tiny
