Repository QuiltMC/quilt-mappings, pull requests merged in 2025-01, with the labels that each got.

#674 1.21 fix final
  mappings/net/minecraft/entity/InteractionEntity.mapping
Labels: bug, v: release, reviews needed, critical, s: tiny

#675 1.21.1 fix final
  mappings/net/minecraft/entity/InteractionEntity.mapping
Labels: bug, v: release, reviews needed, critical, s: tiny

#676 1.21.2 fix final
  mappings/net/minecraft/entity/InteractionEntity.mapping
Labels: bug, v: release, reviews needed, critical, s: tiny

#677 1.21.3 fix final
  mappings/net/minecraft/entity/InteractionEntity.mapping
Labels: bug, v: release, reviews needed, critical, s: tiny

#682 update enigma and plugin for 1.21.1
  gradle/libs.versions.toml
Labels: bug, t: toolchain, v: release

#678 add mappings for Rarity
  mappings/net/minecraft/util/Rarity.mapping
Labels: t: new, v: release, final-comment-period, s: tiny

#679 add missing CommonColor constants
  mappings/net/minecraft/util/CommonColors.mapping
Labels: t: new, v: release, final-comment-period, s: tiny

#680 add mappings for LocationPredicate.Builder fields and setter methods
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
Labels: t: new, v: release, final-comment-period, s: tiny

#683 1.21.1 update enigma again
  gradle/libs.versions.toml
  mappings/net/minecraft/client/gui/screen/realms/RealmsMainScreen.mapping
  mappings/net/minecraft/client/gui/widget/button/realms/RealmsWorldSlotButtonWidget.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/realms/Ping.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/SizeUnit.mapping
  mappings/net/minecraft/client/realms/dto/RealmsServer.mapping
  mappings/net/minecraft/client/realms/dto/Subscription.mapping
  mappings/net/minecraft/client/realms/dto/WorldTemplate.mapping
  mappings/net/minecraft/datafixer/fix/StatsCounterFix.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/task/PlayWithVillagerBabiesTask.mapping
  mappings/net/minecraft/entity/passive/TameableEntity.mapping
  mappings/net/minecraft/network/LegacyQueryHandler.mapping
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/util/Rarity.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceRules.mapping
Labels: bug, t: toolchain, v: release, reviews needed, s: tiny

#684 1.21.2 port
  gradle/libs.versions.toml
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsMainScreen.mapping
  mappings/net/minecraft/client/gui/widget/button/realms/RealmsWorldSlotButtonWidget.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/realms/Ping.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/SizeUnit.mapping
  mappings/net/minecraft/client/realms/dto/RealmsServer.mapping
  mappings/net/minecraft/client/realms/dto/Subscription.mapping
  mappings/net/minecraft/client/realms/dto/WorldTemplate.mapping
  mappings/net/minecraft/datafixer/fix/StatsCounterFix.mapping
  mappings/net/minecraft/entity/ai/brain/task/PlayWithVillagerBabiesTask.mapping
  mappings/net/minecraft/entity/passive/TameableEntity.mapping
  mappings/net/minecraft/fluid/FlowableFluid.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/network/LegacyQueryHandler.mapping
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceRules.mapping
Labels: bug, t: port, t: toolchain, v: release, reviews needed, s: small

#685 1.21.3 port
  gradle/libs.versions.toml
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/net/minecraft/client/gui/screen/realms/RealmsMainScreen.mapping
  mappings/net/minecraft/client/gui/widget/button/realms/RealmsWorldSlotButtonWidget.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/realms/Ping.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/SizeUnit.mapping
  mappings/net/minecraft/client/realms/dto/RealmsServer.mapping
  mappings/net/minecraft/client/realms/dto/Subscription.mapping
  mappings/net/minecraft/client/realms/dto/WorldTemplate.mapping
  mappings/net/minecraft/datafixer/fix/StatsCounterFix.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/task/PlayWithVillagerBabiesTask.mapping
  mappings/net/minecraft/entity/passive/TameableEntity.mapping
  mappings/net/minecraft/fluid/FlowableFluid.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/network/LegacyQueryHandler.mapping
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
  mappings/net/minecraft/world/BlockView.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceRules.mapping
Labels: bug, t: port, t: toolchain, v: release, reviews needed, s: small

#671 fix `generateDiff` task when target version doesn't exist
  buildSrc/src/main/java/quilt/internal/plugin/ProcessMappingsPlugin.java
  buildSrc/src/main/java/quilt/internal/plugin/TargetDiffPlugin.java
  buildSrc/src/main/java/quilt/internal/task/diff/DecompileTargetVineflowerTask.java
  buildSrc/src/main/java/quilt/internal/task/diff/DiffDirectoriesTask.java
  buildSrc/src/main/java/quilt/internal/task/diff/DiffTargetTask.java
  buildSrc/src/main/java/quilt/internal/task/diff/LazilyDiffTargetTask.java
Labels: bug, t: toolchain, v: snapshot, final-comment-period, s: tiny

#653 rename LivingEntity setCurrentHand -> tryStartUsing and add javadoc
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: bug, t: refactor, v: snapshot, final-comment-period, s: tiny

#666 Dispenser stuff
  enigma/simple_type_field_names.json5
  mappings/net/minecraft/Bootstrap.mapping
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  mappings/net/minecraft/block/dispenser/DefaultDispenserBehavior.mapping
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/block/dispenser/DispenserBlock.mapping
  mappings/net/minecraft/block/dispenser/DispenserContext.mapping
  mappings/net/minecraft/block/dispenser/EquipmentDispenserBehavior.mapping
  mappings/net/minecraft/block/dispenser/FallibleDispenserBehavior.mapping
  mappings/net/minecraft/block/dispenser/MinecartDispenserBehavior.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/command/EntitySelectorOptions.mapping
  mappings/net/minecraft/util/hit/BlockHitResult.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
Labels: t: refactor, v: snapshot, final-comment-period, s: small
